### ISSUE TITLE
Imported GLTF model does not show up

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#10]
I have a Tilt Brush model that I uploaded to Sketchfab. When I downloaded the gltf version and importing into Neos, nothing shows up in-world. The model is present in the object model via the development panel, and it does get a gizmo if selected, but the model does not show up.

Here is a link to where you can download this model: https://sketchfab.com/models/53a19edeff484cb19f26552d2a3a44e5#

**Comment by Frooxius** [comment]
Hmm looks like Assimp is having problem reading this one for some reason. I'm going to try close and compile a new version and report it to them if it doesn't work.

Alternatively I'm thinking of integrating the reference loader instead for importing the format, probably has much better support: https://github.com/KhronosGroup/glTF-CSharp-Loader

**Comment by Frooxius** [comment]
Upon further investigation it seems that there's some kind of bug in the .NET wrapper rather than the core Assimp library. Will see if I can find it.

**Comment by Frooxius** [comment]
Upon even further investigation it turns out that both the official model viewer built around the .NET wrapper and my importer implementation had the exact same bug and didn't account for a texture file path being null for some reason.

It is fixed now. However the glTF support in Assimp still seems incomplete, as it doesn't read materials correctly. I will switch to the official Khronos loader eventually for glTF.

Also compiled latest native version of Assimp, so that should have plenty of bugfixes and improvements on its own :) Pushed new build to nightly channel.
