### ISSUE TITLE
Increase the Lock-in Distance on the World Browser

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#1003]
I am unsure if this applies to all buttons, or just to the world browser, but currently I find that when I try to click a world it scrolls instead, because the action of pulling the trigger causes the laser to move down slightly. I have to focus on holding my controller quite still while clicking. It is very easy to back out of the modal on an accidental press, so I'm wondering if the lock-in distance could be increased.

**Comment by Frooxius** [comment]
I can increase it, it's a bit low right now, but I don't think it would be a good idea to do it just for the World Browser, it'd be a global change to keep the scrolling experience consistent.

**Comment by H3BO3** [comment]
A global change would work great. Thanks Froox!

**Comment by shiftyscales** [comment]
It wouldn't take a very big change either. I've also run into this, where I was scrolling instead of clicking. I've mostly stopped having that issue, but probably because I've had to adapt to being extra-careful to hold the controller steady.

That change will help with new users too I imagine since when the UI enters a scroll instead- the net result is that it feels like the trigger input was just dropped instead since they'd also let it go almost instantly after it entered a scroll.

**Comment by Frooxius** [comment]
Doubled the threshold in 2020.9.9.214, hopefully that makes this better. Let me know if it needs some more!
