### ISSUE TITLE
DynamicBoneChain on root of object prevents object from being deleted

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1006]
Discovered, and reported to me by PurpleJuice, if an object contains a DynamicBoneChain on the root of the object, the object is unable to be deleted by the context menu.

Steps to replicate:
- Spawn an object, e.g. a box
- Add a DynamicBoneChainComponent
- Attempt to delete the object via the context menu

It is able to be deleted through the inspector both with the preserve assets and non-preserving deletion buttons, and with the 'destroy selected' option on the DevToolTip.

There appears to be nothing of note in the logs regarding this issue:
[SHIFTYWINDOWS - 2020.9.6.1418 - 2020-09-08 20_04_18.log](https://github.com/Frooxius/NeosPublic/files/5192374/SHIFTYWINDOWS.-.2020.9.6.1418.-.2020-09-08.20_04_18.log)

**Comment by Frooxius** [comment]
This is intentional, it's to prevent accidentally deleting objects by holding onto the dynamic bones (e.g. this can happen by accident, when deleting stuff and grabbing part of your or someone else's avatar).

Dynamic Bones are designed to be mainly visual and not the way to grab and manipulate the whole object itself. I don't recommend setting them up on the root for this purpose, use a regular grabbable for that.

**Comment by shiftyscales** [comment]
I see! That makes sense, thanks.

**Comment by H3BO3** [comment]
Even if the root is not part of the bone chain? I have a setup that has a grabbable on it so I can pick it up and then a chain that affects slots further down. I am holding the grabbable but I still cannot delete the object.
