### ISSUE TITLE
Skinned mesh renderers invisible until 'Readable' is set to true

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1026]
Observed by Zyzyl, GearBell, ProbablePrime, and Ryuvi, a number of existing skinned meshes were invisible until the 'Readable' property was set to True.

Affected meshes include GearBell's hangar doors, and ProbablePrime's mask.

The common factor seems to be skinned meshes that have the 'Readable' property set to false (it is not certain how this property was set/why/when).

I'll post more if I learn more.

**Comment by H3BO3** [comment]
just to clarify my multitool was not affected, it was a joke :<

**Comment by Frooxius** [comment]
Can you send me examples of any of the meshes or their URL's? Can be in private DM if you don't want them public.

Does this affect all users equally or do some of them see the mesh and some don't?

However this sounds like it's coincidental, the Readable doesn't really affect anything relating to the mesh being displayed in particular, changing that property just forces the mesh to be reloaded, which can prod things through and make it load. 

I **strongly** discourage setting the meshes as readable unless you really need to, because there's a performance penalty for doing so. Typically you'd only ever do this if you wanted to use the mesh with a particle system.

**Comment by Zyzyl** [comment]
In the case I reported, the affected mesh seemed to be invisible to everyone in the world. As noted, setting the Readable property to True caused the mesh visual to appear. It became invisible again if Readable was reset to False. I have asked if mesh creator is happy to send a copy to you Froox.

As I mentioned on Discord, this particular mesh was invisible either when loaded from the Neos cloud as part of a saved world OR freshly imported from an fbx file.

**Comment by Frooxius** [comment]
Thanks! "Readable" doesn't really have much to do with visibility like that, so I'm not really sure what could possibly be causing that based on just the description. I'll definitely need the sample to look at so I can analyze problem.

**Comment by Princessii** [comment]
Hi, I had this issue with my diving board that I made and all it had was  1 blendshape. As soon as I get on I can import a clean one and grab the url for you, or would you prefer the actual fbx file?

**Comment by Frooxius** [comment]
I've got a sample file which has the issue. I'm looking into the issue, it seems that something has changed in Unity itself, which has trouble  processing skinned meshes without any bones. I'll update once I have more.

**Comment by Frooxius** [comment]
Fixed in 2020.9.14.684, thanks for report!
