### ISSUE TITLE
Dynamic Variable Node [Create or Write] should be condensed

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1061]
Issue: There shouldn't be 3 nodes to distinctly do an action that is either a Write or Create,Create, or Write DynamicVariable as it makes it very confusing and unwieldy as it needs to be simplified, it also overbloats what a singular node/concept should do. 

Reason 1: Creating a Variable over another Variable would/should be similar to Writing to it as Overloading. Defeating the Purpose of the [Write] Node and [Create or Write] Node
Reason 2: They are Impulse Impulse Data should be compounded or simplified for the most optimal node flow. 

Create Success, Create Fail. Write Success, Write Fail, OnNotFound ImpulseData could be compounded into a Bool Value that the user can specify. It Determines if you wish to Create or Write. Then Simplifying if the Node is Success, Fail, or NotFound.

**Comment by Frooxius** [comment]
Having them as multiple nodes is deliberate design choice. Each node is technically different separate function and you should think about which one you want to use in advance. They're also form of optimization, creating a dynamic variable is a relatively heavy modification , so it shouldn't be coupled with light writes, because the node would have to constantly keep checking if it should be creating the dynamic variable or not.

Generally I avoid doing "monster" nodes which pack a lot of different functionality, because it gets unwieldy. Nodes are like simple "atomic" method calls and they should not do to much.

**Comment by TehTurk** [comment]
I agree and do consider with it with it being unwieldy, but the problem that occurs this is it makes it generally confusing even in an atomic/state sense to the user. It either writes, or it creates. Why should there be a lossy third option where it does both and you don't care? It just seems like there's an extra state added. If we are needing to be mindful of what node we uses shouldn't their use be stricter?

**Comment by TehTurk** [comment]
Let me re change then the issue then to properly reflect it.

**Comment by TehTurk** [comment]
The Node [Create or Write] should be removed as it's a loose state that isn't that rigid and doesn't take in consideration that the responsibility on what node is used by the user.

**Comment by Frooxius** [comment]
Like I said, this is intentional design and will stay this way. They are both somewhat different operations and two different operations should not be combined, because their behavior will differ.

Create will create the variable only if it doesn't exist and initialize it. If it already exists it does nothing, it doesn't update its value either.

CreateOrWrite will create if it doesn't exist and if it does it will update its value.

Those are two different patterns which have somewhat different use-cases. It's a common pattern in API's like databases and other IO, where you have explicit Create/Insert, Write/Update and CreateOrWrite/Upsert operations. This is where the strictness comes from, you need to choose the right one.

**Comment by TehTurk** [comment]
Hmm okay understood, would those wordings and terms be used then instead? The initial confusion from these nodes was due to the wording and how I had interpreted it due to them. They read so similar and didn't seem distinct enough. On top of DynVariables be more of an advanced thing then an easy thing I think then distinction would be warrented.

**Comment by Frooxius** [comment]
I think it's more problem for documentation instead to describe the differences. The wording is pretty standard and consistent with the actual operations, we'd only make it more convoluted and inconsistent if it was changed. Databases use Insert/Update/Upsert, because they deal with rows (or some other collection of entries).

One small change would be changing "Create" to "CreateNew" and "CreateOrWrite to "WriteOrCreate". For example in C# this is what's used for file IO when already existing file will cause the operation to fail (see here: https://docs.microsoft.com/en-us/dotnet/api/system.io.filemode?view=netcore-3.1). But it has potential to be misleading too, as it might make people think it will somehow create a new version of variable even if one exists, so it goes back to the documentation.

**Comment by TehTurk** [comment]
Hmm I get your point., but Create already had inherently new in it because Creating something is basically making something new. So your only just adding more letters when it's already simply defined in that case. 

Would it be possible to call  CoW something like Update then? Or Initialize? Create and Write are Fine for distinction but it's more so the Third node. Inject would work pretty well here. Because it'll create, or Write the Variable.

**Comment by Frooxius** [comment]
It's not necessarily the case, semantics matter a lot as well. In the file IO example "Create" and "CreateNew" operations behave differently. Create will overwrite existing file, while CreateNew will fail if it already exists. Depending on what you're doing you might want one or the other.

Although the terminology doesn't map 100 % to Neos and dynamic variables, it was just a possibility to make it a bit more distinct. Otherwise we'll just have to leave it as is.

Doing "CoW" wouldn't fit with any rest of the naming scheme, it should be consistent across the board. Same with "Initialize/Inject", they don't really accurately describe what's going on and  they would just introduce new terminology that's inconsistent with all the rest.

**Comment by TehTurk** [comment]
Ah I didn't suggest CoW as a choice. It was short term so I didn't have to write it ^^; But Alright 🤔, but sadly the problem of how the nodes themselves present themselves at the getgo and how 1 to 1 you want them described behavior wise to I/O as well persist as well. 

To those who are new or like looking at for the first time the distinction isn't really obvious at the get go. You yourself said it will "create and Intialize" So this is where I got the idea/suggestion from. Same thing with Update as Writing and Updating are somewhat synonymous behavior wise.
