### ISSUE TITLE
[Linux] When installing on SteamVR there is a path issue with capital letters

### ISSUE THREAD

**Issue by guysoft** [Frooxius/NeosPublic#1078]
Hey,
I installed NeosVR on Ubuntu 20.04 via Steam, but when I started the application I got this error:
![Screenshot_20200924_195939](https://user-images.githubusercontent.com/325670/94203453-1e179e00-fec8-11ea-8458-6d6335be6599.png)

After investigating I saw the following path does exist:
``/home/guy/.local/share/Steam/SteamApps/common/NeosVR/actions.json``

The only difference was the capital letters ``steamapps`` from ``SteamApps``

A workaround was to add a symbolic link:

```
ln -s ~/.local/share/Steam/SteamApps ~/.local/share/Steam/steamapps
```

Other stuff on Steam seem so work, so I don't think its a steam issue.

**Comment by InsaneGrox** [comment]
Gonna add to this that this did not occur for me, using a different distro and VR headset however, @guysoft using a vive with ubuntu 20.04, me using an index with linux mint 20 codename Ulyana, cinnamon desktop.

**Comment by Frooxius** [comment]
The issue is definitely due to the "SteamApps" being capitalized, Steam expects it to be lowercase and Linux paths are case sensitive. It's a bit strange that it's capitalized though, since both on Windows and Linux it normally creates it as lowercase "steamapps".

There's unfortunately not anything we can do on our end though, since this is handled by SteamVR and not Neos. The workaround should work, maybe just renaming to "steamapps" would do the trick. If it makes the folder capitalized consistently on your system I'd suggest reporting the bug directly here: https://steamcommunity.com/app/250820/discussions/3/

**Comment by guysoft** [comment]
My workaround is to add a symlink, that way you have both.
