### ISSUE TITLE
Toon outlines is causing a major performance hit

### ISSUE THREAD

**Issue by Reactantvr** [Frooxius/NeosPublic#1088]
I run a similar benchmark to Frooxius where I go to an empty world and spawn dozens of my avatar until I get a certain FPS number. I do this when it transitions from 45 to 30.

With toon outlines enabled, I am able to spawn only 40 of my avatar while maintaining 45 FPS. With it disabled, I can spawn 65 of my avatar. 

I tested this with several other avatars of much lower poly count and found the impact to appear to be the same no matter the avatar. I tried the avali v1 in the neos essentials folder for example. It had the same impact when I added toon outlines to the two materials it had in the body. I confirmed the same results with the avali on the far right with the gun (I deleted that prior to duplicating).

The best way to test this is to use the neos bot in neos essentials. It has a higher poly count and will give you a very obvious performance impact. Steps are to convert all materials in the baked section to toon shader. Save that avatar once done convert a copy all to toon outlines. Just change each to lit and do nothing else. Now, in an empty world, spawn as many of toon (no outlines) and watch your FPS. Then, delete those and do the same with toon outlines. You should notice a major difference in performance. While doing this to test performance, stand at least 10 meters away from the avatar. 

With the above steps, I was able to spawn only 21 of the avatar before hitting 30 fps with outlines and was able to spawn 36 without outlines.

**Comment by Frooxius** [comment]
This is unfortunately just the nature of the outline rendering with toon shaders. In order to render the outlines, it actually needs to render your avatar twice - first for the outline with slight extrusion and then another time for the actual color visual. It also does this using extra stage, using a geometry shader, which has a bit of extra overhead on itself.

As a result, the GPU usage for avatars with outline (particularly the lit one) is effectively doubled, because the geometry is dynamically doubled when rendered, so the numbers you see aren't too unusual. It's not something that can really be fixed, achieving the outline effect requires more GPU resources than doing it without them.
