### ISSUE TITLE
Normalize Default Range/Repeat Values on multiple Components to 1 instead of max float

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#1095]
Several components that deal with panning and movement have maximum ranges defaulted to max float value, this has led to problems with floating point imprecision when Panners on textures are left to run for a while (Caused by a default max float Repeat value), and also many ranges for most things being much higher than necessary.

This setup has caused confusion from people such as @Enverex who don't recognize the floating point max and realize that it should be changed. Changing that value to a normalized value would also help a Panner applied to a slot to not send it shooting off to huge ranges immediately upon speed change.

I have not collected a full list of common components affected by this yet, but I can work on it soon. Certain ones I've seen so far:

-Panners (Repeat values)
-GrabbableReceiverSurface (Range value)

**Comment by Enverex** [comment]
To clarify, I did recognise that it was max float, but I (as I assume most people) left it alone because I didn't know why it was set as such. Here is the effect of having a panner on for a long period of time (floating point being shifted from hundreds to thousands to millions respectively):

![image](https://user-images.githubusercontent.com/958670/94491091-73f98800-01df-11eb-9071-a12b7dffd219.png)

![image](https://user-images.githubusercontent.com/958670/94491101-78be3c00-01df-11eb-81bb-4f953aae6803.png)

![image](https://user-images.githubusercontent.com/958670/94491108-7c51c300-01df-11eb-9fe4-72ef223f14f2.png)

**Comment by Frooxius** [comment]
This makes sense for Panners and I can switch the default to be 1 so it wraps around quickly, but not for GrabbableReceiverSurface. For those the range is infinite, so it's effectively only limited by the size of the object being dropped. Setting it to some arbitrary value could lead to more confusion.

**Comment by H3BO3** [comment]
I've noticed that grabbablereceiversurfaces don't yoink objects from near-infinite distances when default values are set. What does the range value actually do?

**Comment by Frooxius** [comment]
Range lets you put a constraint on how far away the objects can be to be snapped. By default it's based only on the size of the object and whether it's in the range of the collider with the receiver surface.

**Comment by H3BO3** [comment]
How does the size of the object play into it? The other day I was trying to snap a little cube onto a big cube, and it wouldn't snap until it got quite close, even with default max float ranges.

**Comment by Frooxius** [comment]
I've set the default Repeat range for Panners to 1 in 2020.9.29.1115. Do you have any other components or should this be closed?

**Comment by H3BO3** [comment]
I will keep an eye out and reopen if necessary.
