### ISSUE TITLE
Enable Anchor nodes to work with Multi-User Avatar Anchors

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#1106]
The Anchor nodes in Avatars-> Anchors don't function with a multi-user avatar anchor. It would be nice if they did.

**Comment by Frooxius** [comment]
This is unfortunately not possible, because Multi-User Avatar Anchor are different from actual Avatar Anchors, they serve as a proxy them and provide extra behaviors on top. The behavior for each can differ and can require the user to manually point at some point in collider, where an anchor will be created. 

I can add new nodes to work with some of them. The main question is how to best generalize this. Can you provide some use-case examples please?

**Comment by ProbablePrime** [comment]
I was incredibly tired when I made this so my use case turned out to be sorta weird(I'll make a new issue for the problem i fixed here if its valid later and can be voiced productively) so i'll adapt my thinking to be more generic while still applying to the subject matter.

I experimented with the Multi-Anchors today and found them to be useful in cases of mass transit or movement. The current approach to using them is to click on the "master" anchor which creates a new one for each user. That's good for rides, vehicles, elevators and other movement based mechanics. However it can lead to uncontrollable positioning and as such I'd probably rather use individual anchors which i'd manually find and anchor users to using logix. 

Therefore I don't really have viable use cases for this. It seems rather Niche to be used for sorta generic cases where circles, squares or point generators will position users in a way that makes sense.

Due to all of this I'll close this for now to lighten the cognitive debt here. 

Thank you!
