### ISSUE TITLE
Pushable Component

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#111]
This is a request for a component that allows you to push objects around. This would work like Grabbable, in that when you add the component to an object through the inspector, users can grab them. 

Once this component is added to an object, I'd expect the action of the user controller (but not the ray caster) colliding with the collider to push the object in the direction the controller is moving. 

This should also be compatible with Grabbable, in that if both components are added to an object, you can either push it with your controller, or grab it while pushing.

**Comment by Frooxius** [comment]
Hmm, I'll have to think about how would this one work. Pushing with any part of the controller would require constant physics checks (likely convex sweeps using  a box or compound collider around the controller), which might get pretty expensive.

It might be better to wait for the physics system dynamics, since it would be easy to achieve with that, rather than trying to reimplement the specific functionality manually.

**Comment by sirkitree** [comment]
👍 I had a feeling this was going to be easier once physics was implemented. :)

**Comment by shiftyscales** [comment]
This would be best achieved by #22.
