### ISSUE TITLE
"Only Headless Hosts" filter unchecked for "Headless Sessions" search preset

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1138]
The filter currently does not operate as intended as it does not only display headless hosts/sessions.

**Comment by Frooxius** [comment]
This was done intentionally, the problem is with the naming, since there was meant to be a mode which shows empty headless session in addition to active ones. When it was showing only headless, it would not show a lot of active sessions. I can change it, but I think it might be more confusing to people.

**Comment by shiftyscales** [comment]
Yeah, I remember it was added for #1012. The primary condition that needed to be met with that was an easy way to find headless sessions, including empty ones since they are filtered from the other categories.

I think non-headless hosts that have an active session are best left to the 'active sessions' category.

As is now, the Headless Sessions preset is effectively Active Sessions + Empty Headless Sessions, which I don't think is as valuable/useful as just displaying all/only headless sessions as the name would imply.

**Comment by Frooxius** [comment]
I've made the change in 2020.10.12.499, but not that this partially reintroduces the problem from #1012. If someone hosts the session on LAN on another PC and it's empty, it won't show up. Only headless ones will ever do.
