### ISSUE TITLE
Request for more prominent details on Moderator, Neos Team powers and responsibilities + moderation process

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#1172]
First off, congratulations to everyone who has been added to the Neos team and Moderator status, you’re all critical parts of our amazing community!

**This topic has been discussed in Discord before, but I wanted to make a note here so it can be tracked. I believe it is important for all NeosVR users to have clearer information on the following points:
A)	Moderator powers (if they have extra ones beyond standard users) and responsibilities
B)	As A) for Neos team members (assuming these are different)
C)	The moderation decision making process
D)	Possibility (or not) for appeals or complaints regarding moderation decisions**

Regarding **A)**, we have recently had a number of people nominated as VR / Discord Moderators, however there is not (to my knowledge) any public information on how they can be expected to perform moderation duties beyond using the tools already available to standard users (kick/ban etc.). More transparency is important here; users cannot properly assess whether they should alert a Moderator to a perceived problem if they do not know what abilities said Moderators have for dealing with issues.

Similarly for **B)**, clearly at least some Neos team members have access to data and functions that standard users do not (e.g user registration information for linking email addresses to accounts etc.). It is important that the community understand what information team members can access so that requests for help can be directed to the right people. Furthermore, I suspect there will be a requirement for some team members to have access to inventory records for the purposes of item ID dispute resolution once those systems are implemented. Given that account registration data and inventory items may be generally considered private by users, I think it would be good in principle that we know who is allowed access to that data and for what reasons. 

I understand we recently had a case where a global ban was applied to a user account. This is a major penalty to apply and, from what I have gathered (I recognise this is probably not the full story), the sanctioned user was given no official warning or notification of the application of the ban. I am in no way suggesting that this moderation action was misapplied. However, I believe it would make for a healthier community (and would help reduce potential for drama) if users had a better understanding of how incidents are assessed and dealt with.

On point **D)**, moderation actions can often be surrounded by some disagreement / divergent perspectives. I suggest that it would be beneficial for there to be some form of appeal / mediation process in disputed cases. Community members with elevated status / powers can often attract criticism or complaints from users who may disagree with the interpretation of rules or sanctions. It can protect good-faith actors on both sides if a clear process is laid out for a complaint to be made, should a user feel it appropriate. It helps end users know where they stand and gives those in elevated positions security that they will be dealt with fairly should a complaint be made against them.

I’d like to emphasise that I have only ever had positive interactions with the current Neos team and Moderators. This request should not be interpreted as an complaint about, or hard feelings towards, anyone. However, when there is a lack of transparency around moderation in online communities, it is common for bad feeling to accumulate over time along with accusations of moderator ‘conspiracies’ etc. I would very much like to avoid that for Neos! I suggest the wiki AND/OR a the neos.com site would be appropriate places for some of the requested information. An announcement in one of the weekly updates would be welcome as well. 

I realise this is quite a broad request - if it would be better to reduce into smaller chunks that's fine. I welcome any and all feedback on this.

**Comment by Frooxius** [comment]
Thanks for the post! It's definitely important to address these things, since we're just starting to deal with things that need moderation in first place and there were only handful of cases where it was necessary.

There's a lot of things and I think some of them will be better answered by Veer, but here's quick info on a few points:

A) Generally you should alert Neos moderators if you can't deal with a problem using provided self-moderation tools or if the issue is affecting the community in broader sense (e.g. users who are targeting all public worlds with harassment)

B) I recommend reading #faq channel on the Discord, it has information on who to contact for certain things and issues.

Currently only I do have raw access to the database and raw inventory records as result. Because of the highly sensitive nature, I setup the system so even Neos team members who have access to the codebase won't be able to access what a normal user couldn't and I plan to keep things that way, instead providing other members and moderators with tools that provide only bare information needed.

One tool that's currently accessible to Neos team and moderators for disputes is finding which users own particular asset. To do this they need to be given the ID of the given asset in the first place (they can't just enumerate things in the inventory) and it only reveals owners, but not the actual associated items. This is to help solve disputes with things like stolen textures or meshes.

Some Neos team members can access basic account information for things like linking up Patreon emails, changing usernames and adding badges.

C) I know that the user was warned and notified in DM's before, since this wasn't his first offense. Veer could provide more details, but we've been dealing with this user for a few weeks already. Since he kept escalating his actions while playing dumb, we had to put a stop to it.

We plan to automate this system in the future as it matures some more, so the user is notified automatically and other users can be warned as well (e.g. people who abuse permissions can be forced to Spectator by default in public worlds, but the host of the world will always be able to override this action, but be also warned that the user has misused it before).

D) In general we want to use moderation as little as possible and instead encourage moderators to defuse/mediate situations first and talk to the user, then warn and only then take action. The moderation tools are also setup so the action taken is as minimal as possible for given offense. We don't want to cut out people from their work/socialization platform even over some more serious things.

For example the most serious bans applied to users still allow use of Neos, but disallow joining of (semi)public worlds and any sessions won't appear. Users can be still individually invited to the sessions. So far we've only used full account ban on bots that registered accounts to post spam on the Wiki.

In terms of the escalation/disputes, generally it would go Moderators -> Veer -> Me (Frooxius). Again Veer could give more info on this later.

Anyway I hope this helps shed some more light on things!

**Comment by ProbablePrime** [comment]
I was speaking with Veer about this last week, I requested that information such as this be publicly documented. I suggested a Wiki page of some kind with some of the above answers on them and offered to create it.

With the information above that's now possible, Is it ok for me to proceed?

**Comment by Frooxius** [comment]
@ProbablePrime Yes you can proceed, thank you! Let me know if you have any questions or need for clarifications.

**Comment by Zyzyl** [comment]
Thanks for the detailed response Froox! It's great to hear you're actively thinking about these matters and already have plans to e.g. safeguard inventory privacy while still enabling dispute resolution.

I look forward to hearing more from Veer. Particularly regarding Moderators - I understand that they should be seen as a backstop should users feel unable to deal with a challenging situation. What I (and I believe others in the community more generally) am still unclear on is exactly what users can expect Moderators to be able to do about challenging situations / individuals.

I'd be grateful for you creating that Wiki page Prime!

**Comment by ProbablePrime** [comment]
https://wiki.neos.com/Moderation and https://wiki.neos.com/Guidelines have been created.

Due to the nature of wiki's these can be edited and updated at any time. I predict these ones in particular will change a lot as Neos grows but they are a start and were very much needed.

**Comment by TehTurk** [comment]
Would you be alright with closing this @Zyzyl since the initial questions were answered?

**Comment by Zyzyl** [comment]
Thanks for following up @TehTurk. I would prefer to leave this open for now as I'd appreciate further claraification on a few of the points I brought up - perhaps from Veer. Specifically:

1) If I feel that I have exhaused the options available to me and I ask a Moderator to intervene in an active session, what can Moderators do, there and then, which goes above and beyond what I could have achieved as a standard user?

2) Related to 1), it is my assumption that heavier penalties (e.g. ban on joining (semi)public world) are not able to be imposed immediately at the sole discretion of an individual Moderator, but that Veer would need to be involved as well. Is that correct? If that is correct, where is the dividing line between what Moderators / non-Veer Neos team members can do individually and what they cannot?

3) Regarding my original question about the possibility of appealing/complaining about moderation actions. Are we to understand that we should direct any appeals first to the Moderators involved / another Moderator? Then, if unsatisfied with the resolution, one could escalate to Veer / Frooxius? My primary concern here is with ensuring that users be dealt with fairly and that the moderation team be perceived to be acting fairly as well. I'm sure it will be understandable that some users may feel there is a potential for bias / conflict of interest to creep in here - Neos is a small community and most of the moderation team are friends. Unfortunately I don't have any suggestions for how best to handle this, but it would be good to hear that the team has given some consideration to this point.

4) Thanks to ProbablePrime for starting the wiki page. I would ask that a reference be made to it in some highly visible place (for example in one of the weekly annoucements) so that more people become aware of it. That may also help trigger some useful feedback / comments for improving the page. 

5) This was not mentioned in my original post, however I note from the list of Moderators on the wiki that the majority live in American time zones (judging from spoken accents and what I know personally from a few). Obviously that reflects where the majority of our userbase seem to live and I think we have sufficient Moderators for now. However, if the team were to be expanded again in the future, I suggest adding a few more users from European, Australian or Asian time zones (perhaps with facility in multiple languages as well as we expand the localisation efforts) to ensure a more even global coverage.

**Comment by Zyzyl** [comment]
Thanks for clearing those points up for us @Veeridian! The transparency from the team is always welcome. I'm happy to close this issue now.

I have added the information from your comments to the wiki page started by Prime here: https://wiki.neos.com/Moderation
It would be great if you could check over it to ensure everything is accurate, I think we may be missing the names of one or two of the moderators as well.
