### ISSUE TITLE
OnGrabbableReceiverSurfaceReceived node should accept IGrabbableReceiver

### ISSUE THREAD

**Issue by Coffee-Maker** [Frooxius/NeosPublic#1177]
This should be a fairly simple change, the node would ideally work with any IGrabbableReciever. The node may need to be renamed to "GrabbableReceiverReceived".

**Comment by Frooxius** [comment]
This is definitely not a simple change, as it's not currently possible from technical standpoint. IGrabbableReceiver interface only allows objects to receive notification of grabbed objects, but it doesn't require them to report any kind of event, since they can do absolutely anything with this information.

This means that there's not an event to listen to and report through node in the first place, so this change cannot be made without placing additional requirements on anything that implements this interface, both now and in the future.

**Comment by ukilop** [comment]
Then how feasible is a _new_ node instead of lumping it in with existing?

**Comment by Frooxius** [comment]
It's not feasible. The problem isn't the node itself, it's the IGrabbableReceiver interface. Components that implement it don't necessarily fire any events when they handle the objects, so no node can exist to listen on an event that doesn't exist.

**Comment by Coffee-Maker** [comment]
As it stands we can use the SlotChildrenEvents node to receive events from the grabbableParenter and use the dedicated node for GrabbableReceiverSurface.
