### ISSUE TITLE
Session halt/freeze on User join for 2-3 seconds

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1184]
- Host session with 10 + people the number can varies
- New User Joins
- Lag of 2-3 Seconds
- While minimal it's a bit of a jarring thing to have when about 10+ users join the session at the same time
- It also ruins social moods or takes focus off what people are doing at the time breaking workflow/atmosphere.

**Comment by Frooxius** [comment]
There's already planned optimization to address this: https://github.com/Frooxius/NeosPublic/issues/223

It would help if you could provide any technical details though, since it seems a lot more severe on your end than what I've experienced otherwise:

- Are you hosting on client or using headless?
- What hardware are you hosting on?
- Does the lag affect only host or other users as well (e.g. other users see everyone else lag)?

I'd recommend continuing the discussion in the existing linked above, closing this one as duplicate.
