### ISSUE TITLE
Direct Connections are not working 

### ISSUE THREAD

**Issue by RoxyBoxxy** [Frooxius/NeosPublic#1193]
I keep getting relayed thought the usa server so when in a us lobby i get 28ms ping from the uk and i end up with huge desync issues, some other people might have the same issue

**Comment by Frooxius** [comment]
I'm sorry, but if Neos can't establish a direct connection, there's not much that I can do to help the situation from my end, because this is usually because of your ISP and/or network configuration.

Neos will try performing NAT punchthrough 5 times to establish direct connection. If none of them succeeds it will fall back and connect through the relay.

Typically having strict NAT anywhere on the path will prevent the NAT punchthrough from going through. If you can configure your router to use Open NAT instead that might solve the problem. However typically this is due to the NAT owned by the ISP, which users don't have control over.

If you have a public IP, you could try forwarding all ports by default to your machine so Neos can go through. Alternatively you could also try switching to Steam Networking Sockets, which uses Valve's relay network.

Eventually we'll have more relay servers around the world which should help the situation, right now there's only one in Central US. I could see about adding one in Europe sometime soon, but I can't make a promise when since there's an associated monthly cost with it.

**Comment by Enverex** [comment]
What is the requirement for this to work properly? Does Neos try and use uPNP at all? Me and Roxy have been trying to narrow down why this happens on their end.

My router is configured with a different machine in the DMZ (not the one I use for Neos) and uPNP is disabled which seems like a worst case scenario, but it works fine for me.

Roxy on the other hand has a standard setup with uPNP enabled (which implies it's not a strict NAT and also works for other games) but Neos has to use a relay in their case. Adding static port forwarding fixes the issue, which would mean it's not likely to be an ISP issue (else I'd expect that not to work either).

So what other possible reasons does that leave for Neos having to use a relay?

**Comment by Frooxius** [comment]
Like I mentioned, you need open NAT for this to work well. Specifics however matter a lot on the specific hardware along the whole connection path between the two hosts, sometimes it doesn't quite work without a clear reason why, networks are prone to a lot of weird edge cases.

uPNP isn't used, generally it's not too reliable for games so it's not even supported by the protocols used by games in favor of NAT punchthrough since it's a lot more robust and reliable. I could look into potentially adding support, but it might be tricky with the current protocols. 

How exactly does uPNP enabled imply that it's not a strict NAT? They're unrelated things. Most games also use relays when this fails, so just because they work doesn't mean that UDP punchthrough works for them either, they could be going through a relay as well, it's pretty standard practice.

However there are no other possible reasons for Neos having to use relay. It will try to do NAT Punchthrough 5 times and if all of them fail it'll fallback to the Relay. There's no other logic there.

**Comment by RoxyBoxxy** [comment]
Fixed: I am dumb and forgot to enable static port on my nat mapping in pfsense
