### ISSUE TITLE
Per-session locomotion memory

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1247]
A common scenario when navigating between sessions is that the locomotion used in one session is kept while returning to another, leading to some undesired outcomes.

As an example:
- A user is in noclip/floating before navigating to a new session
- In the new session they use a physical locomotion
- When returning to their previous session, they drop out of the sky

If the previously used locomotion could be returned to on focusing other active sessions, it would prevent this from occurring.

Suggested recently by Kodufan# 7558 and others previously.

**Comment by Frooxius** [comment]
This is a bit problematic. The locomotion remembers the last setting globally, because when it didn't do it, we got lots of complaints from users, that Neos keeps forgetting their selected locomotion type. There are some downsides to both cases, but I feel like the current system is one with less impact.

If you drop out of the sky, you can just switch back to Noclip and fly back, but having the locomotion switch for new users can be particularly jarring.

One approach would be to only use the last global locomotion when the world is first started, but afterwards remember it. That might provide it a good compromise for this situation, since new users won't switch their locomotion too often.

**Comment by shiftyscales** [comment]
I think that would work well too. Similar problems can already happen that way depending on how the locomotions/permissions are setup for a given world.

E.g. a user enters a new session in teleport/prefers to use teleportation, but the world doesn't have teleport installed/enabled forcing them into walk/run instead when they join.

Although specific cases like that could be taken care of by #461.

Starting in their current/preferred locomotion, and remembering their locomotion from previous sessions seems like it would be a good compromise that would fit the needs of this issue. Thanks for the consideration, @Frooxius!

**Comment by Frooxius** [comment]
Made the change in 2020.11.1.1319!
