### ISSUE TITLE
Add Reflection and Light Probes

### ISSUE THREAD

**Issue by Toxic-Cookie** [Frooxius/NeosPublic#1250]
### Context ###
After I searched the issues list for "Reflection Probes" and "Light Probes", no issues showed up so I have decided to open this one. 

It is well known that Neos uses Unity for rendering purposes, as such, reflection probes and light probes should be natively supported and simply require being exposed to components and or LogiX to use. 

Although baking functionality would be great, it is not immediately needed and can be omitted for the time being if need be and added later on.

To substitute baking for now, an external bake can be made and imported into Neos for use. Eg. 360 image for reflection probe.

### Reflection Probes ###
A Reflection Probe is rather like a camera that captures a spherical view of its surroundings in all directions. The captured image is then stored as a Cubemap that can be used by objects with reflective materials. 

Several reflection probes can be used in a given scene and objects can be set to use the cubemap produced by the nearest probe. 

The result is that the reflections on the object can change convincingly according to its environment.

### Light Probes ###
Light Probes provide a way to capture and use information about light that is passing through the empty space in your scene. Similar to lightmaps, light probes store “baked” information about lighting in your scene. 

The difference is that while lightmaps store lighting information about light hitting the surfaces in your scene, light probes store information about light passing through empty space in your scene.

Light Probes are positions in the scene where the light is measured (probed) during the bake. At runtime, the indirect light that hits dynamic GameObjects is approximated using the values from the nearest Light Probes to that object.

**Comment by Frooxius** [comment]
Reflection probes are planned feature that will be added. I'm not 100 % sure about whether we could support Light-probes. Those two should be separate issues, I strongly discourage bundling two different (even if somewhat related) features into a single issue. I was considering adding Reflection Probe support soon (including baking), but if you wanted both at once you might potentially need to wait a really long time.

Neos uses Unity for rendering yes, but your assumption that it can be simply exposed it incorrect. Adding both of these is actually quite complicated and labor intensive, as Neos needs to have full control over the assets (since we have our own texture asset upload to GPU implemented for DirectX 11 and OpenGL) and data in its own data model and a lot of the functionality built into Unity for authoring those is only usable inside Unity Editor, meaning that we need to re-implement our own solutions so it works at runtime.

**Comment by InsaneGrox** [comment]
> Reflection probes are planned feature that will be added. I'm not 100 % sure about whether we could support Light-probes. Those two should be separate issues, I strongly discourage bundling two different (even if somewhat related) features into a single issue. I was considering adding Reflection Probe support soon (including baking), but if you wanted both at once you might potentially need to wait a really long time.
> 
> Neos uses Unity for rendering yes, but your assumption that it can be simply exposed it incorrect. Adding both of these is actually quite complicated and labor intensive, as Neos needs to have full control over the assets (since we have our own texture asset upload to GPU implemented for DirectX 11 and OpenGL) and data in its own data model and a lot of the functionality built into Unity for authoring those is only usable inside Unity Editor, meaning that we need to re-implement our own solutions so it works at runtime.

I've got a possible temporary solution for the reflection probes that can be used potentially before polishing and making them function as they do in unity, simply have a component in an "experimental" category of rendering for now named ReflectionProbe, and have it have a single 360 material input, for now it can act as a global reflection probe that neos switches to the nearest one locally for now (or even only one in the world at a time), simular to how the skybox is currently used as a global reflection probe, and can be auto-converted to proper ones at a later date (the reasoning for the experiemental category is due to the fact these would behave differently from how they'd behave when finalized), this might be a waste of time if all of that godot engine talk is still under consideration however.

**Comment by Frooxius** [comment]
@InsaneGrox That would actually take a lot more time to develop than just doing it properly. ReflectionProbes don't work as materials, they use raw cubemaps, which are then dynamically passed to the actual materials when rendering (or done indirectly through Defferred). Doing it the way you propose would require significant alterations to the rendering pipeline.

As a rule I generally don't do experimental features like that. I already know how it has to be implemented properly, so it's easier and better to do just that, rather than spending a lot of time on some hacky solution only for it to be thrown away later.

**Comment by Frooxius** [comment]
Reflection probes were finally added in 2020.11.22.1118! With full support for baking in-game, wizard to mass-bake them and more.
