### ISSUE TITLE
[Tweak/QoL] Auto-save persistance throughout NEOS restarts

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Frooxius/NeosPublic#1253]
I feel like auto-save should be persistant through NEOS restarts such that if you close NEOS and reopen the same world with auto-save enabled, it'd be automatically enabled again.

**Comment by shiftyscales** [comment]
I feel there might be more potential for harm in having a world auto-save without explicitly turning it on than there would be progress lost by forgetting to turn it on. If you open a world you've made and begin using it in any way other than building in it, potentially undesired changes are committed to the world.

In contrast, to turn auto-saving on it requires applying the checkbox (the value of the auto-save interval is saved into the world) at the start of the session. If by chance you happen to forget- Neos already throws up a confirmation prompt if you wish to save your world before closing it.

**Comment by Frooxius** [comment]
Yes, this is non-persistent for this reason. Otherwise it's very simple to just open the world to hang out and not realize the Auto-Save is on, resulting in the world to get permanently trashed. 

It's even worse if other people try to open or have a copy of the world, as this would keep saving the world over and over simply by not realizing that auto-save is on.

Without some complex behavior to counter this I think this would do a lot more harm than good. Perhaps there would be some heuristics to determine when it should be persistent and when not, but that might also make the system a lot less predictable, as it would be difficult to tell if the autosave will be on from previous session or not.

The simplest solution is to simply turn it on when you know you're going to be working on the world.

**Comment by 3x1t-5tyl3** [comment]
Yeah I can see why it was setup that way. Haven't given much though into those issues.

I'll be closing this issue. Thanks for the info!
