### ISSUE TITLE
[Request] SetTransform(Pos, Rot, Scale) Node

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1272]
- Benefits as a Reset for some setups
- Can work a bit more natively with transform types
- Many of us have wanted this/requested this

**Comment by Electronus** [comment]
seconding this, even better it it can take a float 4x4 matrix.

**Comment by Frooxius** [comment]
What exactly does "Can work a bit more natively with transform types" mean? You already have nodes to set individually the position, rotation and scale, so this would work the same, but would set them all in one go, but functionally it wouldn't be too different from using those individually.

**Comment by H3BO3** [comment]
I'm not sure how it could take a matrix -and- all three types. There might have to be a distinction between nodes that could accept a matrix and ones that took a float3, floatq, float3. Not to mention the Local/Global distinction.

@Frooxius I think this is intended to work as a fast way to set all three in one go rather than having to chain them. I suggest two new nodes (Set Local Transform and Set Global Transform) that would have inputs for all three TRS values at once. If the values are unfilled, they default to identity transform for fast resets.

**Comment by TehTurk** [comment]
Mainly to prevent the chaining as a simple reset but also give the current Matrix Types some more purpose/usage.

**Comment by Frooxius** [comment]
Matrix can be supported, but it will just be a shortcut, as it will internally decompose the matrix into Position, Rotation and Scale and assign those. Using Matrix isn't going to be more native than that.

But if that's fine with you to avoid chaining then it should be all good when they get added, I just wanted to make sure you're not expecting it to do something different.

**Comment by H3BO3** [comment]
How will you be able to accept a single matrix type but also still accept individual TRS types? I'm just trying to clarify... Unless you plan to make four nodes total, I understand that.

**Comment by TehTurk** [comment]
I think that'd be fine, I genuinely don't know how else it could be used o.O. I thought the Matrix Types were originally just TRS anyway 🤔 and was broken down into Float3/FloatQ for usage.

**Comment by H3BO3** [comment]
@TehTurk Nearly all setups use the regular transform component types instead of compositing a matrix first, though. I imagine the matrix-accepting node would only have specialized uses.

**Comment by Frooxius** [comment]
There will be two nodes, one that accepts matrix, one that accepts them individually. 

I don't really know what "Matrix Types were originally just TRS" means? TRS is just specific type of matrix, but there's lots of different ones used internally. But the data model handles the transform as individual components, with transformation matrices constructed just internally.

**Comment by H3BO3** [comment]
@Frooxius What will be the distinction between Local and Global set?

**Comment by Frooxius** [comment]
Same as the other nodes.

**Comment by TehTurk** [comment]
Ah okay! I thought originally the Transform Matrix was the base type, and the singular ones were derived/handled from that .

**Comment by Electronus** [comment]
Use case wise, KierDran is using a TRS matrix to store bone information and being able to take it and use it directly may help.

**Comment by ChrisWarner103** [comment]
Cheers for making this @TehTurk I would have done it myself. But I didn't exactly know how. My original idea which I put in the discord was just to have like a ResetTransform node where the user can tell the node which to reset. The design I was thinking was like a node that has 5 inputs maybe. The pulse, 3 Booleans that check to see what is being told. It’s just in the inspector you’ve got the reset buttons but you can’t actually access them through logix of any form. Could also be like a node that just takes in a slot and a pluse and it'll just reset all the transforms.

**Comment by H3BO3** [comment]
@ChrisWarner103 That kind of node would be very redundant, when you can just have a node as proposed that accepts the transform, if inputs are unfilled it behaves like a reset (As proposed in your last sentence, this would behave exactly like that). Not to mention boolean-based behavior like that wouldn't work with Neos' datamodel.

**Comment by ChrisWarner103** [comment]
@H3BO3 Okay, just wanted to mention it because I originally posted about having a node like this. But personally, I don't think it would be redundant at all. Like if users just wanted a node that says like this resets the transforms and that's it. I get yes, my original pitch with the bools was a bad idea. But still being able to just have a reset node would be ideal and not redundant

**Comment by H3BO3** [comment]
Yeah, this is that node. It (re)sets the transform if there are no inputs. So it would be a bit redundant, imo. @ChrisWarner103

**Comment by ChrisWarner103** [comment]
Not to mention as well that if a new user is trying to learn logix and they didn't know that by not plugging anything in essentially resets. They'll be trying to look for a node that resets instead. I get it you have your opinion on the matter of it being redundant, but I would rather use a ResetTransform node then have a SetTransformLocal or Global @H3BO3

**Comment by Frooxius** [comment]
Added the nodes in 2020.11.5.88:

- Added nodes to set Slot's transform in one operation (requested by @Turk, @H3BO3,@Electronus and @KierDran):
-- SetLocalPositionRotation
-- SetLocalTransform
-- SetTRS (mildly dangerous, make sure your TRS is valid, otherwise use the ones above)
-- SetGlobalPositionRotation
-- SetGlobalTransform (I strongly recommend using the one above instead, setting global scale can lead to lots of problems, you were warned)
-- SetGlobalTransformMatrix (This one is even easier to shoot yourself into foot with. Use only if you absolutely know what you're doing)
