### ISSUE TITLE
Add impulse for animation completion on Set User Scale

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1280]
An impulse on completion of the animation for the Set User Scale node could be very useful for chaining/timing events following the use of the node.

Thanks again for adding the node, @Frooxius!

**Comment by TehTurk** [comment]
Also chatted to @shiftyscales about this but currently this also has the issue of where you can have the operations layer over one another.
Love the new node Froox :D 
Examples
- User makes a SetUserScale Operation last 9999 seconds
- User makes a SetUserScale Operation Last 1 Second
- Due to this, any other SetUserScale Operations are overridden unless it's just as long, then the operation compounds

**Comment by Frooxius** [comment]
I can just have it cancel any existing scale operation whenever you trigger another one. That way they won't conflict with each other.

**Comment by shiftyscales** [comment]
I assume if you implement that behavior it would cancel the existing operation only for the user that is currently already being scaled by it?

E.g. if you wish to scale multiple users separately, that would still be possible with that tweak made, right?

**Comment by Frooxius** [comment]
Added in 2020.11.6.439! The canceling only cancels any scaling animation on the user you're running it on, other users are unaffected.
