### ISSUE TITLE
Undeleting user duplicates user

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1281]
Discovered by Conduit (MIKE# 4278), a user can delete themselves, then un-delete using the undo manager to produce a duplicate user/avatar that uses the same streams.

**Comment by TehTurk** [comment]
Hey this was a bug previously before, but I think got previously reported by Zyzyl prior (can't find the issue), but nice to see it still exists in some form!
I was wondering can we get this function natively in some way? While yes currently a bug I'd love to see this as a proper behavior because
- Duplicating/Fake Users has been a thing for testing, Stress Tests, User Interactions etc.
- It shows off the wonderful bewilderment/strength that is Neos.

**Comment by Frooxius** [comment]
Does this have any negative effects other than just being weird? It's not necessarily something that needs to be fixed, as you can just delete the other self again afterwards using Redo.

**Comment by shiftyscales** [comment]
Yeah, it doesn't have to be fixed. It's technically correct behavior which is why I didn't tag this issue as a bug.

Just wished to make a record of it/log it. There's nothing immediately harmful that I've seen as a result of this behavior at this time.

**Comment by Frooxius** [comment]
Hmm I'm just going to leave this behavior in then if it's not harmful, as it can be just a funny thing to do, thanks! Please reopen if there are some serious issues with this found.
