### ISSUE TITLE
New player start - Please add noise gate and player height

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1331]
The new player start menu is a massive improvement! But as I see it there are two more things that are important, and for these two users don't know they need to configure them.

The noise gate can prevent players from being told about it in a repramandy way, and its also a selling point for neos (people like that feature and it's not common as far as I can tell).

Player height is arcane enough in what it does that even experienced users don't reliably know what it does (I personally have some guesses, but I'm sure it does even more than that). The current setting experience is also quite rough due to the radio button layouts, and the format is confusing often for imperial users. The user being guided to configure this right at the start would prevent this from being an issue!

So, please consider these two! This would also let me remove two pages from tutorial world, which is great from my perspective!

**Comment by Frooxius** [comment]
We already have a topic for this here: https://github.com/Frooxius/NeosPublic/issues/683

Adding player height is planned, but I don't plan on adding a noise gate to the welcome guide because it's non-essential and would add more noise, particularly to new users.

The main goal is to make sure that the user can communicate with others and doesn't get frustrated and lost. Noise gate doesn't help prevent that, it's just a minor annoyance to other users, but usually people will tell them how to adjust it if it's particularly issue on their headset afterwards.
