### ISSUE TITLE
Sound source scaling

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1350]
Discussed with @Frooxius in-world before, an extension to how volume and falloff calculation is handled in Neos to account for an object/slot's scale.

This is useful in quite a few ways, e.g. having a user's voice volume range and sound effects they produce respect their current scale (hearing a large user without requiring them to go into 'shout', or allowing smaller scaled users to stand around nearly the same point without sounding like they are in broadcast).

As Frooxius had noted, this would need to be implemented in a way that preserves settings for existing experiences.

**Comment by H3BO3** [comment]
I think if this was done for user voice audio it should be clamped to a certain min scale so people getting incredibly tiny don't just disappear and leave no trace.

I definitely agree with maintaining existing things, perhaps a bool on the audiosource that takes the global slot scale into account, defaults to false - Many poorly-managed sound hierarchies would break otherwise.

**Comment by Frooxius** [comment]
Added scaling in 2020.11.23.1311! By default the audio sources still use global distances, but you can now switch their space to Local. There's also MinScale and MaxScale which let you clamp how much scaling occurs (e.g. when it gets too small it won't scale the range anymore).
