### ISSUE TITLE
Stopwatch node restarting the playback when it should be resuming.

### ISSUE THREAD

**Issue by Coffee-Maker** [Frooxius/NeosPublic#1353]
If you play, pause, and then play the stopwatch node again it will restart instead of resuming. This is likely a bug introduced in update 2020.10.27.1173 where the resume function was modified, adding handling for when the playback doesn't loop and it's normalized position is approximately 0 to run the play function instead of resuming. The playback initializes with a value of float.MaxValue on the stopwatch so the normalized position will be approximately 0 when performing the steps provided within a reasonable timeframe.

**Comment by Frooxius** [comment]
Fixed in 2020.11.18.630, thanks!

- Fixed Stopwatch node reseting itself every time the Start is pulsed, rather than resuming (reported by @Coffee | Programmer)
-- Note some internal handling of playback for "infinite" playback was changed, so NormalizePosition for such clips is always -1 to indicate that it's not valid/applicable. There are possible sideeffects and glitches to this, keep a lookout, but things seem to be good from testing
