### ISSUE TITLE
DuplicateBlock and GrabBlock Component doesn't work for desktop users

### ISSUE THREAD

**Issue by ChrisWarner103** [Frooxius/NeosPublic#1356]
Adding the DuplicateBlock Component to an object than trying to duplicate it in desktop mode using the "F" key. It'll still duplicate. This is the same as the GrabBlock component. DeleteBlock works fine. It does as intended but the two components don't work in desktop mode.

**Comment by Frooxius** [comment]
This is unfortunately because desktop isn't officially supported right now and the mode is hacked together, so it doesn't respect a lot of stuff like this. I could hack this in as well if it's really crucial, but usually I avoid doing much with the mode and instead waiting for proper desktop support.

**Comment by Frooxius** [comment]
I ended up fixing the DuplicateBlock in 2020.11.21.1177 since it was trivial enough. The GrabBlock should've already worked, since it's being checked for in shared code in the Grabber itself, but the check there was incorrect and wouldn't work if GrabBlock was on the same object as the Grabbable, so I think that's what caused the issue, should be fixed too now. Thanks!
