### ISSUE TITLE
OnLoad Event Node should be renamed

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1358]
- This is stemming from a conversation in #questionsandhelp in the discord https://discord.com/channels/402159838827905024/439421735474036738/778727107186524180
- Some Suggestions are OnCloudLoad OnLoadFromCloud OnCloudSpawn

This is a suggest but if you see a better name to switch it to feel free. I just wanted to make this event node be more easier to understand use wise.

**Comment by TehTurk** [comment]
On a DM from @Zyzll he actually let me know that this might not be quite the case. https://discord.com/channels/402159838827905024/439422161657135106/727800150063317022
The namecase is still very broad and a bit confusing to the layman or when your not aware/thinking, but if this removes it's consideration I can understand.

**Comment by Frooxius** [comment]
This won't get changed, the node follows the name of the underlying event in Neos, as do all others. Naming it to someone else would be inconsistent and more confusing. E.g. all the proposed names are technically wrong, since it doesn't relate to cloud loading at all, any loading process will trigger this event (e.g. load from locally saved items and such).

**Comment by TehTurk** [comment]
Thanks for the followup Froox. Dang okay, and loading events aren't like easily inherently known or easy to figure out. So maybe I'll try to document it for reference then 🤔

**Comment by Zyzyl** [comment]
The wiki has a filled out page for this node @TehTurk - if you make any additional observations that would be a good place for the :)
