### ISSUE TITLE
Context menu selection new user observations

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1365]
New users tend to need to be shown how to select things in the context menu, as they often seem to expect selection to be a different mechanism than full trigger press.
It's not uncommon to ask a new user to select something, they open the menu and highlight an option just fine, but it takes them a few tries to actually select something. 

I've noticed other games use the on-trigger-release mechanism to select menu options (the steam vr home works in this way) allowing for light trigger taps to select menu options instead of full clicks. This follows with desktop ui where on mouse up is what I see as the common action trigger.

In terms of this bug, these observation bugs have been problematic in the past because the close criteria is vauge, I would personally consider this resolved if:
* Y'all consider this as an issue for later.
* Y'all consider this not viable feedback and will not look into it (which would make me sad)
* Y'all consider the selection process fine as is (would also make me sad as this menu interaction issue is a very common thing I see)
* Y'all allow this to be setting configured so usability can be tested with new users (quite a bit of effort)

I know this would effect every button interaction and not just the context menu, but I'm curious if it would be an improvement to global useability and not just during new user onboarding.

**Comment by Frooxius** [comment]
What exactly are they expecting to the interaction to be? The menu was designed this way precisely because lots of users were having problems operating the menu when the mechanism was different from all other UI's. Do they expect some completely different mechanism from trigger? Or is it just not triggering on the press, but after release, allowing to cancel the action by moving away?

**Comment by Earthmark** [comment]
From what I've been seeing:
Dragging through the option is common (but without holding the trigger), this is probably taught from half life alyx at least, unsure of prevelance in other games.
Cursor over then what looks like a trigger bump is also common (I'll need to make a tool to watch this more closely and verify that it's trigger bump).

This may just be an education thing as well, the new tutorial panel may resolve some of this. Much of my experience is this is from over time, before that panel was made.

I realized I should make this issue when I had a friend join recently and they commented on the interaction requiring 3 unique gestures to select anything in the menu (ctx -> move -> full trigger; this isn't bad but the last one seems to not be a common go-to), and up to 5 unique gestures to do something like delete an accidently spawned avatar (partially hold trigger -> grip -> ctx -> move -> full trigger; the first one is optional). where those gestures have very little wiggle room (if the first step is full trigger a different ui path occurs) and are hand specific.

I'm not saying these are not needed things, just that they are often complex and users seem to often get frustrated and/or confused.

I think I need to gather more information though, probably didn't think through making an issue. I'll see about getting more data to better answer this question.
If you like feel free to close this for now and I'll re-open when I have more data, if that data indicates an issue.

**Comment by Frooxius** [comment]
Are they dragging through the option while still holding the menu option? On some controllers we could potentially switch to the Menu button being held to allow drag through, but problem is that only some controllers support that - on Vive controllers long-press of the context menu instead opens/closes dash due to lack of free buttons. I'd rather keep it consistent.

I'm not sure what "cursor over what looks like a trigger bump" really means? 

I don't know how would we make those more simpler while still allowing to do same number of different operations or not introducing a lot of unexpected behaviors where it does a thing without the user confirming. 

A lot of general UI interactions are lots of tiny steps like that. Think about deleting a file in your computer. You move the cursor over the file, press right mouse bottom, you move the cursor to the delete option and you click the left mouse button. 

There's not much that can be reduced with things like this, other than making specialized actions - e.g. you're in mode when a single click/action deletes whatever you point at, but then you need to get into that mode, if you forget or don't know how to get out of it you just end up constantly deleting everything and getting even more frustrated. This menu is designed so it avoids triggering actions the user might not necessarily want to.

**Comment by Earthmark** [comment]
I'm gunna close this for now until I get more information, I agree with you that many system interactions are like this as well... Thanks for your patience with my random bug requests!
