### ISSUE TITLE
Neos doesn't connect to outside websocket properly.

### ISSUE THREAD

**Issue by Psychpsyo** [Frooxius/NeosPublic#1375]
I wrote a websocket which I had Neos try and connect to from logix. My websocket picked up on the incoming Neos connection and was able to give me the IP it came from but Neos did nothing and fired the disconnect event a little later. I managed to figure out that my Neos client did hold onto the TCP connection until shutdown though. (Even after deleting the component and leaving the world it was in.)
My websocket was written in C++, using the default Windows socket library (winsock2.h), once implemented by myself and once using a library.

I'll append the code example using the library as it's a lot simpler and more stripped down, together with the library.
[Neos Websocket Bug.zip](https://github.com/Frooxius/NeosPublic/files/5579871/Neos.Websocket.Bug.zip)

**Comment by Frooxius** [comment]
This is most likely something with your code, the Websocket in Neos is confirmed to work and connect properly as there are many applications using it and we're using a popular library for Websockets: https://github.com/sta/websocket-sharp

Are you handling the handshake and all the necessary parts of the protocol properly? I'd recommend testing directly against that C# library that I linked and see if it works with that one or not. I'd strongly recommend using existing Websocket library on your end as well rather than writing it against raw sockets, as it's easy to miss something in the proper protocol flow and have things misbehave like this as a result.

**Comment by Frooxius** [comment]
Here's the Websocket protocol specification if you really want to go the route of implementing it yourself: https://tools.ietf.org/html/rfc6455 Does your implementation conform to this specification?

**Comment by Psychpsyo** [comment]
No, it does not. Turns out that I very much did not know what I was doing, as I tried to just accept a TCP connection.
Sorry for wasting time.

**Comment by ProbablePrime** [comment]
It happens to us all :). Thanks!
