### ISSUE TITLE
Exclude users from reflection probes

### ISSUE THREAD

**Issue by candypheonixIO** [Frooxius/NeosPublic#1376]
Would it be possible to add a toggle for reflection probes to not render Users, this would be useful in situations were a realtime reflection probe is used, but would not want players rendering on the cubemap.

**Comment by shiftyscales** [comment]
It's probably something that should be done sparringly if at all- but I had a similar thought along the lines of using a single realtime reflection probe that uses position at local user.

**Comment by Frooxius** [comment]
I'm sorry, but this can't be added, you'll need to wait for the layer system for this: https://github.com/Frooxius/NeosPublic/issues/1277

Excluding users this way is quite expensive, as it requires marking the whole hierarchy before render, rendering and then unmarking afterwards with regular cameras.

Problem is, realtime reflection probes don't behave like regular cameras though, as they render on their own and their rendering doesn't happen fully in sync with main rendering (e.g. they can slice the rendering over several frames). As such there's not a point in time where the users can be temporarily hidden, because normal rendering can happen in the meanwhile. This would make users flicker for your real world view.

Instead, the layer system will let you place users onto a dedicated layer and then tell the probe to never render that.
