### ISSUE TITLE
Component to mask and tint specific parts of an image

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#1378]
Use Case 1: 
the recently added reflection probes are wonderful, however when used in an environment with color changing effects their usefulness is diminished. tinting the entire cube map texture would not work, as it would also tint the entire environment as well. 

Use case 2: 
some times, parts of a texture want to be recolored, without converting those textures into splat-maps. again, tinting the entire texture would have bad side effects. 

the proposed component would have a base texture slot, a mask, and a tint setting, perhaps also a blend mode setting. 
the component would provide a texture, such that it is the base texture modified with the mask and tint applied according to its blend mode.

**Comment by Frooxius** [comment]
Unfortunately this is a bit of a complex issue, what you're asking for can be several different things/features, but they won't solve the problems properly.

One way is to create a wizard where you drop in the textures and it generates a new texture. However that's a bit more of a niche use right now and I'd rather instead make something more general, which is going to take longer. However that will not work for anything realtime, certainly not reflection probes.

Even if it was realtime, it still wouldn't work for reflection probes. Those use cubemaps, not traditional 2D textures. Constructing these is not realtime either, but what makes this even more complicated is that for reflection probes, the cubemaps undergo some blur convolution passes, to simulate diffuse/specular irradiance. Simply tinting the resulting texture will produce wrong results.

It is the nature of baked effects that they are static, because they're "baked in" to the specific snapshot of the environment. If you have your environment changing in realtime and you want more accurate reflections, you will have to use realtime reflection probe, but you will also pay the performance cost.

One way to amortize this would be to expose the texture of the realtime reflection probe, so you can use it in another. This way, you could have a realtime reflection probe far in distance, with a 360 photo of the environment around it and any effects using Neos' materials on top of it and then use its texture for the other probe in the actual environment. That way you skip re-rendering the actual geometry if you setup the probe right and reduce some of the performance impact.


I'm not really sure what to make of this request otherwise. What you're specifically asking for won't solve your Use Case 1 and for Use Case 2 I'd just recommend keeping the source files (splat-maps and base texture) around, if you need to bake a new version of the texture.

**Comment by mralext20** [comment]
i see. thank you for the insight. i shall be closing this.
