### ISSUE TITLE
LogiX Node Selector loses reference to tooltip when switching worlds

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#138]
## Problem
When using the LogiX tooltip, opening the Node Selector, and switching worlds, the selection within the Node Selector does not affect the tooltip.

## Steps to reproduce
1. Equip the Logix tooltip
1. Hit the Menu button and select the Node Selector option - Observe the panel with node types to select
1. Double click on a node type - Observe the text on the tooltip change to the selected node
1. Switch to another open world with the  world browser
1. Switch back to the original world in which you opened the Node Selector
1. Double click on a node type - Observe that the text on the tooltip does not change, and double clicking does not open a new node of the type selected

In order to get this to work you have to close the Node Selector and open a new one.

## Desired Interaction
When switching back to the world in which you opened the Node Selector, it should still function to switch the node type when you select one.

**Comment by Frooxius** [comment]
This is a bit tricky to implement, because when you switch between worlds, the tool gets transferred from one world to another, breaking any links to that world.

I plan on implementing structures to store translation tables and restore original references when bringing an object back, but that takes some doing to do properly, so it might take some time.

**Comment by Frooxius** [comment]
This is now solved by the interface not being tied to a particular instance of the tooltip.
