### ISSUE TITLE
"Contacts+ Worlds" needed before everyone becomes a hiding hermit

### ISSUE THREAD

**Issue by GearBell** [Frooxius/NeosPublic#1410]
As Neos grows, Neos Players are becoming anti social with hiding in private worlds and contact only worlds or hidden worlds. Im slowly seeing groups mingle less and less as we seem to hide from the general public. We are in very dire need of a Contacts+ world setting, in which those who are friends of the host and friends of whomever is present in it can join - to allow for a slightly filtered yet open to new mingling. Yes, you can at the moment set your world to hidden and allow for anyone to join - but Hidden World is offputting and noninviting plus you still need to find whoever the host is and ask to join through them, if they ARE on your contacts list at least. Not to mention very few people know of the "hidden, yet anyone" trick so they choose contacts only or private. We very badly need to open up worlds a bit more through Contacts+ access because at the rate everyone is hiding you will only ever see the same people and watch as their social groups shrink and people will get bored with Neos.

**Comment by shiftyscales** [comment]
Hey @GearBell - I'm sorry you've been frustrated with the current social climate in your circles.

There are already a few issues open that cover the needs expressed here. #693 and #701.

These are things that are intended to be addressed when the Contacts UI is reworked.

Having 'Contacts+' on itself isn't going to help things considerably with regards to the issue you're expressing. There already is the 'Contacts' mode which is an even tighter (but still publicly visible) mode.

There are many potential (and valid) reasons why a user may wish to utilize a hidden or private session.

What would help more is identifying the underlying reasons why even the 'Contacts' setting isn't more widely used. I imagine it's because most users perceive even it as being too broad, at least until such point as we implement our planned user tagging system along with the Contacts UI overhaul.

**Comment by dawky110011** [comment]
I would love to see something like this implemented. As someone in an odd time zone, I usually get stuck by myself with everyone either hidden or in a contacts only world. I find these sessions are appearing more and more, and most people don't know about the "hidden but can invite" worlds. I'm finding people are in these worlds more and more as neos grows to just hang out with friends, but leaves me by myself. I dont feel comfortable asking people for an invite, but would rather join a world thats like a "friends+" instead of the awkward "can this person add me".

**Comment by DeliriousJax** [comment]
I agree with @GearBell  

A setting for contacts and contacts of those contacts would be really nice as it has become Way harder to join people or whatever without adding some host I don't know, or having to add someone I don't know so they can join me to hang out with one of their friends. Then many times that contact sits dormant or I remove it, then have to add it back later on at random times based on situation.

I get that the contacts UI is under way, but I feel like this is urgent enough a change to make even sooner. Especially since the "don't show in session list" check was added.

**Comment by Enverex** [comment]
You guys want the earlier issue of https://github.com/Frooxius/NeosPublic/issues/701

**Comment by TehTurk** [comment]
Yeah if it helps I recommend doing a 👍 or chiming in on your thoughts there as that's the open one too. I have a few thoughts I myself need to add too.

**Comment by inzanesonikku** [comment]
no, im agreeing with gearbell here, there are far too many people hiding in private or contact+ worlds. i aint sorry to say this, but it startin to look like VRC with this shit.

**Comment by TehTurk** [comment]
I do too, but talking on a closed issue doesn't help D: you wana say this on #701
