### ISSUE TITLE
Only Player Who Spawned Video Sees Video From Website URLs

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#1418]
While YouTube and Twitch links appear to work fine, trying to paste links directly to video media hosted elsewhere (e.g. direct to .mp4 or .mkv files on a website) only appears to work for the person pasting the URL. It'll load almost immediately for that person, but it'll remain an unloaded texture for everyone else.

Checking the logs of the target server shows that only the person pasting the URL ever tried to load the video. No connections were ever made by the other people in the world to the server the video is hosted on, as though it simply didn't even try. If someone else then grabs the (broken for them) video and duplicates it, the duplicated video will then work for the person that duplicated it (and a connection to the server can then be seen in the server's logs) but no-one else in the world will see that copy of the video (it remains checkerboarded).

Example URL to test this with - https://xnode.org/archive/nsp/Ninja%20Sex%20Party%20-%2020201123%20-%20Welcome%20To%20My%20Parents'%20House%20-%20NSP.mkv (safe for work, despite how the name may look)

Obviously you need more than one person present to test this as it'll always work for the person trying to load the URL themselves.

**Comment by Frooxius** [comment]
Do you have logs from a session for at least one person for who the video loads and for who it doesn't load? Having logs from a clean replication case might help.

**Comment by shiftyscales** [comment]
I just tried replicating this issue with Aegis, @Enverex.
The steps I took:
- Created a new video player with the dev tool tip
- Waited for Aegis to join
- Pasted the video URL into the URL input of the `VideoTextureProvider`

After a few seconds it loaded for me, and them him nearly immediately after. Playback worked for the both of us.

I then tried pasting the video as you had instructed, and it caused the issue to occur.

I think I found the issue/reason, though. For some reason when pasted in, the video is imported as a 'stream' which causes it to not load properly, **if the 'stream' checkbox is unchecked, it loads properly for all users**.

Despite your claim, duplicating the player didn't cause the video to load for either of us in testing.

My log:
[SHIFTYWINDOWS - 2020.12.1.501 - 2020-12-01 16_26_09.log](https://github.com/Frooxius/NeosPublic/files/5626280/SHIFTYWINDOWS.-.2020.12.1.501.-.2020-12-01.16_26_09.log)

Aegis's log:
[DESKTOP-CT41UQL_-_2020.12.1.501_-_2020-12-01_18_26_11.log](https://github.com/Frooxius/NeosPublic/files/5626284/DESKTOP-CT41UQL_-_2020.12.1.501_-_2020-12-01_18_26_11.log)

@Frooxius

**Comment by Frooxius** [comment]
When you uncheck the "Stream", Neos will download the file and play it from the locally downloaded file.

It seems like there's something odd with the server hosting it, it doesn't seem to like concurrent connection from the libVLC library for streaming. I've enabled detailed logging and it always fails at the https connection establishment on the other account. 

Given that every client is loading the video completely independently of each other (there's no shared logic or any sort of exchange in the loading process) and streaming from different servers works fine with streaming (e.g. http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4), there's not really much more that we can for this on our end. I'd recommend checking the configuration of your server, see if there's any sort of throttling / DoS prevention or something that might be tripping it up.

Either that or switch to a different streaming server or download the video first. 

I've found that the retry attempts don't work when video is streamed, which will be fixed in the next build and I've added extra delay. It didn't seem to help in my testing, but I can't really do more than that, sorry.

**Comment by Enverex** [comment]
> I've enabled detailed logging and it always fails at the https connection establishment on the other account.

Can I see this detailed logging please? The server's just running a standard Apache setup so it seems odd that it would be having issues with VLC in any way (given that it works for the initial user and works fine if anyone tries to use the VLC standalone program to load the videos).
