### ISSUE TITLE
[Bug?] Setting the loop property of a playing clip stops playback if the clip has already looped

### ISSUE THREAD

**Issue by Zyzyl** [Frooxius/NeosPublic#1438]
I'm not clear if this is a bug or intended, but thought I'd flag it just in case.

It seems using the SetLoop node to set the looped status of a playing clip to False does not interrupt playback if the clip has not yet looped. However, if the clip has played more than once and has looped, using SetLoop (False) interrupts playback and sets the playback position to the end of the clip. Since this is inconsistent between whether the clip is playing for the first time or not I guessed this might not be intentional.

**Comment by Frooxius** [comment]
This is intentional. The way looping works is that it just "wraps around" the playback time. E.g. if you have 10 second clip and it has looped once and it's at 5 seconds, the raw playback time is 15 seconds. If looped twice it would bee 25 seconds. Once you disable looping, this will stop it immediately, since the raw time is beyond the length of the clip.

This is done because playbacks are used for more than just audio playback, anything that keeps a track of some "starting time" uses this (e.g. animation, custom times and so on).

If necessary it could be changed, so it recomputes new playback position when it's set to false though, perhaps as an option.

**Comment by Zyzyl** [comment]
Thanks for the explanation, I think I understand why it does what it does currently. I don't think the current behaviour is necessarily a problem, this just came up while I was testing how stuff worked. 

A priori, I think my expectation would have been that playback would always continue up to the end of the clip (whether it had looped or not) if SetLoop (False) was used. Without knowing anything about how things work under the hood, my feeling was that changing a 'setting' should not suddenly stop playback - that should be the job of Pause/Stop etc.

Would probably need more opinions from other people to decide if this is an issue so I'll leave this open. Feel free to close at your discretion though since this isn't causing me any problems atm
