### ISSUE TITLE
Setting a color to NaN and opening a color picker freezes all users in the instance

### ISSUE THREAD

**Issue by shadowpanther** [Frooxius/NeosPublic#1440]
Steps to reproduce:
* make a NaN, for example a division node with no inputs
* route this NaN into a color, by using Pack rgba of From HSV
* drive any color value with the resulting color
* remove the drive (optional?)
* in inspector, click the color box to summon a color picker window

**Comment by Frooxius** [comment]
Do you have a log at hand from this? It's likely messing up some of the related components which try to use the NaN values directly .

**Comment by shiftyscales** [comment]
I believe the `freezing` is as a result of the massive performance degradation associated with the constant exceptions generated.

[SHIFTYWINDOWS - 2020.12.5.1396 - 2020-12-05 20_45_56.log](https://github.com/Frooxius/NeosPublic/files/5648310/SHIFTYWINDOWS.-.2020.12.5.1396.-.2020-12-05.20_45_56.log)

A log from recreating the above. At first I just opened the color picker, then I closed it, removed the drive, and re-opened the color picker. The massive performance degradation only seemed to happen after removing the drive, but both were visually glitchy due to the material using NaN colors.

The bounds of the color wheel was also invalid due to NaNs propagating into it as well. (Line 507.)

**Comment by Frooxius** [comment]
Ah yeah that definitely seems to be the case, I made some changes for the next build, that should help.

**Comment by shadowpanther** [comment]
Also worthy of note that I first discovered the glitchiness of NaN by setting a NaN color to a light. Everything in the light radius went perfectly black, including LogiX nodes and inspectors, so figuring out how to undo it became tricky. That didn't hit the performance yet, just a visual effect, but one that can create a lot of inconvenience.

**Comment by Frooxius** [comment]
All cases should be fixed in 2020.12.8.638, thanks!
