### ISSUE TITLE
Video Streams Playing while de-activated and between worlds

### ISSUE THREAD

**Issue by skywindkitsune** [Frooxius/NeosPublic#1449]
Issues:
* Video Streams appear to keep playing even while paused, the audio will cut out but the video will continue to play.
* Video Streams also do not stop playing when the object containing them de-activates
* Video Streams also appear not to stop playing between worlds.

This only occurs with Video streams from Youtube/Twitch, regular videos work fine.

Result:
Causes Neos VR to crash and sometimes the whole computer to blue screen when it runs out of memory.

Observed doing the following:
Had Video Stream: https://www.youtube.com/watch?v=KFz52twepU4 playing on Rhenium's Youtube TV Player at my Home.
Switched over to work on my Skyhawk Complex World which has 2 of Rhenium's Youtube TV Players one in the upstairs deck and the other on the lower deck, the entire lower deck including the TV is deactivated when you are not inside a Collideable trigger, this is also done locally per player with a local user override.

The upstairs TV was playing: https://www.youtube.com/watch?v=kfvKw9y-ano
the downstairs TV was playing: https://www.youtube.com/watch?v=OVPPOwMpSpQ

Resulted in an FPS drop from 62 to 18 constant even tho i was standing on the upper deck with the downstairs TV de-activated, my PC blue screened shortly after.

Tried again a second time and encountered the same issue again.

Tried a 3rd time but this time i closed my Home world which resulted in an immidiate increase in FPS.

all the Video players were using the LibVLC plugin.

About my Setup:

CPU: AMD-FX 8300
GPU: Nvidia GeForce GTX 1660 Ti
Ram: 16 GB
HMD: Oculus Quest Running wirelessly trough Virtual Desktop

**Comment by Frooxius** [comment]
Unfortunately this is intentional. The current version of libVLC that we're using doesn't handle pausing the stream gracefully, so the workaround where they do keep playing has been added.

I'd recommend only using single stream in a world to watch any live feed when needed, but not make them permanent part of the world. Alternatively you can use one video player and change the URL to load a different stream.

Once we upgrade to the official libVLC support, I'll revisit this issue.
