### ISSUE TITLE
Enable Bone-Based Clipping

### ISSUE THREAD

**Issue by DFliyerz** [Frooxius/NeosPublic#1451]
It would be nice if you could make it so everything attached to a bone (ie the head bone) is made invisible in your view so you don't need to rely on clipping planes, since with those anything within a certain distance of you becomes invisible.

**Comment by Frooxius** [comment]
I'm sorry but unfortunately this is not something that's possible to implement, clipping is based on a rendering unit, which is the whole mesh, it cannot be done at granularity of individual bones, because those only deform the geometry, but then the geometry is rendered in one go.

At most it would be potentially possible to change the clipping settings per-mesh, but better approach for this would be having local overrides that scale the bone instead.

**Comment by DFliyerz** [comment]
That sounds fine, are local overrides currently possible?

**Comment by H3BO3** [comment]
Not yet, Froox needs to make some changes to the render pipeline to support it.

**Comment by InsaneGrox** [comment]
Technically yes, but it also appears in mirrors unfortunately at the moment :(
