### ISSUE TITLE
[Bug] Gizmo's break UVRayCastPortals until they're cleared

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Frooxius/NeosPublic#1460]
Having a part of the canvas or any uix slot focused and as such having a gizmo out aswell, "breaks" the uvraycastportal until the gizmo's are cleared. At which point it becomes responsive again.

This makes working with UIX & UVRaycastPortal's difficult.

Some problems that occur: The entire Canvas becomes unresponsive until gizmo's are cleared. Workflow, while it should be the same as for normal UIX workflow, is strongly diminished by the need of having a devtip to clear gizmos at hand constantly.

Steps to reproduce:
- Any UIX Canvas with a camera, uvraycastportal and all the other needed bits to make it work.
- Select anything underneath the canvas that one is working on.
- Issue becomes apparent.

I can supply a sample if needed as-well.

**Correction upon further analysis

The Canvas only behaves in the aforementioned way if it's in a hidden layer and moved away (for example high into the air to make sure that no interactions with the world happen).

**Comment by Frooxius** [comment]
This is expected behavior given your setup. Hidden layer is designed precisely so it doesn't have to be moved away far away, but can stay exactly at the same position. If you use HiddenLayer you should never move the hidden part really far away.

Similarly UVRaycastPortal's function is to transfer raycasts. It's not specific to the canvas, it will let you to create any sort of interaction, including interaction with gizmos. When you move the object far away, the gizmo becomes really big and blocks the interactions. The system doesn't know that you want to interact only with canvas and not the gizmos, you need to configure it in such a way.

The best use with canvases is to switch the Canvas collider to "Trigger" and then on the raycast portal set the "OverrideHitTriggers" to True. This will prevent the laser from interacting with the hidden canvas, but the raycast that passes through portal will hit the Canvas as it's set to trigger.

I recommend checking out the curved canvas in the MTC 2.0 to see how it's setup or take apart Neos' own canvas if you can, they use this principle.
