### ISSUE TITLE
Contacts List Platform Indicator

### ISSUE THREAD

**Issue by LeDrascol** [Frooxius/NeosPublic#1476]
A head device type indicator to the contacts list (or other lists) to indicate what distinct platform is being used. This would be represented as an icon by the user's name corresponding to the mode (VR/Screen/Headless). This could help identify headless contacts, and users in screen mode for debugging. Additionally, the setting could be opt-out for privacy concerns.

**Comment by Frooxius** [comment]
I don't plan on adding this until proper desktop mode is implemented, as that will unify how desktop and VR and change how they're represented (and allow dynamically switching between the two), meaning the work on this might need to be scrapped.

Question is if it would be really useful then though, since desktop mode wouldn't necessarily mean just debugging, it could be someone playing normally. It might be better to just leave this system for contact categorization system instead, where you can categorize headless accounts and others.
