### ISSUE TITLE
Streaming cameras and local player culling sometimes break the user (or crash the server)

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1485]
Setup:
A space that us culled like so:
- Slot A 
  * Large box collider (trigger)
  * User collision tracker (the thing that says if local user is inside the box)
  * Player parenter (targeting slot B as the target of parenting)
  * Value copy - Copying the IsLocalInside to the active of slot B
- Slot B - parented under slot A
  * This contains the stuff in the room, and any users in the room.

Steps to replicate:
User A has a streaming camera on, and set to a mode where it follows the player (any mode but world and manual)
User A enters the bounds defined by the slot A collider

What happens:
The user is 'thrown', with their avatar seemingly gone, no way to talk, and no way to interact (seems like the user root is partially destroyed, I didn't check what slots under user survived the behavior though).
If the user respawns they are fine.

What I expected to happen:
The user enters the space, and the things under A render in for the user (and the user is parented under A).

[DESKTOP-5HFQ42U - 2020.12.9.819 - 2020-12-15 22_17_21.log](https://github.com/Frooxius/NeosPublic/files/5701236/DESKTOP-5HFQ42U.-.2020.12.9.819.-.2020-12-15.22_17_21.log)

Additional related bugs, setup is the same.

After the user is in the 'thrown' state, if the user is reparented under the root when in that state, they are kicked from the session due to an update failure.
[DESKTOP-5HFQ42U - 2020.12.9.819 - 2020-12-15 22_15_57.log](https://github.com/Frooxius/NeosPublic/files/5701239/DESKTOP-5HFQ42U.-.2020.12.9.819.-.2020-12-15.22_15_57.log)

If user A puts away the camera, enters the volume, then re-enables the camera, they see the camera under them via inspector and visually rapidly flickering near them. Other users see the camera in the world root via inspector, similarly flickering but near the world root instead. If the observer is in the collision volume as well, they see it rapidly flickering in both places.
For user A the camera wants to be parented under user A, but for what seems to be the host user, the camera attempts to be parented under the root. Other users see the results of the fight between the two. As the camera movement is smoothed, the result is a 'flickering' look of the camera oscillating.

If the host enters the 'thrown' state, the world crashes (or is rendered unusable, Rukio reported it and I don't recall his exact wording).

The behavior was verified with @shiftyscales and many others.

**Comment by shiftyscales** [comment]
Rukio had initially reported the issue, and also provided the following world as a replication case.

neosrec:///U-Rukio/R-5fb28d73-2f0b-4d92-a951-19bcbf6b46fc

The actual cause of this appears to be very specifically linked to a slot that has a CharacterParenter and ColliderUserTracker that is used to set the active state of the slot the CharacterParenter places them under. (The context/use-case being private rooms.)

I've made another world that can demonstrate the issue here:
neosrec:///U-Shifty/R-b48a171c-98c1-4788-9f4f-ca7d682ee442

To replicate, walk into the trigger with the stream camera out. You will be offset by the global transform of the slot the trigger is on, and because you are now outside of the bounds of the trigger, the ColliderUserTracker no longer tracks you and sets the slot you are parented under as inactive without de-parenting you from it first.

[SHIFTYWINDOWS - 2020.12.9.819 - 2020-12-16 01_13_53.log](https://github.com/Frooxius/NeosPublic/files/5701544/SHIFTYWINDOWS.-.2020.12.9.819.-.2020-12-16.01_13_53.log)

Possibly not directly related, but similar issues can occur with setups like these if a user changes locomotion modes as per #1144 wherein the ColliderUserTracker will lose track of a user that is still inside of its trigger volume.

**Comment by shiftyscales** [comment]
Others that assisted in testing included Tatsu Kimiero# 3109, Snooper# 0001, and Princessii# 0001.

**Comment by Frooxius** [comment]
Should be fixed in 2020.12.18.33 now, sorry for the trouble! Let me know if the issue still occurs, but I think it should be good now.
