### ISSUE TITLE
Snapper/SnapTarget persistance toggle

### ISSUE THREAD

**Issue by The-furf-of-July** [Frooxius/NeosPublic#1500]
I have plans to add a lot of snappers to my avatar, but I don't want the attached items to save with my avatar, i.e. collars, hats, other accessories. 
I have a LogiX script that accomplishes the same thing, but it has to be manually set up for every snapper. However, I feel like this feature may be well-suited to be a hard-coded option.

What the script does is, when a snaptarget is attached to a snapper, it sets the slot to be non-persistent, and once the object is detatched, it is made persistent again. This allows the snappable object to be saved, while also making it so it does not save with the avatar.

**Comment by Frooxius** [comment]
Hmm this might be potentially a good addition, but it brings a few problems. Ideally the objects persistence shouldn't be modified like this. It might not be accessible, it might already be set to non-persistent by something else, so the system would need to remember its state upon snapping.

What might be better approach is to add some general mechanism to indicate that "I'm persistent, but my children should not ever be saved". This might be common enough pattern to allow something general like that, rather than baking this behavior into the SnapTarget.

**Comment by Frooxius** [comment]
I've added ChildrenSaveBlocker component in 2020.12.18.1284, simply put it on the SnapTarget and it will prevent any children from being saved.

**Comment by The-furf-of-July** [comment]
Can the same solution be applied to the Snapper as well? Or does it need to be on the SnapTarget?
If it has to be on the item being attached, that doesn’t solve the issue.
Additionally, does ChildSaveBlocker prevent the snaptarget from being saved on its own?
