### ISSUE TITLE
Desktop view overblown whites

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#1501]
http://www.lagom.nl/lcd-test/white.php

Not certain if it's due to the post-processing stack, or other potential factors in the rendering pipeline, but when comparing the desktop view in Neos to overlays such as SteamVR, whites are overblown, causing a drastic reduction in definition of detail/definition in gray, and white, e.g. text, web elements in a browser, etc.

Inside of SteamVR I can distinguish each square on that test website, in Neos, all squares aside from 200 appear as pure white.

**Comment by Frooxius** [comment]
This is the postprocessing stack interfering, there's nothing going on with the texture itself. I've tried to mitigate this before the release, but unfortunately it's a bit more complicated, so it'll have to wait until I do some more work on the postprocessing.

In the meanwhile I can add an brightness slider to it, that might be useful in general when working with the desktop.

**Comment by shiftyscales** [comment]
I could see a brightness slider as being something enjoyed in other contexts as well, e.g. dimming the displays while inside of a dark world. I think that would be a good addition regardless for now, thanks @Frooxius !

**Comment by Frooxius** [comment]
I've added the brightness in 2020.12.24.35 and set default to 95 % which seems to help. I looked into it some more, I think it might not actually be the post processing, since it shouldn't really alter 100 % white (bloom starts at 110 % intensity), they might just be slightly dimming it by default in SteamVR as well. Not fully sure though, but regardless it seems to help, so I'm going to close this for now. Thanks!
