### ISSUE TITLE
Unify all tooltips into a single "Edit tool" that can be equipped more directly from the dashboard, and with it's own menu to select between all available "modes"

### ISSUE THREAD

**Issue by TiagoTiago** [Frooxius/NeosPublic#1515]
Instead of having to figure out you need to find some specific item in some folder "deep" in your inventory and then "equip" it, it would be much more intuitive if there was an easy to find button in the dashboard to equip and de-equip the "Edit tool", and additionally, it would come with it's own menu (that may be called both from in-world as well as from the GUI) to select the various "modes" available.

You can still keep the conventional approach of having the individual tooltips be files inside folders thrown around the inventory; but additionally, there would be a special folder you place the default tooltips everyone should have from the start, which would be used by the "Edit tool" functionality to populate it's menu (you can even have sub-folders produce sub-menus to help organize things), and which may be customized by the user to have whatever tooltips they want (and reorganized as desired with the help of sub-folders as suggested above).

Maybe it would be ok to at first leave customizing the tools menu to "advanced" users at first; but if you wanna also already go ahead and bring it more in reach of newbies already; instead of leaving it restricted to direct inventory manipulation, you could also add an option to add any standalone tooltips currently equipped or grabbed into the menu, and of removing/disabling any tools from the modes menus.

ps: And of course, you can dual-wield Edit-tools and have have each hand be in a different mode at the same time.

**Comment by ProbablePrime** [comment]
This sort of concept already exists in the form of a Multi-Tool. Multi-Tools take the majority of the frequently used editing tools and place them within the same sort of interface. There are quite a few available on the market. 

Once you have a Multi-Tool, (There are even some in the essential tools folder). You can configure it to be saved on your avatar. With this in place you don't need to even spawn it.

I myself keep all of my tools stored inside my face. 

Further enhancements to Neos' UI in the future in the Areas of Facets(widgets within the UI) and the inventory may allow for quick spawning menus to be placed within your UI space that allow you to spawn these multi-tools very quickly.

For now spawning a single multi-tool once per session or storing one on your person is a perfect solution to your suggestion I feel. 

Some good Multi-Tools are:
The Architect - Winner of the recent MMC competition. 
H3's Multi Tool - A very comprehensive tool
Exit's Tool - A very feature Rich tool with a lot of added parts.

You can find most of these within various public folders or worlds while in game.

The Architect can be found in a world called "Edge of Reality" there's also a long overview of it here: https://www.youtube.com/watch?v=xbbpZZ8bCDU

H3's Multi-Tool can be found in their public folder you can pick this up from the Directory.
The same goes for Exit's multi-tool. 3x1t-5tyl3 is their name ingame.

**Comment by Abysmal2134** [comment]
I always thought that the main tooltips would eventually be swappable from the quick radial menu, similarly to how the locomotion settings are picked.
If not that then migrated to a facet menu that stays facing you in the userspace and syncs it's contents to the inventory tool folder.

I'd imagine more work on facets and the inventory would be needed first since Froox has mentioned wanting to have easier ways to access locomotion and tools before.

**Comment by Frooxius** [comment]
@ProbablePrime and @Abysmal2134 are correct, there are mechanisms that will allow for quick swapping of tools and their functions, both with the planned UI additions and multi-tools that can be made with Neos.

At the core, Neos will always use separate tools for different tasks, because having a single "megatool" doesn't scale as more tools are added and adds extra burden on people trying to learn those tools. I expect that we'll see lots of specialized tools in the future for different tasks, both official and user-made. Once there are dozens or hundreds of tools, a single unified tool becomes too impractical. 

Instead the user will find a good collection they regularly use and either make them into a multi-tool or use the quick swapping mechanism. 

A good example of this are brushes for example. There are already many versions of those, with different styles and behaviors. Different tools can also have different form factors depending on what they do. E.g. with brushes we're moving towards them actually looking like different art tools, to make it easier for users to tell what they do just from looking at them.

I'm going to close this issue, as this won't get implemented officially and the underlying issues are planned to be solved in different ways.
