### ISSUE TITLE
Desktop Access Keyboard oddities

### ISSUE THREAD

**Issue by eduprimowl** [Frooxius/NeosPublic#1519]
I am having an odd issue in Blender with the Desktop Neos Keyboard.
If I open a field to enter an object/mats name or other field of entry, I can Paste, Hit Enter.
However any keys typed do not appear in the fields whether numbers/letters.
The keyboards Tab button however does toggle edit/object mode from the keyboard and arrowkeys flip throuugh keyframes.
I also submitted this using NeosVr Keyboard so it's working elsewere such as firefox.
Literally the only thing stopping me from my entire workflow in blender  via NeosVR

I love this abiity so thank you for what's here.  My wrist can barely take mousetime anymore, and OVRtoolkit/VirtualDesktop r meh.

**Comment by Frooxius** [comment]
Hmm, I'm looking into this and this seems to be because Blender doesn't seem to support/respond to Unicode key events for some reason, only the direct keyboard scan-codes. This is a bit tricky. I could make Neos send keyboard scancodes for regular letters and such, but that means we'd lose unicode support and/or get inconsistent behavior based on what your keyboard layout is.

**Comment by Enverex** [comment]
FYI Blender doesn't respond to the SteamVR keyboard either.

**Comment by Frooxius** [comment]
I see, thanks for the info. Yeah this is tricky, it sounds like they wrote their own stack for processing keyboard input (or at least part of it), rather than using the one provided by the OS. I'm not really sure what could be done about this on our end.

One thing I could do is add togglable "legacy input mode" which will always send keyboard scancodes, but you'd have to toggle that on and off manually and it would behave weird if you use keyboard layout in your OS that doesn't exactly match the Neos keyboard. E.g. If you had AZERTY, Dvorak, QWERTZ and such, the labels on the Neos keyboard wouldn't match the ones you see.

Alternatively you could try bugging Blender so they add support for this input event: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/551b9903-8fb9-4d00-b3ac-a187431efb86 but considering it's not supported right now, they might have some major hurdles that are preventing that from happening.

**Comment by Frooxius** [comment]
Looks like they have made several attempts to implement this. It seems that it stems from not supporting IME on Windows. Here are some relevant issues I found:
https://developer.blender.org/D765
https://developer.blender.org/D6861
https://developer.blender.org/T54138

Not much we can do on our end, as this is more of a Blender issue, other than the "legacy input" hack I mentioned above.

**Comment by eduprimowl** [comment]
Thank you for looking into it, I will just make a string logix input, and use it to type and copy from there to  paste into desktop blender.
If you feel frisky and it's not too much trouble legacy input option would be nice.
