### ISSUE TITLE
MatCap + Color Masking Support in Toon Shader

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1536]
## Is your feature request related to a problem? Please describe.
Often when helping users I've found alot of them requesting MatCap Support or Color Masking for their Toon Setups. There is currently a way to do MatCaps but it's not ideal in a way.

## Relevant issues
There is #1473 But I think it didn't focus on the issue properly at hand. So reopening it due to discussions that have popped up around me about it. If this is grounds for disregarding it I'd ask to at least leave it for future consideration, I know a Shader System is a HEAVILY requested thing which ,(Because then you could do it yourself) so little things like this can help people hold over until we get it in some form. 

I do know #428 Does mention Color Masking and MatCaps when we first conceptualizing the Toon Features, and I know maybe weren't a super priority then, but I think it'd be a good thing to have a hold over to keep things basic as well too. 

## Describe the solution you'd like
- Support for it in Modified Xies in some form
- Or Improve the Current MatCap Material, and a ColorMask Material (That's a Filter Mainly, or at least can use the features properly)

## Describe alternatives you've considered
Currently there's a way where you can Overlay the MatCap Material, then having the Main Material appear, and get a similar effect, but as a result your missing some features that MatCaps can natively have like influence bias and otherwise etc, and it's not ideal for those who just want to use the support but in a nice and easy fashion.

For Color Masking it's a bit different atm.

## Additional context
 I'm aware the JP Community currently uses the MatCap trick for alot of their avatars, so it would be a benefit to many groups of Neos I'd reckon. Having more bare minimum features also coaxes users over because it lets people do the bare minimum of features that we could support without too much maintenance.

**Comment by dawky110011** [comment]
This is a feature that NEEDS to be implemented, since visuals are everything when it comes to avatars and first impressions. 

I have models both in MMD (a film making software) and unity, that take major advantages with matcaps and masking.

I've been asked a lot from people using human models, if they can put a matcap on their skin/clothes/jewelry and if they can mask it so it only shows in certain areas.

The same with emission masks. I've met people who DO NOT want to play neos because they simply cannot have these 2 things on their avatar.

For example, matcaps are used as a fake reflection, a pearlescent effect or to completely replace an albedo with a toon like matcap. rarely are they used as an albedo. MMD models and various other models have these as a standard to their texture list along side shadow ramps to complete the look. Metallics and gloss DO NOT give the same desired effect and can make things look worse in some cases. 

Masks are used to create scrolling emissions via the map, but masked so they don't take over the whole albedo, only where they want the emissions to show.  (scrolling emissions over tribal tattoo's, noise emissions panning through masked areas of clothing etc)

Another thing I have noticed with the pre-existing matcap shader is that it rolls when you roll your head. Which has confused me since i have never seen a matcap used like this. reflections dont roll when you roll your head, so why does the matcap. ( I will open a 2nd github request on this if needed)

I feel like the implementation of matcaps and masks too the pre-existing toon shader IS A MUST HAVE since people use "custom shaders" just to get these 2 effects, which I know are a part of the xiexe toon shader. 

I've seen too many people complain about this, and from what i can recall, it has been asked A LOT

**Comment by Frooxius** [comment]
If there are many people asking for this, I'd suggest telling them to vote on this issue. Using strong language and caps won't help increase the issue's priority, we need to gauge how many people actually need it compared to other issues.

Adding this particular feature represents a potentially significant maintenance burden on our end and will delay a switch to another render pipeline in the future and introduction of custom shader system, as those features will have to be re-implemented, so I'm trying to keep the additions minimal.

I'd consider adding this if there's really big demand for it, but so far only you and Turk voted on this issue, which is a lot less than other issues get, which have much lower maintenance burden. There are many other issues which prevent people from playing Neos so we need to priorities which ones get addressed and which ones do not.

**Comment by dawky110011** [comment]
My strong language is only due to the concerns people have with it. The disappointment in new users voices when i tell them they can't use it hits me since i would love to see it too. I have friends in neos with collections matcaps that would love to take advantage of this and i will be sure to pass this along, as we talk about it from time to time.

I would love to get people to comment on this, but the majority of people who i have spoken to have either left your game or have mentioned it on the discord. Some people don't even think about commenting on a github ( i never considered it untill months in ) so I'm only voicing what players have said to me who never thought about directing it here.

Next time this is brought up in convosation I will direct them here. 

Thank you for considering this, as i know it is not a priority, but something heavily desired.

**Comment by Frooxius** [comment]
I understand the concerns, it's just that we have tons of different voices complaining and leaving about lots of different problems all the time. There's only so many of those that we can address at the time (and some are much easier to address than others) so we need some way to tell which issues are affecting lots of people and which ones are just people very vocal about, but affect fewer users.

Directing them towards voting on GitHub will definitely be most effective, when it's scattered around conversations in-game or in Discord it's hard to keep track of and a lot of it doesn't reach us at all, so no change happens.

Priority for issues is fluid. If there's a surge in interest in this, then it will become prioritized.

**Comment by TehTurk** [comment]
Will do o7 It's only been around for 5 days issue wise and sometimes some issues are talked about a bit before the issue is related in a proper context fyi, it happened with hip tracking to some degree as well, which still requires more votes imho because I know I've had many users request more on the social side of things for it to be requested. So demand isn't always quantifiable, but I'll try to direct people to the github to properly upvote issues like these a bit more strongly. 

Only reason I originally brought this up is that this was considered for the original ShaderBase vs like an Extra Addon that sometimes can get requested from time to time which can require alot of extra development time, so I knew in some form it was in consideration from the start. Thanks for the Response as always Froox.

**Comment by WolfYears101** [comment]
I've been bothering lewis for proper matcap support for so long now

**Comment by RoxyBoxxy** [comment]
maybe we could introduce a new shader/material Poiyomi Toon Shader is good and has a MIT licence

**Comment by Elektrospy** [comment]
As much as i agree with getting something versatile like Poiyomi in terms of shaders,
trying to get the "full" features list of XSToon seems like a good start and more realistic right now, 
since the basic version of this shader has already been implemented.

Which following the discussion of the initial issue #428 and inside NeosVR, 
also seems to be desired by a lot of users.

The most requested features so far been:
- second uv channel
	- xstoon does support this for most of its texture inputs
	- this also allows you to have two lower res textures and without needing to bake to a much bigger single atlas just to keep all the smaller details intact
- matcap support
	- for xstoon this falls under the reflection category (the settings do change depending on the reflection mode chosen)
	- ![xstoon reflections options](https://cdn.discordapp.com/attachments/756597153161281657/796013233621827604/xstoon_reflections.png)

( for anyone interested, here is the most recent original xstoon shader documentation: https://docs.google.com/document/d/1xJ4PID_nwqVm_UCsO2c2gEdiEoWoCGeM_GDK_L8-aZE/edit )

**Comment by Frooxius** [comment]
@RoxyBoxxy I'm sorry, but Poiyomi shader won't be supported at any point. I've already investigated it in the past and unfortunately it clashes too much with Neos on technical level for us to reasonably support it. In short, it has too many featured all built in into its variants, which is not feasible to compile for Neos (it would surpass number of variants of all existing shaders several times over), meaning we'd have to severely reduce and modify it.

@Elektrospy Having full feature list won't unfortunately be possible either for similar reasons as above. I can include some extra features from it, but we need to be selective about which ones, because there's only so many extra ones that can be added, it's already a bit at the limit right now.


This issue was created for MatCap and color masking features in particular. I think including the Second UV channel is possible as well. Given the interest in those I'll investigate adding those features when I can, but please note that adding even more features to it will be even trickier, potentially not realistically possible anymore.

**Comment by Elektrospy** [comment]
`Having full feature list won't unfortunately be possible either for similar reasons as above.`
No problem froox, i used it more for comparison to adding the Poiyomi shader.

`please note that adding even more features to it will be even trickier, potentially not realistically possible anymore.`
That's also the reason why i selected the two most requested features since the xstoon shader was added. :wink:)

**Comment by Frooxius** [comment]
I've added the Matcap, ColorMask and secondary UV support in 2021.1.22.1352, hope it helps with more flexibility! Let me know if there are any issues with those, I normally don't use those features!

**Comment by StarfishHidari** [comment]
I think some mix up may have occurred when color masking was added in, I've spoken with a lot of people about this and it seems like what people were expecting when they asked for "color masking" was a grayscale color mask texture option, and a color field. Anything affected by the color mask texture would be tinted by the grayscale mask texture.

**Comment by Frooxius** [comment]
I see. That wasn't described in this topic, so I assumed it to be the same ColorMask functionality that other Neos material expose. I'd recommend making a new issue for that functionality.

**Comment by TehTurk** [comment]
I can remake the issue to make it clear, sorry it wasn't caught in the original discussion.
