### ISSUE TITLE
Values should cast when connected to a compatible field on an interface card

### ISSUE THREAD

**Issue by chemicalcrux** [Frooxius/NeosPublic#1541]
## Is your tweak request related to a problem? Please describe.
Values do not get auto-casted when plugged into a field of a compatible type. For example, a float output will not cast to int when plugged into a ValueField\<int\>'s Value field.

This was originally brought up by Enverex.

## Describe what would you like tweaked
Casting should occur automatically, as it would for connecting to the input of another field.

## Describe alternatives you've considered
An explicit cast is possible, of course, using an appropriate node.

You can also produce a cast by plugging into a compatible input, then connect the output of the cast to the field. Note that this does cause #1493 to rear its head if you delete one of the wires coming out of the cast!

## Additional context
None needed.

**Comment by Frooxius** [comment]
This is intentional. Any casting that leads to information loss always needs to be explicit so the user is aware that they're losing precision or possibly overflowing the values. This follows the rules of similar programming languages, like C#, where casting to a more flexible datatype is implicit (e.g. int -> float), but one that results in information loss needs to be explicit (float -> int). 

I recommend checking this documentation on C#, LogiX follows the same principles/philosophy: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/casting-and-type-conversions

**Comment by chemicalcrux** [comment]
That's fair, but it's inconsistent with the casting behavior you get when connecting to other LogiX nodes -- for example, plugging a float into a `^` node produces an automatic float->int cast.

Is there something unique about making a connection into an interface card that motivates this?
