### ISSUE TITLE
Ensure Single Instance option for DefaultUserScale

### ISSUE THREAD

**Issue by LeDrascol** [Frooxius/NeosPublic#1554]
DefaultUserScale is a small component that can be easily lost or forgotten on an avatar, and is often difficult or impossible to find. This issue has increased in prevalence with the popularity of the component on publicly distributed avatars.

The TextureThumbnailSource component solves this issue with a 'Ensure single thumbnail source' option, which removes all other instances of the component.

A replica of that functionality could be added to DefaultUserScale as a means of both reducing duplicates and easily eliminating the component when unwanted.

**Comment by TehTurk** [comment]
Generally I don't know if you want this being added, you'll get one component with it, then that'll mean every other component will get that as well too. Plus this issue isn't using the new templates so please use them in the future I've noticed you haven't used them for some and the point of adding them is to use them, because instead of focusing on the problem that seems to be presented which is "Finding a Lost or Forgotten Component" is the main reason instead of the request.

**Comment by LeDrascol** [comment]
Feature request is too specific, as described above.
