### ISSUE TITLE
Active Sync Button for Bhaptic Suits

### ISSUE THREAD

**Issue by Casoliv-Kuro** [Frooxius/NeosPublic#1556]
## Is your feature request related to a problem? Please describe.
Problem is that the BHaptic Vests have the Power On/Off button on their back. So if you sit down and lean onto the back of your chair they switch off. When switching them Back On i have to restart Neos VR. Because otherwise the Haptic Suit will not work anymore.

## Relevant issues
Just switching off the Suit and Switching it Back on while in Neos.

## Describe the solution you'd like
Maybe a Button in the Home menu that forces a resync of Neos and the Haptic Suit.

**Comment by Frooxius** [comment]
Hmm, this is a bit of an odd issue. Neos doesn't manage the linking with the suit on Windows, it only links with the bHaptics software, which then links to the suit. There's not really much I could do on Neos' end to do any sync like that, it sounds like the issue is somewhere else.

When you restart the suit again, does it show up in the bHaptic software on Windows? Can you send me a log file from when it disconnects?

**Comment by Casoliv-Kuro** [comment]
Hey, sorry for the late reply has been a very busy week. 

When i restart the suit again it does show up on the Bhaptics software and it is pingable. But in Noes it does not respond to any touching or triggers. I will do another test tonight and then upload the fresh log.

**Comment by Casoliv-Kuro** [comment]
So After some testing. The Problem lies within the Bhaptics Player App for the Desktop. Everytime it connects to the Vest it goes into Wired Audio only mode. Which Receives no inputs from the PC then. Weird that that is a starting thing with what my Vest starts each time. But if that is switched off it works fine in Neos again. 

Sorry took me so long, had not had that much time as of lately as I wished  I had for VR etc.

**Comment by shiftyscales** [comment]
Ah, interesting. Thanks for following up, @Casoliv-Kuro.
