### ISSUE TITLE
Component Deduplication Wizard

### ISSUE THREAD

**Issue by LeDrascol** [Frooxius/NeosPublic#1557]
## Describe the solution
Some components only function with a single instance, are difficult to locate for removal, or are accidentally added in excess of need. While some already include mechanisms to process duplicates, this behavior is not standardized and may be difficult or cumbersome to support in every case.

A possible method to handle this is a component deduplication wizard. This would display a list of all elligible components, with the options for 'Remove All' and 'Ensure Single Instance'. Only a predefined set of components could support this behavior.

Examples of existing behavior:
- TextureThumbnailSource: Has a function to remove duplicates
- SimpleAvatarProtection: Has a function to remove all instances

Examples of possible use cases:
- DefaultUserScale (#1554)
- LogixInterfaceProxy **component** (#1491)
- AvatarDestroyOnDequip

## Is your feature request related to a problem?
Yes. Described above.

## Relevant issues
Described above.

## Describe alternatives you've considered
None.

## Additional context
None.

**Comment by shiftyscales** [comment]
It sounds to me like the underlying issue is more in finding the location of particular components in the hierarchy, which is something that has been discussed in/would be covered by other issues such as #208.

"Component Deduplication" seems like a very niche thing to have as a 'wizard' and the only real reason for the existance of the wizards is in the ease of helping otherwise time-consuming workflows in the absense of more general tooling that would make it easier to find/change the properties on numerous components in a hierarchy simultaneously.

I don't think this is something that should be considered or implemented because it is something that will be solved by developing proper systems down the line to more easily manage components across an entire hierarchy, and it also only serves to fix a problem that ideally wouldn't come up in the first place, e.g. multiple copies of the DefaultUserScale component that could be better managed if the person creating the avatar organized their own hierarchy.

E.g. in my case, I always have a slot called 'Components' at the root of my avatar where I store most custom things, like added components, etc.

**Comment by LeDrascol** [comment]
Users cannot be expected to be responsible with their component setups, or remember where unwanted or duplicate components have been placed. A large amount of public avatars and objects are set up with unwanted or lost components that must be manually located through trial and error. Repeatedly removing LogixInterfaceProxy **components** is the definition of time-consuming.

Systems like this already exist on some components, but is not yet a standard behaivor. Given that some support does exist, it is safe to assume that this beavior is expected to happen but has been overlooked for these cases.

Issue #208 appears to be unrelated. Collapsable components and paged inspectors would not make finding and removing unwanted components easier.

**Comment by SnooperXP** [comment]
I think what was being refered to in #208 that matches the feature you're asking for here is the second part of the initial issue which states:
> Next to this it would be great if the inspector features a search field where you could search the DataTree and components.

It appears as though this is already planned and would be the solution to the duplicated components in the tree that you seem to reference.

Also it appears you specifically are focusing on a woe with the LogixInterfaceProxy, but I think that issue was already raised by you in #1491 and was marked as Won't Fix/Implement.

Failing this, once component access becomes available it should also be viable to create specific tools towards this end. As such, I will close this issue and mark as duplicate.
