### ISSUE TITLE
Pass mutiple values into Dynamic Impulse reciever/trigger

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#1583]
## Is your feature request related to a problem? Please describe.
It would be very useful to have multiple parameters for passing around between functions when utilizing dynamic impulse nodes. I find I'm constantly wanting to pass an arbitrary number of variables to send along for more reusable functions.

For instance, just passing 1 variable to a string parsing function which then stores the result allows me to create a function that I can pass the string to parse. But It would be useful to pass along another variable in this instance that I could use to determine where to save that result.

## Relevant issues
Possibly #860 

## Describe the solution you'd like
Dynamic Impulse Trigger and Dynamic Impulse Receiver would each have a "+" (plus sign) that allowed you to create more variable receivers. These would directly correlate to what is passed (i.e. the first variable passed would be variable 1 on both nodes, var2 on the Trigger would be var2 on the Receiver).

Types would be perhaps per node (all variables string for instance on a Dynamic Variable Trigger with a type string). Though it would be great if there were a good way to have types per var.

## Describe alternatives you've considered
The only alternative I've found thus far is duplicating the Logix and having just one different node, sometimes the same node with just a different name parameter (in the case when I'm saving to a Dynamic Variable, for instance, the only thing different is the name string passed to it).

## Additional context
There was a somewhat relevant question asked by Alex from Alaska back in July here:
https://discord.com/channels/402159838827905024/533553295956901918/734554335035523152

**Comment by sirkitree** [comment]
Sorry hit enter too quick. Wil, fill t hi is out properly

**Comment by Toxic-Cookie** [comment]
Gonna toss this an upvote. This would be a game changer for projects. It probably requires collections beforehand though.

**Comment by Frooxius** [comment]
This will be implicitly handled by Collections, you'll just pass a collection of values as an input, so a separate issue isn't needed for this.

One approach is to have ability to define some equivalent of static "structs/classes", but that's a whole issue on its own as well.

**Comment by sirkitree** [comment]
LOL, a response before I even finish filling it out. OK, thanks @Frooxius ! :)

**Comment by sirkitree** [comment]
One thing I'll note: Collections feels like it's a long ways off, while adding a + to the existing nodes might be a quick solution until then? We could use it now quite honestly.

**Comment by Frooxius** [comment]
I'm sorry, but I can't really add quick hacks to LogiX like that, because that means they would have to be supported forever, or else we'd break everything that uses those to break them.

The hacks themselves often end up costing way more time down the line than a proper solution would anyway, due to all the problems, bugs and weird behaviors they cause with their behavior.

I think collections aren't that far off now, I know what exactly I need to do to support them (the new LogiX validation system) properly. I could look into introducing them partially ahead of time too, without temporary storage support too.

**Comment by Earthmark** [comment]
Does this include some kind of structure validation? Verifying that an object has some subset of fields?

For full transparency my brain thinks of typescript with this, but would structural validation be part of this addition with collections?

**Comment by Frooxius** [comment]
That would be the struct/class part, which is almost like defining a new "fixed" datatype, but that's a bit more complicated, I'm not fully sure  yet how we'd define and implement those. There's lots of ways to go about it, but it's also going to be dictated by some future changes to LogiX that aren't locked in yet.

Collections are dynamic, so that'll be up to you to make sure to include all the right data and handle cases when it's not present.

**Comment by Earthmark** [comment]
Exactly what I wanted to know, thanks!
