### ISSUE TITLE
Generate Rig Analysis Import Option

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#1591]
## Is your tweak request related to a problem? Please describe.
@chemicalcrux has been having an issue with the Rig Analysis windows when importing certain rigged models, a model file with 67 armatures with 5-13 bones each creating a report for each armature, thousands of lines of text total. Before that it was hundreds of thousands of lines as the FBX had name collisions, which generated a rig analysis report for every single bone.

## Describe what would you like tweaked
A checkbox added to the advanced import dialog to generate the rig analysis report(s) (defaults true).

## Describe alternatives you've considered
Chemicalcrux tried to delete the rig analysis reports as soon as they appeared with logix, however this broke the loading spinner, which just got stuck and never disappeared. Another solution would be to not create import reports for multiple armatures or armatures that lack a minimum number of bones or have the wrong structure to even be considered humanoid, but I could see the heuristics for that getting messy and breaking some workflows.

**Comment by chemicalcrux** [comment]
Some extra details about the import report size:

My original structure was:

```
- empty 
-- armature0
--- root (with four children)
-- armature1
--- root (with four children)
```

The resulting import report identified the root bone under armature0 as an armature, and listed its children. However, it then listed *each child of every bone named "root"* as a separate armature.

I believe this is a problem with duplicate names in FBX files, as I've run into an identical issue before.

Since every armature winds up listing every single bone in the entire model, this produced a 113,000 line file for model with ~450 bones and 67 armatures 

I then corrected my model:

```
- empty 
-- armature0
--- root0 (with four children)
-- armature1
--- root1 (with four children)
```

It now correctly identifies the 67 armatures. However, since each armature lists every bone in the model, this still produces a very large import report.

If this behavior is intended, then adding a toggle for the import report would be much appreciated. If this is *not* intentional, then I can open a separate issue for that.

**Comment by Frooxius** [comment]
In 2021.1.17.998 disabling the Setup IK will now prevent the diagnostic from being spawned which should solve the issue. Thanks!
