### ISSUE TITLE
Theoretical Request: Discord Links to Shared Folders

### ISSUE THREAD

**Issue by GearBell** [Frooxius/NeosPublic#1614]
If the creator feels compfortable enough, imagine a feature where you have a public folder and can create a link to that folder - for instance, in the Neos Vehicle Enthusiats folder there are many vehicle contributors who have thier own folders of vehicles. What if while in Neos you can Create Link, post the link to that folder in discord and it makes a reference, then people can copy that link, go into neos and paste it to create a folder reference, you then grab the reference then save it into your inventory and it becomes that shared folder?
A Create Folder Link would be useful in many sharing cases.

**Comment by 3x1t-5tyl3** [comment]
I think further extension into a "Place folder infront of face" when the link gets clicked on?

Though some security concerns may pop up. Still felt like this would make it actually usefull. :P

**Comment by Frooxius** [comment]
It's possible to just create a general link that would get imported as inventory link into Neos and can be shareable outside, rather than something that's specific to Discord.

However the main question would be what would be the workflow to getting this URL. I don't really want to build any new complex UI for the old inventory, so it might wait until a new one is built instead.

**Comment by chemicalcrux** [comment]
If it should only work for public folders, then a context menu option when holding a folder link to copy a link would be reasonable.

**Comment by Frooxius** [comment]
Ah that would work! Thanks!

**Comment by Frooxius** [comment]
This was quite simple to add, I've added this in 2021.1.21.1068. Just grab the inventory link item, open context menu and go "Copy Link". It'll put URL into your clipboard that you can then just copy and paste back into Neos. Thanks!
