### ISSUE TITLE
CultureInfo has an implicit cast to User

### ISSUE THREAD

**Issue by Psychpsyo** [Frooxius/NeosPublic#1624]
## Is your tweak request related to a problem? Please describe.
When connecting a CultureInfo output to something that expects a user, Neos automatically creates the CultureInfo to User cast node. This makes it seem like this cast does something but it seems like the resulting user is always null.

## Describe what would you like tweaked
Remove the cast to avoid confusion.

## Describe alternatives you've considered
Keeping a useless cast.

**Comment by Earthmark** [comment]
Can this be renamed as "Disallow creation of cast nodes that can never exist as defined by the type system"? This would cover the more general case of when two classes inherit from different hierarchies, as no duplicate class inheritance in C#. There's a number of times where this would still semantically be incorrect, but at least it'll resolve this particular case (and related concrete type casts).

**Comment by Frooxius** [comment]
The cast itself cannot be removed, because it's handled by a generic one. Removing it would remove all non-primitive casts altogether.

It's possible to prevent the cast from being automatically created, but it's a fair bit tricky, as it's only applicable in some scenarios. Some of the casts will result in null with some inputs, but not with others, as the ability to cast them is determined at runtime, so that needs to be preserved. 

Preventing casts from one specific type to another is possible, but just requires some extra code to resolve that at runtime. I'll see when I can prioritize that, but it'll be probably low priority since this is just a confusion issue.

**Comment by Frooxius** [comment]
Should be fixed in 2021.1.21.1068!
