### ISSUE TITLE
Separate Essentials Assets From Displayed File Sizes

### ISSUE THREAD

**Issue by LeDrascol** [Frooxius/NeosPublic#1637]
## Describe the problem
Currently, saved items display the total size of all assets, including those not counted against storage. With the changes to shaders being counted as an asset, existing objects are increased by alarming amounts.

This is confusing and misleading, as object and avatar sizes can no longer be accurately determined, and users mistakenly think an avatar is much larger than it is. The issue is compounded by older avatars now showing file size increases of ten times or more.

## Describe the solution and alternatives
A non-exaustive list of different potential solutions:
- Completely remove 'free' assets from displayed file sizes
- Completely remove shader sizes from displayed file sizes
- Display two file sizes, with unique and 'free' assets separately

## Relevant issues
Content stats (#297) UI could be used for this.

**Comment by shiftyscales** [comment]
> No, that's complicated unfortunately.
Yeah there's deduplication and other things going on that make the storage usage shown in the inventory misleading at best. Usually the size you see isn't even the size you download, because Neos will load variants of the assets.
When showing the size was originally requests I warned about these kinds of side effects, but it was a demanded feature anyway. I'm not sure if I should just remove it or keep it for now.
> 
> With reworked inventory UI I'd like it to instead generate and show more detailed analysis of the objects - how many textures and how much resolution it has, how many vertices, objects, components and so on.
Those are a lot more useful metrics than the raw size of its referenced assets.
> 
> Yeah it was from the beginning. Like I said, I warned about its misleading nature, but it was demanded anyway.
Until the UI is reworked and more detailed info can be shown, it's going to be what it is.

Frooxius discussed this matter in the DIscord earlier today. The immediate option is to remove the display of the size outright, otherwise, no work will be done in this area until the inventory UI is reworked.

If you wish to rework/rewrite this issue to be about removing the feature outright, or displaying other metrics (down the line when the inventory is reworked) that can be done, otherwise, this issue will be closed as `Won't Fix/Implement`.

**Comment by Frooxius** [comment]
Sorry, but this is not possible, the information to do this is simply not there in the metadata. When this feature was originally requested, I warned that it's going to be misleading and count other stuff as well, but also doesn't show the actual download sizes, since the asset variant system will download optimized versions based on user's hardware. With the recent changes, I can just remove it so it's not shown in the first place if people would prefer.

Doing this properly requires the #297 to actually generate proper statistics and the inventory UI to be reworked to display it.

**Comment by shiftyscales** [comment]
It does seem to cause a lot of confusion, so its removal would probably be beneficial for now, @Frooxius.

**Comment by LeDrascol** [comment]
Any solution that can either reduce end user confusion or provide a more accurate description can be considered a valid solution to the current problem, even if not listed in the original post.

I cannot speak for the community's interest in removal of object size displays, but a complete removal of all information could be considered a regression. In such a situation, concealing the information without removing it completely would be preferable if possible.

The inability to determine the size of any object could act as a hindrance to inventory management for users with limited storage space.

**Comment by TehTurk** [comment]
So Ideally would it be better to have a move easier list of what's counted to your cloud storage? That seems to be the original problem. I'm for it's removal but then people don't "know" what's counted to cloud storage so it's a rock and a hard place. I'm aware of the JSON Record request, but is there an easier way for users to look at what's on their account?

**Comment by Frooxius** [comment]
For storage space you want to use the analysis tool anyways. That was one of the points too when this feature was originally added - this is going to be misleading for that, as Neos deduplicates assets. So even if you had item that has 100 MB of your own assets, deleting it might not free up 100 MB of of your storage, because the assets are still used by other items.

I don't plan on making too many changes to the old inventory UI, so this might just need to wait until it's reworked then, with it being misleading in the meanwhile.

The JSON/report is currently the primary way to get a good idea on what to remove first. Inventory isn't best way anyways, because some things don't show there like worlds. We often deal with cases where users don't know what to remove from inventory and are confused what's taking up space, only to discover they saved a copy of a large world through generating that report.

**Comment by uyjulian** [comment]
The following exists to visualize the JSON record: https://earthmark.github.io/neos/inventory-plotter.html  

#297 is most likely going to be the issue to improve the handling of object size metadata

**Comment by Frooxius** [comment]
I've made change in 2021.1.29.504 that prevents shaders from being saved at all and instead the references/providers are regenerated every time. As a side effect this fixes the size bloat issue, so I'm going to close this.

Please keep in mind that the number shown is still now quite accurate representation and it includes other assets as well and raw data, rather than the data that will be actually loaded. 

For better stats https://github.com/Frooxius/NeosPublic/issues/297 will be implemented in the future.
