### ISSUE TITLE
User space objects become ungrabbable when physically grabbing in-session.

### ISSUE THREAD

**Issue by Psychpsyo** [Frooxius/NeosPublic#1656]
## Is your tweak request related to a problem? Please describe.
Things in user space become ungrabbable with laser grab if something in the current session is close enough to be physically grabbed.

## Describe what would you like tweaked
Make it lasergrab the user space object (most of the time this would be the dash) even if something outside of user space is able to be physically grabbed, as the current behavior allows anyone to spawn a massive collider to make other peoples dash ungrabbable.

## Describe alternatives you've considered
Keeping it as is and leaving the option to abuse this.

## Additional context
I noticed this because someone made a huge grabbable collider on accident and it took us a while to figure out why my dash wasn't grabbable.

**Comment by AshtonSparx** [comment]
I'd like to mention, it would be nice if your user space had priority over world space regardless of what you're trying to do in it. So even if someone was standing in your dash, your laser should work through them. If this could be an issue, an alternative would be an option to toggle something like "Userspace prioritized over world space" or a similar/shorter naming scheme. 

So if you desired, if your dash is infront of you. You can't interact with items, unless it was something you're looking at (let's say you're trying to save an item, how would you save it with this turned on?) 

Also wish your dash could render over users so people walking in front of you while you're in your dash could stop being an issue.

**Comment by Frooxius** [comment]
This behavior is intentional. Originally the dash behaved this way and always took priority, but this was met with poor reception from many users, as it made a lot of interactions really confusing (e.g. you spawn out something out of the inventory, but you can't interact with it until you close your dash, even though it's right in front of you).

We had some discussion on that over here already: https://github.com/Frooxius/NeosPublic/issues/500

Currently proposed solution is to have element of your dash that will toggle it into a full overlay, making it render on top of everything and taking priority for all interactions when active. This will let you recover "lost control" in such cases as well as deal with things in the world obscuring your dash and such, while maintaining the more fluent interaction in most cases.

I recommend continuing discussion in the issue above, marking this one as duplicate as it essentially deals with the same problem. If it's something that you see actively abused or very commonly be a problem let me know and I'll see if I can prioritize work towards this feature.
