### ISSUE TITLE
The SimpleViveBasePositioner component does nothing.

### ISSUE THREAD

**Issue by Psychpsyo** [Frooxius/NeosPublic#1657]
## Describe the bug
The SimpleViveBasePositioner component does nothing.

## To Reproduce
1. Add a SimpleViveBasePositioner to something. (Input -> Utility)
2. Give it a user and two slots.
3. Nothing happens.

## Expected behavior
I assume it's supposed to position the two slots at where the users base stations are.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: Beta 2021.1.24.1327
 - Neos Platform: Probably any, I am on Windows
 - Regression: Not sure but it probably did work at some point.

## Reporters:
Cameron#7818

**Comment by shiftyscales** [comment]
This is reportedly a really old component. @Frooxius used to use it at events as a ways to align playspaces when there were multiple systems (e.g. at public events.)

Did you have any specific uses you were hoping to use this component for @Psychpsyo ? I'm wondering if it might be okay to remove it outright?

**Comment by Psychpsyo** [comment]
Apart from it being kinda neat I have no use for it, no. I'd be fine with it being removed.

**Comment by Aerizeon** [comment]
It would be pretty neat to have the reference positions for base stations though, even if not very practical :3

**Comment by Frooxius** [comment]
Yeah this is an old deprecated component, I'm going to remove it in the next build. A lot of things have changed since it was implemented, from the SteamVR Input system, to hardware devices. This was hardcoded specifically for the original Vive with two base stations.

If you want, you could request a more general component to show tracking references (although it'll probably be low priority), but I don't plan on reworking this one specifically.

**Comment by Frooxius** [comment]
Forgot to close this, was removed in 2021.1.26.1308.
