### ISSUE TITLE
Add option to change audioclip format

### ISSUE THREAD

**Issue by Toxic-Cookie** [Frooxius/NeosPublic#1698]
## Is your feature request related to a problem? Please describe.
You currently are not able to convert audio formats in the game.

## Relevant issues
Didn't find any.

## Describe the solution you'd like
It would be nice to be able to inspect an audio clip and convert it to a different format. eg. from ogg to wav. Not sure if converting from video formats to audio formats would be possible but would be quite handy. Especially in the case of mp3 to some other format.

## Describe alternatives you've considered
Converting using tools outside the game works but is inconvenient.

## Additional context
None.

**Comment by Frooxius** [comment]
This is already supported, you need to go to the StaticAudioClip and you'll have conversion options at the bottom for all supported formats: 
![image](https://user-images.githubusercontent.com/8838625/106550066-af4fee80-6512-11eb-957d-9d3b16bd6761.png)

**Comment by Toxic-Cookie** [comment]
I must be blind. I have no idea how I missed that. Video formats and MP3 having the conversation options would be cool though if they don't already.

**Comment by Frooxius** [comment]
Video/multimedia are handled differently from audio clips, so that's trickier. It could potentially be added as some point, but that gets a lot more complex, so won't likely happen soon. Currently it's only supported for audio formats that Neos supports reading natively and it can encode only to WAV, OGG Vorbis and FLAC.

There's a hacky way to do MP3 by pasting the URL of it to audio clip, but it might produce noise or corrupt output as the native MP3 decoder is buggy.
