### ISSUE TITLE
Limitations on Patreon Custom Icon Badges and Custom 3D Badges

### ISSUE THREAD

**Issue by Aerizeon** [Frooxius/NeosPublic#1717]
## Where have you searched for this information before making this issue?
This information is informally available in the community, however I was unable to find an official and complete source of information **(from Frooxius or Karel)**

## Which part of the system do you need information on?
Custom 2D Badges
Custom 3D Badges

## What information do you need to know?
Limits on the Custom 2D Badge:

- Resolution
- File size
- Texture format
- Texture settings (FilterMode, WrapMode, Uncompressed, etc.)
- Material settings (Cutout/Transparent/Additive/etc)
- Physical Size
- Any other un-listed limits

Limits on the Custom 3D Badge:
- Vertex Count/Triangle Count
- Material Count
- Material Types
- Effects limit (Emissive lighting, blur, etc)
- Physical size
- Texture Count
- Texture Size(s)
- Texture settings (FilterMode, WrapMode, Uncompressed, etc.)
- Any other un-listed limits

Are there any cases where a user can request more than one of either (or both)?

## Do you plan to format and contribute the provided information to Wiki?
Yes, this is part of a larger effort to document the features of various Patreon tiers

**Comment by ProbablePrime** [comment]
I know some of this:

2D Badge:
Dimensions: 128x128 pixels
Material: Limited to the same material as other icons, Unlit. No changes allowed.

**Comment by Aerizeon** [comment]
The purpose of this request is to get an official answer :P

**Comment by Frooxius** [comment]
Custom 2D Badge:
- You supply a single 128x128 image file (if it's larger we downscale it to that resolution), any common image format will work, PNG preferred.
- You can request for it to use point filtering (some places will still use bilinear due to automatic atlasing)
- Rest of the settings you don't have control over, they're default Unlit material right now
- It should be something you have rights to use and is ok to be shown in public (same as general guidelines for public content)

Custom 3D Badge:
- Max 100 triangles, static mesh, no skinned mesh allowed
- Max 1 128x128 texture. It can be used in any/multiple material slots
- Texture should be compressed (no raw RGBA), no HDR. Point filtering or Bilinear (will use higher filtering in the future once the settings are per-platform)
- Max 1 material
- Generally most materials are OK to use, except ones with grab pass (filters, refract...). It should be non-obnoxious (if you make it glow excessively we might ask you to change it)
- You can have simple transform drivers on it (e.g. spinner, wobbler). Anything more complex than that we'll likely reject
- Physical size is meaningless, it'll be auto-fitted to the standard badge size
- Same content guidelines as above

**Comment by Aerizeon** [comment]
Thank you!

**Comment by Aerizeon** [comment]
Information was originally added to wiki on the Patreon page, but has since been moved to the [Bages](https://wiki.neos.com/Badges#Custom_Badges) page.
