### ISSUE TITLE
UIX + Material RenderOffset,Masking, OffsetOrder

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#1737]
## Where have you searched for this information before making this issue?
I was talking to Ryuvi about this issue and wanted to get some more information. Even he himself kinda wish there was more information, or an easier solution to a Dilemma of "How do I make my UIX Panel Solid, and not have any alpha whatsoever"

## Which part of the system do you need information on?
I was hoping to make get a better underlying idea of how UIX and Material Offset Orders are conveyed to have an easier time of trying to set up UIX panel without issues. If you set the default offset from -32000 to 0, you have a completely solid Canvas, but you then run into issues with Masking. I'd like for the information to be verbose as possible so I may be able to figure out a solid solution for myself.

## What information do you need to know?
-MaterialOffset Ranges
-UIX Render Offset Ranges
-Masking Ranges
-Other Information I may not be too keen on regarding this topic. 

## Do you plan to format and contribute the provided information to Wiki?
Yes

**Comment by Frooxius** [comment]
If you want to have solid UIX Panel, put an image with ZWrite at the bottom so it blocks all the stuff behind it.

You should never touch MaterialOffset, UIX Render Offset or MaskingRange, they're internally managed. If you do, stuff will likely break.

**Comment by TehTurk** [comment]
Thanks Froox I'm aware that's a current fix, but I remember my tests with ZWrite being unfruitful so I'll have to look again and see.

But the point of asking is to get more information as even if they are internally managed. They can be still adjusted and used and I see them used regularly.

Understanding what's happening is key so that others can know why not to touch them, or if they have benefit they can be used in a responsible format.
The idea was to also put the resources for the Wiki for others to refer.

**Comment by Frooxius** [comment]
I'd recommend taking apart some Neos' UI and check how that's constructed. Typically you put Image component at the topmost part of the canvas using a custom UI Unlit Material, with ZWrite On and OffsetFactor and OffsetUnits set to 1.

You should not be changing those values at all, the stuff **will* break if you do. Some of them get ignored anyways and over-written with UIX managed values to ensure proper rendering.

Those values are used to ensure proper rendering order of the UI elements in the limitations of the current rendering pipeline and will likely change once we have our own sometime in the future.

Each generated UIX graphic chunk gets assigned an incremented sorting offset based on the order they're supposed to be drawn. This is all happening within the 3000 (Transparent) rendering queue. Generation and ordering of UIX graphic chunks is internal to UIX and can change too, the way to properly interact with the system is through adding the UIX graphic components and such.

The masking is for writing to stencil buffer, which is used to achieve the masking effect when rendering UIX elements in the proper order. You can have up to 7-8 nested levels of masking. The only time those properties are changed is when using NestedCanvas, which is to ensure that the nested canvas renders and masks within the parent one. If you change those properties and then use your Canvas as a facet, they will get overwritten and likely mess up your rendering.

Whatever you're trying to do, it should be done through other ways rather than changing those.

**Comment by TehTurk** [comment]
I always have, if it seemed like I hadn't I apologize, even learning from examples it isn't always clearcut. I just wanted to kinda get some info out there on it and understand why some stuff might behave the way it does.

Hmm okay, so it's a bit of an inbetween not having everything kinda fleshed out in that capacity on top of a mix between actually RenderOffset and how UIX Handles the Rendering internally. Some of this information is good to know and I can throw some stuff on wiki. Ah I'm not trying to do anything specifically, just more so a question of is there easier ways or information I'm missing.

To kinda close, then is there like a chart or like a break down of how it all gets layered? I was hoping to make a visual aid or having something for those who are more fledging in their endeavours in this area or things..
How does Stencil Buffer kinda fit into all this?(Is it Masking only?) I'm aware of stuff like Depth, Z, and now Stencil Buffer, I assume these are similar or get layered in a certain way for render techniques/tricks. And how the Image Data is being treated/handled.

**Comment by Frooxius** [comment]
I don't mean to suggest that you don't or not, just mentioning that to be sure!

And yes, part of how it works is due to the limitations of current rendering pipeline, since we have to work within its constraints. 

The internal stuff is pretty complex and can change at any time, it's not really something that anyone should be concerned with, you should only interact within the high level components provided to you and their behaviors and guarantees. If you start exploiting some quirks of the internal implementation, your things will likely break at some point, we don't guarantee that those will stay the same.

Stencil Buffer is used specifically for masking. UIX takes control of the stencil buffer parameters on the UI materials to ensure that it's written to and read from properly to ensure the elements are properly masked. Again the way this is achieved is internal and not something you should touch - use the Mask component and the system will do this for you.

I'm not sure what do you mean bv Image Data being treated?

**Comment by TehTurk** [comment]
Ahh, I think there was miscommunication sorry. For that final blurb I wanted to fill out the aspect of how those properties aftect Materials. (Not UIX), UIX was the original inspiration for the question, but it was generally more aimed at how every thing kinda comes together in terms of Rendering, Queue, Offset, etc. I can understand if some of the RenderQueue around UIX is a little fragile atm untill more is added. Maybe the Title wasn't the most clear as I did UIX + Material, but I wanted to just have a better flesh out of how a user can use the current System, and know what works, doesn't, and the info one should know. And don't worry about complex topics!(Please D: I like the complex things) I'm asking for that kinda stuff to kinda simplify it for others.

I know when an image is being rendered onto your screen there's usually a couple of different steps, and I assume Depth, Z, And Stencil are similar in nature? Couple cursory google searches lead me to believe this, but the step at which one is used or how they lay on top of one another is another thing.

Say if a user wants a Visual Effect, knowing aspects of these can be kinda key.

**Comment by TehTurk** [comment]
Hmm I understand. I think this is enough for Documentation and if I find anything else that I need to fill out I'll reopen a different one that's a bit more clear or specific on the info I need.
