### ISSUE TITLE
Dynamic*VariableDriver/DynamicVariableInput try harder to find a value matching their criteria

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#1739]
## Is your feature request related to a problem? Please describe.
I want to make meta languages on top of logix, built around assembling physical objects.
One of the goals would be the system is able to tolerate updating gracefully, allowing the 'blocks' of the language to be just as viable as the systems evolve over time and new variables and blocks are added (and new dynamic variables are added)

To support this I have each block contains DynamicDriver components that route data values from the previous block into an expression and then into a DynamicVariable component inside a sub-DynamicVariableSpace. A snapper is a child of this space, so child modules are attached to this snapper to get linked together (this makes any child modules see the modified value, instead of the parent value, AKA: Overriding).

This works fairly well, here is an example of such a module system where the relays between each ball are receiving a color from the previous layer, and rebroadcasting a modified color to the next layer. New balls can be added at any time, and they magically link together and 'just work'
![image](https://user-images.githubusercontent.com/1251609/107596271-0e28fe00-6bcc-11eb-8d4a-7c96d782595f.png)

However, there is a problem. If a module does not broadcast _every_ value also broadcast by its parent, child modules that may depend on un-overridden values don't see the value at all, as they hit their parent's variable space and give up, saying the variable isn't bound.

See this example, where the middle black ball has had it's input and output nodes deleted, simulating a node that would affect unrelated variables or an additive API based change. Child modules of the disconnected module are also black, as their driver inputs did not find the values provided by the parent of the disconnected node.
![image](https://user-images.githubusercontent.com/1251609/107596402-7972d000-6bcc-11eb-8b2b-c085b6f80b70.png)
This is simulating module updates over time, where newer modules may have access to additional variables, but older modules would not be written to rebroadcast those values, because they didn't exist at the time. Any new modules placed under older modules would not work properly. This makes modular block systems built in this way a bit of a maintenance nightmare.

## Relevant issues
None found.

## Describe the solution you'd like
DynamicVariableDriver and DynamicVariableInputs will scan upwards through dynamic variable spaces until they find the provided value as well as a namespace match, instead of only a namespace match (I am counting non-direct bound values running into a namespace with OnlyDirectBinding set to false as a namespace match).

The assumption is also if a space closer (as in a less grand grandparent) to the driver/input suddenly provides a value, the driver/input would rebind to that closer value.

## Describe alternatives you've considered

Each variable is bound to it's own dynamic variable space - this feels really skuzzy, and would require a lot of variable spaces for some projects.

Variables all under one space, that dynamically rename themselves. - This is complex, and I can see it being very error prone. It would also require quite a bit of logic to run, even though that logic is only needed for a fraction of the total runtime.

## Additional context
Images were inlined. I can provide more concrete examples of systems I had planned that used this pattern.
To be honest I had assumed this was how dynamic variable spaces worked from the get-go... I only recently decided to test if my assumption was true, and it was not!

**Comment by Frooxius** [comment]
I'm not sure if this is something that could be feasibly added, as it goes against the design of the dynamic variable system. There is no "search" for the variable with given name. The dynamic variable space is found first and then the variable is linked there. There's no concept of the space "providing" a value, the system just synchronizes values based on a name.

Part of the reason is that with this design, the system can be very efficient, as it doesn't need to do constant searches and checks. The linking could only change when the name of the space is changed (note that it's very expensive to do so) or the hierarchy changes, which hooks up to the hierarchy events (which are also very efficient).

Doing this would break that efficiency, causing the system use significantly more performance across the board.

It would be better to find a different solution for what you're doing, rather than abusing the dynamic variable system for something it wasn't designed for. I do have some plans for physical "linking" of references and values like that which could potentially serve here, but I'll have to think more about those.

**Comment by Earthmark** [comment]
Interesting and good to know, I'll ponder different approaches. Thanks for the clear answer and helping me understand what the system is going for!

Hope ya have a good one.
