### ISSUE TITLE
Secure WebSockets fail to connect

### ISSUE THREAD

**Issue by ty802** [Frooxius/NeosPublic#1755]
## Describe the bug
Secure WebSockets disconnect on Connection attempt
## To Reproduce
Attempt to Use the WebSocketServer Component to Connect to a Secure WebSocket (wss://)
## Expected behavior
WebsocketServer successfully connects to the Secure WebSocket

## Screenshots / Video
Insecure Neos (Working)
![2021-02-15 22 47 34](https://user-images.githubusercontent.com/31832680/108020377-e11c8700-6fe1-11eb-9aff-0d87cdb7b855.jpg)
Secure Neos (BUG!!!)
![2021-02-15 22 47 01](https://user-images.githubusercontent.com/31832680/108020548-3789c580-6fe2-11eb-92a2-71d0cc5bd541.jpg)
Secure Firefox (Working)
![firefox_aBt4vAXRQc](https://user-images.githubusercontent.com/31832680/108020625-62741980-6fe2-11eb-9552-fd17b3507dcc.png)
## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.7.1345
 - Neos Platform: Windows
 - Link to reproduction World/Item:   ```neosdb:///3747b8743220ba4c66d95586e36338928979a2b58e67deee355d3ddcfac0fa14.7zbson```
 - Regression: No
## Reporters:
Techy89 : techy#1020
runtime : zkxs#1039

**Comment by Aerizeon** [comment]
I tested the issue using WebsocketSharp in a different application - the problem seems to be that, out of the box, WebsocketSharp only has support for SSL3 and TLS1.0 enabled.

Adding `System.Security.Authentication.SslProtocols.Tls12` to `websocket.SslConfiguration.EnabledSslProtocols` resolves the issue, and it connects to the two demonstration servers I was given (one displayed here, and one from @mralext20)

Presumably, if SSL3 support is desired, `websocket.SslConfiguration.EnabledSslProtocols`  should be set to `SslProtocols.Ssl3 | SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12`

**Comment by Frooxius** [comment]
@Aerizeon Thanks for looking into this, I've made the change in 2021.2.22.855, which should fix the issue!
