### ISSUE TITLE
Please explain the mysteries of LayoutElement.

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#1756]
## Where have you searched for this information before making this issue?
- Discord
- My Own Videos
- The Neos JP Wiki - They seem to have information here but the translation is making it a little unclear(https://neosvrjp.memo.wiki/d/UIX#content_2_5_22)
- The Official Wiki

## Which part of the system do you need information on?
LayoutElement and layouting in particular.

## What information do you need to know?
- How the different width & height properties lead to an overall Rect size within a layout?
- What Area and Priority do?
- What "Use Zero Metrics" does?

## Do you plan to format and contribute the provided information to Wiki?
Yes, I was also about to make a video on these too but then realized that I basically edited them somewhat randomly until I got the layout I wanted. Here's the WIP article: https://wiki.neos.com/LayoutElement_(Component)

**Comment by Frooxius** [comment]
When UIX does layout (e.g. using VerticalLayout or HorizontalLayout) it needs to know how big the elements it's arranging should be. There are three main metrics for this:

- MinSize - this is the minimum size, the element shouldn't ever be smaller than this, even if it causes overflow
- PreferredSize - this is element's optimal size that it ideally wants to be. If there's enough space, it'll be this size, if there's not it'll be anywhere between MinSize and PreferredSize depending on the available space
- FlexibleSize - if there's still space left even after awarding all Preferred sizes to all elements, any elements with this property larger than zero will be used to fill in the remaining space, with this value serving as a weight when distributing the remaining free space

Certain elements provide those properties implicitly. For example Text will calculate its width and height and provide those as appropriate properties based on its contents. The layout elements (e.g. Horizontal/Vertical/Grid layouts) will do this as well based on the elements they contain - if Vertical Layout has 10 elements, each with 32 minimum size, its own minimum size will be 320. If you add padding/spacing it'll add to that as well.

Elements that don't provide implicit size metrics will assume for them all to be undefined (zero, meaning they'll shrink to nothing unless forced to expand).

The LayoutElement component specifically serves to provide/override the metrics of given element, letting you provide your own values, rather than using the metrics implicitly provided by the child elements.

The Priority field is used when there are multiple metric sources on an element. For example if you have Text component on a Slot, it already provides metrics. If you want to override those by attaching LayoutElement, it needs to have higher priority so those metrics get used instead. This is why default Priority is 1 on this.

Area currently doesn't do anything much, it was added for future to provide metrics for layouts that do both horizontal and vertical layout simultaneously.

Use Zero Metrics will ensure that metrics get overriden even if the value is set to 0. Without this, the value will be ignored. Meaning this allows you to force element to act as if it wants the given metric to be zero.

I hope that explains it, let me know if you need any more clarifications!

**Comment by ProbablePrime** [comment]
This is great thank you! 

A few questions, I'll also be re-reading this a few times today to double check so there may be more.

> This is why default Priority is 1 on this.
So, by default the priority on Non-"LayoutElement" components (Such as Text) is 0?

Oh and -1, the default value in all LayoutElement fields means use other providers for dimension calculations(such as text etc contained)?

**Comment by Frooxius** [comment]
Yes, default priority for other elements is 0. Using negative value will always make that metric "pass-through", meaning one with lower priority will get used instead (or 0 if there's nothing with lower priority).

**Comment by ProbablePrime** [comment]
Thanks again, I tried this new knowledge out. The only confusion was the units.

Min & Preferred appear to be Pixels in terms of units.
Flexible however appears to be a ratio/percentage(similar to Rect Anchors).

Is this correct?

**Comment by Frooxius** [comment]
Min/Preferred aren't specifically pixels, but they're the same units as everything else in the world. E.g. if you have 1024x1024 canvas, then Min size of 512 will take half of the canvas, 256 a quarter and so on.

Flexible is ratio/weight used to proportionally distribute left-over space.

E.g. you have vertical layout that has total 500 units of space available. You have two elements, each with 100 units of preferred size. They both get 100 units, so now there's 300 units of space left.

If one of them has flexible size 1 and another 2, that will be the ratio used to distribute the remaining space. The flexible sizes are summed up and then normalized, so you get:

Sum: 3
1 / 3 -> 0.3333 (~33 %)
2 / 3 -> 0.6666 (~66 %)

Meaning the first one gets 33 % of the remaining available space and the other one 66 %, getting this as result:
100 + 300 * 0.3333 = 200 total units
100 + 300 * 0.6666 = 300 total units

If they both had 200 preferred size, then the remaining free space would be only 100. It would be distributed the same way between them, one getting 33 units and the other 66, for 233 and 266 total each.

**Comment by ProbablePrime** [comment]
Thank you!

I think that makes sense.
For Min/Preferred, It does feel like in most cases(Default pixel scale, 0.001 canvas scale etc.) that the values feel and act like pixels though. 

Thanks for confirming that Flexible is ratios, its been confusing for some time.

**Comment by Frooxius** [comment]
They roughly do. Often the canvases are sized really large (e.g. 1920x1080) so those values will roughly match pixel size of elements on a typical screen.

But the canvas is not pixel based, so they're technically not pixels, they're still relative to the canvas size and scale in the world. 

E.g. if you have canvas that's 1x1 units, you can have elements that are 0.02 or 0.05 units for example and it should work if you adjust everything, but those kinds of values are harder to work with than ones that are closer to "pixels".

**Comment by ProbablePrime** [comment]
Thank you, after playing in VR some more I can now close this as I have all the answers I need. Video coming soon and wiki article after that :)
