### ISSUE TITLE
Lightweight Lua Scripting

### ISSUE THREAD

**Issue by Frooxius** [Frooxius/NeosPublic#23]
Embed Lua runtime for lightweight dynamic scripting at runtime.

**Comment by BlaXun** [comment]
I’d love to see this!

**Comment by Frooxius** [comment]
I'm now certain that I won't implement this directly, instead we'll use something more general/powerful, like WASM or CLR, which will allow implementing Lua scripting on top by the user.

**Comment by Aerizeon** [comment]
Have you found a WASM library which works properly with the current .net version you're currently on?

When I looked into it, only one of the popular libraries could be made to work with Neos, and it unfortunately didn't have support for the reference type extensions. (and as such, I started messing around with Lua, since it *would* work.)

**Comment by uyjulian** [comment]
Not all browsers have support for the reference type extensions yet. However, I think once more browsers implement the extension, wasmer will also have support for it.

**Comment by H4x0r-000** [comment]
I Love this idea, Lua is simple, lightweight and performant.
