### ISSUE TITLE
Pelvis spawns backwards in avatar creator

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#241]
![image](https://user-images.githubusercontent.com/8791132/57335527-bd6fa180-70d7-11e9-8a9b-1d80b95ed093.png)

1. Spawn a y-bot avatar for reference
1. Spawn an avatar creator and configure the pelvis
1. observe the pelvis being the wrong way around.

**Comment by ProbablePrime** [comment]
I watched 3 Full body tracking users come across this today. 

Could it be looked at please :(?

**Comment by Frooxius** [comment]
I plan on reworking the calibration process, but I haven't had the time to do it yet, sorry. I should work on it soon (within next few weeks) though!

It's a little bit more complicated than just rotation, because I've tried rotating it several times, but it always broke elsewhere. I'm not sure whether it's the mesh that's incorrectly rotated, the reference, or the calibration.

**Comment by ProbablePrime** [comment]
Rotating the model to be other other way around will calibrate the avatar correctly so i assumed it was the model.

I understand this issue is complex so I appreciate your response. Thank you :)

**Comment by Frooxius** [comment]
Turns out it was the actual reference mesh that was backwards, so orienting it correctly actually made the reference itself backwards, making the avatar calibrate backwards too. 

I've changed it in the 0.8.15.33350 build just released so it's correct. I'll be integrating avatar full body calibration/adjustment into the new full body calibrator though which should be much easier to use. I'll see if I can do some automatic fix for the avatars that were calibrated backwards already, but I think some of them were fixed afterwards, so it's probably going to be a bit tricky. 

Anyway thanks!
