### ISSUE TITLE
Expose points/path on a ballistics path mesh

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#248]
I have a WIP Grenade, with the points exposed I can tween over the points on the path to make a simple throwing animation which will suffice until we have object physics.

**Comment by Frooxius** [comment]
I can't expose the points on the mesh itself, but I can give you a node which will get you the points given the same initial parameters, all you have to do is to make sure both the mesh and the node are fed the same inputs.

Although I'll have to think about how to best do this, because the way it's implemented is that you're actually generating the points from the special object one by one on demand, so that requires maintaining inner state and that might not be nice/easy to do without some extensions to LogiX itself.

One possible implementation is to use collections and enumerate the points, but that needs the handling for the extensions.

**Comment by ProbablePrime** [comment]
This is very old and I no longer require it.
