### ISSUE TITLE
Rotate tools reference/hand attachment inward by 90 degrees

### ISSUE THREAD

**Issue by DeliriousJax** [Frooxius/NeosPublic#254]
As more equip items are coming out, it's becoming apparent that certain models will need to be angled toward the thumb such as ones with handles and barrels or game type weapons. Right now by default the back of the hand is the "top" and the palm of the hand is the "bottom". Perhaps if the little finger would be the "bottom" and the thumb side would be the "top" so barrels handles and magazines are angled properly no matter if they are on the left or right hand.

At the moment, if you angle something like a gun or sword to fit and angle correctly to your right hand, it will be backwards/upside down on your left.

**Comment by Frooxius** [comment]
Unfortunately rotating it wouldn't fix the problem, but rather move it elsewhere. The problem is that each controller itself has different alignment (relative position of hand to the controller), so if you fix it for one, it's going to break on another.

I'm going to be working on a different system though, where you specify relative hand position on the tool or weapon and it's going to use it to match up with the hand on the controller (which matches the hand on your avatar), so when you equip it it's going to fit right into your hand, regardless of what controller is being used.

You'll have to bear with the existing system before that's done unfortunately, trying to tweak it to behave better would take lots of time for something that's going to be thrown away later on anyway.
