### ISSUE TITLE
Suggestion: Default Quads created with the Shape Tool to dual sided

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#257]
From a user experience point of view this makes more sense and will prevent users from being confused when they create an invisible shape with the shape tool(By default the quad's single face faces away from the user).

**Comment by Simulacron3** [comment]
That issue caused me much confusion and trouble early on.

**Comment by Frooxius** [comment]
Would simply making it face the user sufficient? I don't think making them dual sided is a good solution to the problem, because it will cause lots of other issues as well - if the material is already dual-sided, then it ends up "double dual-sided" and even with a single one it might not be clear which is the "proper" side.

**Comment by Simulacron3** [comment]
I think that would work for me. Anything that confirms creation and that there is side, avoiding the situation where the user may think object creation failed and tries again (and again) and can't easily select objects that don't seem to be selectable.

**Comment by ProbablePrime** [comment]
That would work, I didn't anticipate the issues with materials and dual sided quads. Facing the user would be a suitable solution :)

**Comment by Frooxius** [comment]
Done in 0.8.11.317. Thanks for your feedback!
