### ISSUE TITLE
AutoLookAtUser, UserInterfacePositioner, PositionAtUser are difficult to use with Logix

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#272]
Im trying to dynamically drive the target user of the components mentioned in the title here with logix using Users nodes or a User variable. It appears the data types are incompatible and there's no automatic casting setup. 

It would be great to dynamically swap between targeted users.

**Comment by Frooxius** [comment]
I think this is because of a deeper issue, which is that you can't work with references using LogiX right now (assigning or even getting targets) or value fields. Providing support for these should help fix your issues implicitly. Would that work?

I should note though that certain components won't like their references being driven or even assigned to, like AutoLookAtUser, since they're managing it themselves, but that's a secondary issue.

**Comment by ProbablePrime** [comment]
That would work, although it does sound like a lot more work D:.

Other nodes/interfaces seem to take a user input more easily. So I assumed there was something weird going on with these components.

**Comment by Frooxius** [comment]
Can you give me examples of the other nodes/interfaces? I'm not quite sure where the difference is coming from.

It might be because they use more generic reference that happens to be a type of user, rather than specialized user-reference field, but I'm not sure.

**Comment by ProbablePrime** [comment]
Come to think of it i'm not sure in regards to components/interaces but in terms of Logix Nodes: Standard Controller, Fire On True, User Username.

I'm sure there was a component but i'm struggling to remember it.

**Comment by ProbablePrime** [comment]
this is fixed
