### ISSUE TITLE
Crash During Creator Jam 09

### ISSUE THREAD

**Issue by ParkerRK** [Frooxius/NeosPublic#277]
I'm not 100% sure if I'm doing this correct, but: 
During Creator Jam 09, Medra, Myaggic, and I had a consistent crash of the application.
Medra and Myaggic are using Oculus; I'm using Vive

Log:
[DESKTOP-LTFMBAU 7_28_2019_4_23_25_PM.log](https://github.com/Frooxius/NeosPublic/files/3439586/DESKTOP-LTFMBAU.7_28_2019_4_23_25_PM.log)

Crash Report of Incident:
[Crash_2019-07-28_202244033.zip](https://github.com/Frooxius/NeosPublic/files/3439591/Crash_2019-07-28_202244033.zip)

Additional, Likely Unrelated, Crash Reports I Found in Same Location:
[Crash_2019-07-21_201459790.zip](https://github.com/Frooxius/NeosPublic/files/3439595/Crash_2019-07-21_201459790.zip)

**Comment by Frooxius** [comment]
Was the crash happening during a certain action? Or something repeatable?

It seems that it might be caused by the Steam overlay interfering with the libVLC library. Can  you try disabling it and see if it has any effect? 

You can do that in the properties on Steam:

![image](https://user-images.githubusercontent.com/8838625/62033113-8a770e80-b1eb-11e9-8b56-498a0db02b19.png)

**Comment by ParkerRK** [comment]
From what I know, it is unrepeatable since I have no clue what in the session could have caused it. From my point of view it just... happened. I forgot to mention that it was on version 0.8.13.41333

**Comment by sirkitree** [comment]
Thanks for the report, I don't think there is anything actionable here, but if there is, please reopen.
