### ISSUE TITLE
Controller Turning/Rotation Suggestion

### ISSUE THREAD

**Issue by Casuallynoted** [Frooxius/NeosPublic#281]
Has a really fun time hopping about in Neos earlier today 😄 One super small thing that I noticed-

When I use the right joystick, it moves me forward or backward unless the joystick is exactly right or left without any slight leaning up or down, should I make a custom controller config for that one if I just want it to handle turning on the right stick?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Casuallynoted** [comment]
(Quick update on this, after some playing around with SteamVR Input, I don't see an option to do this in there sadly!)

**Comment by Frooxius** [comment]
Hello! Yeah this is a Neos VR thing so you won't find it in Steam VR. I'm not sure I exactly understand the problem though. Is it that you're getting rotated slightly when you're just trying to go forward/backward?

Which locomotion mode is this on by the way, Walk/Run? With Index controllers?

There's one thing you can try in settings, which is enabling "Smooth Turn Exclusive Mode". That way you'll always either rotate or move with that controller.

Additionally if you don't mind some tweaking, open up the locomotion module on your avatar and find the "SmoothTurnThreshold" property. Try changing the value to see if it behaves any different. This essentially represents how much you need to tilt the joystick before you start turning.

**Comment by shiftyscales** [comment]
Hey, @Frooxius. I've had similar issues myself. The problem is that when you want to rotate with smooth turning, you can move forward/backwards (usually forwards in my experience) by holding the joystick at certain angles. It's somewhat an implementation issue, but also a controller-specific/hardware issue.

In my case- I can rotate right with no issue, but if I rotate left, I usually slowly walk forward while I do. It could be down to the way I hold the controller, but there are a few ways you could improve the control schemes/provide options for players.

In particular- it would be nice to be able to unbind move forward/back on the right hand joystick. (Or left in the case of a 'southpaw' configuration.) As is- I use the left stick for moving forward/backwards, and strafing, the right for turning.

Other retail VR experiences use the up and down input on the right joystick for jumping/crouching. This could also be a 'comfort' option to move fly up/down while in fly mode, and provide an easier way to crouch while in seated mode without needing to open the setting menu, and uncheck the seated mode option.

I hope these thoughts/suggestions have clarified the issue for you. Thanks.

**Comment by Casuallynoted** [comment]
Oh man, I’m sorry I didn’t reply sooner- I didn’t get a notification until now! But everything said above is perfect, exactly what I meant and said way better than I would have said it. :)

**Comment by shiftyscales** [comment]
Stick input has been modified a few times since the initial creation of this issue, and isn't an issue any longer as best I can tell.
