### ISSUE TITLE
SphereAligner Component

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#284]
This is a request for a SphereAligner component which is similar to the CircleAligner component but will distribute the children objects in a sphere of a given radius around the parent object.

**Comment by Frooxius** [comment]
This could potentially be done, but aligning on sphere is a lot more complex than circle, because you have a whole extra dimension.

Question is how exactly should the points be computed? It would have to be uniform based on the number of points, but I don't know any formula to compute such distribution. Anyone know a good one as reference? 

It could be done in a more simple way using iterative method with the points repelling each other, which should settle on a solution, but I'd rather do this analytically, as that's going to be much more efficient and won't need to wait for convergence.

**Comment by sirkitree** [comment]
Here's what I'm using for a three.js animation that is similar:
```
function randomSphereEven(radius, PhiNum, thetaNum) {
  let points = [];
  let phiSpan = Math.PI / (PhiNum + 1);
  let thetaSpan = (Math.PI * 2) / thetaNum;
  // create random spherical coordinate
  for (let i = 1; i < PhiNum + 1; i++) {
    let phi = phiSpan * i;
    for (let j = 0; j < thetaNum; j++) {
      let theta = thetaSpan * j;
      let point = new THREE.Spherical(radius, phi, theta);
      points.push(point);
    }
  }
  return points;
}
```

I'm not sure this is the best as I get weird results sometimes, but it may be a good place to start.

**Comment by Frooxius** [comment]
That creates a random point on sphere, that's not really what aligners do. They need to be deterministic and the positioning of the points is based on number of the objects.

For example with circle if you have two objects, they will be at opposite sides of the circle, if you have three, they're going to be exactly one third of the circumference apart from each other.

I need algorithm that does the same. If you want to simply randomly position objects on sphere, then you can do that with LogiX, there's a function for generating random points on the surface of a sphere under Math / Random.

**Comment by sirkitree** [comment]
http://corysimon.github.io/articles/uniformdistn-on-sphere/ maybe?

**Comment by Frooxius** [comment]
Unfortunately that's the same thing as your first example, it generates random points on a sphere with uniform distribution, which is not suitable for an aligner.

For an aligner the distribution must be uniform, but also deterministic (not random).

**Comment by sirkitree** [comment]
https://stackoverflow.com/questions/9600801/evenly-distributing-n-points-on-a-sphere#26127012

**Comment by Frooxius** [comment]
Oh that seems to be it! Thanks! I'll look into this.

**Comment by Frooxius** [comment]
Done and released, thank you for the help and suggestion!

**Comment by sirkitree** [comment]
huzzah! Thank you!
