### ISSUE TITLE
No climbable Components 

### ISSUE THREAD

**Issue by Jazzneo** [Frooxius/NeosPublic#310]
wonder if it's possible to make No climbable Components person won't be able to climb on part of a wall that doesn't have ladder or rope and can be used for people don't people climb on other avatars?

**Comment by Simulacron3** [comment]
I like the idea of setting a personal space in general.  A simple capsule collider to prevent being walked through or the like would do.

**Comment by Frooxius** [comment]
This is already implemented. Attach component "LocomotionGrip" under Locomotion / Interaction.

- If this component is present, but disabled, you won't be able to climb.
- If you configure the locomotion module to be able to climb only locomotion grips rather than any character colliders, you'll be able to climb only colliders with this component in enabled state
- You can use the green tooltip to make things climbable - open the radial menu and set the climbable option before clicking on a collider
