### ISSUE TITLE
Baking meshes leaves weird residual mesh artifacts

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#315]
Here's some steps to see the problem.

1. Visit build a yeen
1. Hit finalize on the button infront of the avatar it bakes the meshes within the model
1. With the baked model, use the grabbable setter tip or the mesh visibility tip. 
1. Notice that the "flash" from these tools shows an extra Yeen top horizontally infront of the model.
1. Select the avatar in the inspector, note the abnormally large bounding box which matches the shape of the horizontal "phantom" mesh.

**Comment by Frooxius** [comment]
Are you sure it's an actual residual artifact? The flash doesn't use skinned meshes, so when they flash they show as their default static pose, that doesn't match the actual visual, that's normal. 

You could check the mesh data and check how many submeshes it has and check if the number of materials matches.

**Comment by ProbablePrime** [comment]
That's understandable, except its also affecting the bounding box. 

Here's the bounding box:
![](https://media.discordapp.net/attachments/565105632689127435/621806734079557652/20190912133705_1.jpg?width=963&height=542)
And here's the residual flashing so you can see what i mean, its just one part. the rest are shown in their default post standing upright.
![](https://cdn.discordapp.com/attachments/602766048797655061/623799959308730368/20190918043712_1.jpg)

i tried it with build a nanachi and the same sort of effect is seen but this time its the nanachi pants. This is less of an effect because they are aligned and scaled to a suitable proportion.

**Comment by Frooxius** [comment]
Oh that's much larger than I thought it was, that definitely seems odd. I'll have a look thanks!

**Comment by Frooxius** [comment]
I've looked more into this. Turns out that it's still technically correct behavior. No mesh data are getting corrupted or added. 

Essentially what happens is that the each individual mesh is "dumped" into a single mesh, with its raw transform, rather than transforming them to correct relative location, rotation and scale of the bake root.

This ends up mushing the meshes all together and losing whatever alignment the mesh renderers had in the inspector. 

The benefit of this is that it has much greater likelyhood of producing identical baked mesh for multiple sources, if all the meshes themselves are the same, with the transformations even slight offset will change the values a little and end up producing mesh with a different hash.

The bounding box that you're seeing is essentially the boundingbox of the "raw" combined mesh, but the character itself looks correct, because it's transformed into appropriate pose by the bones. 

I can add support for actual skinned mesh bounding box (after transformation by the bones) so that will show correct and add skinned mesh support to the flash effect. This would mask the change in the mesh in most cases. Only if you viewed the raw mesh you'd see the odd looking one.

Do you think that's good enough solution? 

Here's a sample of the raw mesh without bones by the way:
![YeenTest](https://user-images.githubusercontent.com/8838625/65150131-bbbdcf00-da23-11e9-9fae-bce64620e49b.png)

**Comment by Frooxius** [comment]
I've pushed out the updates. The mesh data still looks how it does in the screenshot internally, but you won't see it in the flashes or on the bounding box anymore.

**Comment by ProbablePrime** [comment]
Apologies for not responding, you did an awesome job here and thank you so much for responding.
