### ISSUE TITLE
Hover for physical button component

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#345]
I'd like to be able to detect a hover on something that has the physical button component on it. 

Currently the physical button component is not compatible with the touchable components but touchables are the only way I know of to get haptic feedback and the ability to act upon hover. I also can't put touchables on the parent of an object with the physical button component. 

It would be most convenient if the haptics and hover detection were added to the physical button component itself and then hover became an event that could lead to a pulse with the Button Events logix node.

**Comment by TehTurk** [comment]
Seconded, said the in the discord week or so ago if we could get a combination of touchable and button. But if we have one what else should a touchable have? Since we kinda deep in UI update now, what exactly would be the requirements for a good interact-able? The Physical Button is good for showing 3d Action, while Touchable has hover/haptic elements, but also should keep it low spec so people can customize and do whatever they want. That or allow some sort of interaction priority similar to grabbables so we can have multiple components on one object. We also have Neos Button which has a bunch of different things that have a combination of thing, but also has issues too, (It doesn't like changing meshes)

**Comment by sirkitree** [comment]
New feature works like a charm, thank you!
