### ISSUE TITLE
HTC Cosmos support

### ISSUE THREAD

**Issue by Frooxius** [Frooxius/NeosPublic#363]
Currently HTC Cosmos headset isn't supported by Neos. A few people have asked for the support. It's a bit tricky adding this since I don't have access to the hardware, but if there's interest I can add support blindly. I'd need someone to help with testing who has the hardware though.

How much interest is there in supporting this headset?

**Comment by InsaneGrox** [comment]
I have the hardware, and have a mild interest in support, while it is not my primary headset, I do believe it isn't the worst headset in the world, I've already done a bit of testing with the vive cosmos, and from what I've gathered, blind support should be as simple as starting with the oculus controller and working from there considering the way SteamVR binds the cosmos controllers.
https://youtu.be/wOeViwVmdFA (it's just the controllers that don't work properly, the headset itself works just fine, also means the lighthouse tracking plate won't have any problems)

**Comment by Frooxius** [comment]
I've tried looking into this more and add the support, but it's proving to be really hard to do without the actual hardware, as SteamVR won't offer to build the bindings for the Cosmos controllers if they're not present on the system (it offers Index, Vive, Touch and Windows MR ones though), so I can't even start building them into Neos.

I can't also find documentation on the available inputs so I could make proper classes for it. I'd need to either get a dev-kit for the integration or have someone help. I'd need full enumeration of all the inputs and their types on the controller and their respective SteamVR input binding paths.

**Comment by InsaneGrox** [comment]
If you want to I can send you the binding json files for them, I have access to them since I have the software for the cosmos & the cosmos itself on another PC

**Comment by InsaneGrox** [comment]
[bindingstuff.zip](https://github.com/Frooxius/NeosPublic/files/4905203/bindingstuff.zip)
hopefully this is all you'd need (I got these directly from HTC's driver for the cosmos)
File path I got it from
C:\Program Files (x86)\VIVE\Updater\App\openvr_driver\vive_eyes\resources

**Comment by Frooxius** [comment]
Sweet thank you! Yeah whatever materials you have can help. I can't promise they'll be enough, but I'll have a look.

**Comment by InsaneGrox** [comment]
My suggestion short term (next update level short term, like just making it functional enough to use) would be to make them default as emulating oculus touch controllers 1:1, including the oculus controller node in logix (it would be missing the grip strength, thumbrest, and ABXY touches, everything else is present. (including trigger touch and thumbstick touch) long term (when full support is implemented) would be making one change, making the bumper above the trigger act as a seperate secondary button since it doesn't really do anything otherwise, and it would free up the joystick clicking to just jumping, (making yet another controller capable of doing secondary actions without jumping) as a side note, with some binding edits I did get the skeleton working, so the hand offsets don't need to be handled like old WMR controllers pre-skeletal input.

**Comment by Frooxius** [comment]
It's easier to actually implement them properly. I'll have similar handling for them since they're similar to the Oculus, but they'll be their own controller type. 

I checked the files, it looks like it has everything I need! I'll try to get the initial support in a build or two.

**Comment by shiftyscales** [comment]
Cosmos has been supported officially for a bit now.
