### ISSUE TITLE
youtube-dl Feedback Thread

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#373]
From my initial testing- youtube-dl is a very welcome addition to the project. It is providing a very seamless, and intuitive way to import videos from across the web.

It appears that video playback is still causing crashing, however seemingly randomly.
[error.log](https://github.com/Frooxius/NeosPublic/files/4083484/error.log)
[Player.log](https://github.com/Frooxius/NeosPublic/files/4083485/Player.log)

Less importantly- I've noticed that live streamed video- e.g. Twitch, Live YouTube videos continue to stream in their video data even when paused. The texture continues to update while the pause icon is displayed on top. The audio stream is muted as expected, fortunately.

**Comment by Frooxius** [comment]
youtube-dl doesn't  handle any video playback, only extracting the URL's. The actual playback is still handled by the original libVLC wrapper library, no change there. It will be replaced by the official wrapper once it's ready.

Streaming playing when paused is intentional too. The 3rd party libVLC doesn't handle pausing livestreams correctly, causing them to break, so they're only muted right now. This won't get changed until the upgrade to libVLC again.
