### ISSUE TITLE
[Bug] World orbs reference themselves when quick joining

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#376]
When joining a world from a world orb- attempting to create a new instance of that world from a world orb will result in the current session linking to itself. While the world can be closed by use of the close button, or pressing, and holding on the session in the session menu on one's hand- the user will remain inside of the world until they switch to a new session.

This behavior only appears to occur when double clicking/tapping on a world orb. using the "Start Session" button of the world orb does not replicate this behavior.

https://youtu.be/OUPgh5LDI00

**Comment by Frooxius** [comment]
This is intentional. Neos deduplicates any active sessions. If there's already an instance of that session running, Neos just switches you there, rather than opening another instance of it.

Using the startup dialog is a way to override that behavior if you want to run multiple instances, but in most cases you shouldn't, so the deduplication is default.

**Comment by shiftyscales** [comment]
Is it intentional that a deduplicated session is unable to be fully closed, and exited without explicitly switching to another session? A session opened by any other means will close, and send you back to the previous session in the chain.
