### ISSUE TITLE
[Freak crash] Random crash occured when operating with LogiX (also broke Oculus service)

### ISSUE THREAD

**Issue by Hacksawfred3232** [Frooxius/NeosPublic#387]
Crash occured when attempting to get the output connector from the division operator. 
Screenshot: https://cdn.discordapp.com/attachments/439422161657135106/675024705400471572/unknown.png
Last line of the log:
```
System.NullReferenceException: Object reference not set to an instance of an object
  at BEPUutilities.Matrix2x2.Transform (BEPUutilities.Vector2& v, BEPUutilities.Matrix2x2& matrix, BEPUutilities.Vector2& result) [0x0003c] in <fec520f53335442481361d3cb38819cb>:0 
```
Apparently, no crash dump was generated?

**Comment by shiftyscales** [comment]
A crash dump will not always be generated as sometimes the game can be terminated faster than it has time to generate one.

I've not been able to replicate this issue by the setup provided. From the Discord, @Hacksawfred3232 had also mentioned:
`Okay, so I think something broke with the Oculus Service. Had to restart the Oculus Service for the crashes to stop.`

**Comment by Hacksawfred3232** [comment]
Yeah, this looks like a freak crash. Modifying title to reflect this. Should a catch be added in for this in the future, so NeosVR knows to exit cleanly and prompt the user to restart their VR software? This looks like memory corruption, IMO.

**Comment by shiftyscales** [comment]
In cases like these where there are a lot of potential external variables at play, there's not much that could be done on Neos' end. There's no reasonable way for it to know/suggest to the user that they restart their PC/softwares, and as you experienced- even if it could, it might not have time to even get that message out.

There could be a potential argument made for Neos running in a 'safe mode' if it detects multiple subsequent crashes, but that in of itself would be more a bandaid to the issue rather than fixing things at the source, where applicable.

Like with race condition issues, too- it's not worth investing a ton of time in trying to fix it if you have no context for where in the code the issue lies, or how to replicate it. Especially so if the issue is exceedingly rare.

**Comment by Hacksawfred3232** [comment]
Fair enough. Closing the issue then, lets hope the new engine update deals with this.
