### ISSUE TITLE
Particle System Collisions and Particle Collision Scale

### ISSUE THREAD

**Issue by Vigilabo** [Frooxius/NeosPublic#388]
The colliders generated by particle systems do not scale with the scale of the particle system/slot scale. I'm not 100% sure since there is not really any method of visualizing the actual colliders generated. Along with this it would be nice to have the particle collision radius exposed as a usable parameter for particle systems.

**Comment by shiftyscales** [comment]
I tested with the following settings changed from the default particle system:
- Enabled `Collisions` on the `ParticleStyle`
- Set a `Radius` of `0` and `ForceDirection` of `1` on the z-axis to force the particles to move in a consistent line.
I then adjusted the `MinParticleSize` and `MaxParticleSize` to the same values, and adjusted the slot scale observing the way they bounce off of a wall.

My findings suggested that the way the particle systems do collisions is from a fixed point at the center of the particle, so in this context, adjusting the scale would have no effect on the collision because the colliders have no volume.

I do not know if it would be problematic to have upwards of thousands of sphere colliders present in a scene from the particle emitters, but conceptually, it sounds like it could be.

**Comment by Frooxius** [comment]
This is expected behavior. The particle system doesn't generate any colliders at all, so things like particle size or scale won't have any effect. Instead it performs raycasts (infinitely thin lines) for each particle depending on how much it travels between the two points, so there's no "radius" to speak of.
