### ISSUE TITLE
Bhaptics suit support 

### ISSUE THREAD

**Issue by alexderpyfox** [Frooxius/NeosPublic#404]
This would be a handy feature i think to add to the supported hardware list since some big vr YouTubers are starting to buy one and having neosvr as one of the few games to support it would be amazing since everyone can just buy one in store already.

**Comment by MR-Alex42** [comment]
Have contacted bHaptics now if they are willing to provide a free dev-kit. Waiting on their feeedback now.

**Comment by Enverex** [comment]
Given the fact BHaptics have been contacted several times (once by Froox himself) and have provided nothing other than radio silence, I wonder if it's worth contacting one of the random YouTubers that have been provided one by BHaptics? I can't imagine they're doing anything but collecting dust in a cupboard at this point in almost all cases.

**Comment by Casoliv-Kuro** [comment]
Any Updates on this?

**Comment by alexderpyfox** [comment]
> Any Updates on this?

Yes froox gotten a devkit and said he is working on intergrating it yesterday in the updates channel

**Comment by Casoliv-Kuro** [comment]
Damn ty ^_^  I completely overread it. Big dumb me :D

**Comment by MR-Alex42** [comment]
I suggest to include .tact file support. These files could be played similar to animations. 
Also Audio2Haptics support would be great.

**Comment by Frooxius** [comment]
.tact files won't be supported, they don't fit into the abstraction layer, as they're written against a specific type of suit, rather than general animations. Support might be added at some point in the future, but it'll require substantial amount of work. The goal of Neos is to create system for haptics that works across many different devices.

You'll be able to drive the tactic sources from LogiX using audio volume.

**Comment by Frooxius** [comment]
Native support added in 2020.11.29.1371!
