### ISSUE TITLE
UtcNow does not seem to use correct timezone offset

### ISSUE THREAD

**Issue by nitori** [Frooxius/NeosPublic#412]
![times2c](https://user-images.githubusercontent.com/1561831/75820728-29c13d00-5d9d-11ea-97dc-254632349ad9.png)

I would've expected that formatting UtcNow would yield an offset of +00:00.

This probably is also the cause why the difference between UtcNow and the same time converted to local time, is 1 instead of zero.

**Comment by Frooxius** [comment]
Unfortunately this is how .NET formatting for DateTime behaves due to the limitations of the structure. The DateTime doesn't store an actual offset in itself, so the "zzzz" will print out the local system time offset regardless. LogiX just wraps this behavior from .NET, so I can't do much about this, sorry! 

I can look into adding nodes for DateTimeOffset datatype, which supports explicitly specifying the timezone though if that would help.

See this for reference:
https://docs.microsoft.com/en-us/dotnet/api/system.datetime?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings

**Comment by nitori** [comment]
Hmm, well. Working with an offset aware date time type might solve this issue, but I'm unsure if that would be a proper approach. TimeZones are, after all, not only about some offsets, but about location/politics/the weather and maybe what you ate this morning.

e.g. I have yet to try it, but I wonder what happens if I use the Date Time constructer thingy, and give it the date of, let's say, 15, August 2020, 8pm, and use "Local time" for the "kind" input.

If it works correctly, it should have an offset of 2 hours, instead of 1 (I live in Germany), because of daylight saving time.

I saw after a bit of searching, that .NET seems to have something called "[TimeZoneInfo](https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.findsystemtimezonebyid?view=netframework-4.8)" (Note: I'm not a .NET dev, so no Idea how applicable this is), which could be a great help to work with "proper" TimeZones, instead of pure offsets.

Alternatively, maybe as a request for the future, having a way to work with the [IANA tzdata database](https://en.wikipedia.org/wiki/Tz_database) might also be a nice feature, but probably requires some work.

**Comment by Frooxius** [comment]
It's best to use existing language primitives for this kind of thing, as they handle all the complexities of timezones for you.

It kinda depends on what kind of functionality you need, but .NET should generally provide a lot, so I could wrap that. I'd recommend making a new issue if you need nodes/datatypes to better work with TimeZones and similar. 

For this specific issue I'm going to close it, since it's something that's inherent to the DateTime from .NET and how it operates and can't be fixed.
