### ISSUE TITLE
[User Interface][Feedback] Players on Friend list need to have a different color nameplate or Name Badge Symbol to easily establish they are on a friend list.

### ISSUE THREAD

**Issue by aguirretim** [Frooxius/NeosPublic#415]
Description:
This is feedback after comparing with VR chat and other social VR games there is usually a clear nameplate change for people added on the user's friends list. 

Steps to Reproduce:

1. Launch Neos VR.
2. Navigate to a world with a friend in it.
3. Look at the user's friend nameplate.

Expected Result:
The user should see a different color nameplate or Name Badge Symbol

Actual Result:
The user sees the nameplate look no different than players who are not on the friend list.

**Comment by Enverex** [comment]
Probably a badge given that many people play with their name tags, plus you can have multiple badges without issue.

**Comment by shiftyscales** [comment]
At present the username color is reserved for roles. E.g. the Neos Team members have a yellow name, Patrons red, etc. Similarly, badges can be used both as a visual flair, and to transmit information about a user. E.g. if they are hearing impaired.

It could be useful to have a badge indicating friendship- but expanding upon that idea, other aspects of a user's status could be displayed through icons such as the status of their microphone, and/or the voice mode they are currently in. E.g. normal/shout/broadcast.

I've added the UI/UX label so that this issue may be considered during the UI/UX overhaul as we iterate, and improve on the UI now that the UIX framework has been implemented.

Thanks for the suggestion, @aguirretim. If you have any other proposed changes to the name badge system, or think of any other user information you would potentially like to see as a part of them- please feel free to drop another comment in this thread.

**Comment by Frooxius** [comment]
Hmm I think we'd use some other indication for this, other than the name color, since that already has other functions. 

However, I'm actually curious what's the purpose of this feature? What are the scenarios in which you need to quickly know if the person is friend or not?

One thing you can do currently is simply click on their name, which opens up the friends list, which will indicate if they're a friend or not.

**Comment by Enverex** [comment]
>However, I'm actually curious what's the purpose of this feature? What are the scenarios in which you need to quickly know if the person is friend or not?

Obviously you're going to know someone anyway if they're a friend, without needing a tag. This though, I think it's more a social cue of "You should know this person, they aren't a stranger..." rather than something functional. A reminder that you already know this person, which may jog your memory as to who they are (this isn't a big issue in Neos right now due to the size of the user base, but will obviously be more important later on).

**Comment by shiftyscales** [comment]
It would also be a good visual cue to remind users to send out friend requests too. I know I've heard people mention in Neos they were surprised they hadn't added someone as a friend yet.

**Comment by wel97459** [comment]
It's handy for locating a friend in a world too.

**Comment by shiftyscales** [comment]
Worth noting- inside of the world browser, you can now distinguish friends and non-friends by the color of their name while browsing a session's info.

**Comment by shiftyscales** [comment]
As of recent updates, it is now possible to hide the nameplates of contacts using the nameplate visibility facet, allowing a user to quickly distinguish who they don't have added as a contact in-world which should fulfill the needs of this issue.
