### ISSUE TITLE
GrabInstancer creates a new instance of the grabbed object for each collider in its hierarchy

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#426]
Steps to replicate:
- Set up a GrabInstancer
- Add any object with a collider (e.g. empty object with box collider)
- Ensure all colliders are being touched when the grab instancer is activated

Result:
- An additional instance of the object is created for each collider present and in range of the grab

Observations:
- The collider can be placed anywhere in the hierarchy below the GrabInstancer
- Multiple collider types have been tested and appear to all cause this issue

Footage of this issue can be found here:
https://youtu.be/AMwNElleVOs

**Comment by Frooxius** [comment]
I think this is due to the grabber finding multiple separate colliders through which the GrabInstancer is found. So if you have three, it's found three times independently, therefore 3 copied.

The easiest thing is to just ensure it has a single or no child at all (the template doesn't need to be parented under it). I'll see how complex it is to get rid of this behavior.

**Comment by Frooxius** [comment]
Should be fixed in 2020.3.14.776, thanks for the report! This might fix some other strange grabbing behaviors as well.
