### ISSUE TITLE
[Bug] AudioClipPlayer still count as playing even when the clip is done

### ISSUE THREAD

**Issue by LewisSnow** [Frooxius/NeosPublic#438]
I was working on a audio manager system that checks if a clip is player to know if the slot its under should be enabled or not. However for some reason the node that checks if the clip is playing doesnt pick up on it not currently being played when the clip is done.. maybe due to the clip sometimes stopping before it should? I.E I was watching a clips length (7) and watching its progress but it ended up stoping at (~6,98888)

**Comment by shiftyscales** [comment]
Hmm. This sounds like it could be yet another case of floating point imprecision. What happens if you were to plug in an updating relay on the bool output?

**Comment by LewisSnow** [comment]
Not sure, I'll have to test that when Im back into Neos.

**Comment by Frooxius** [comment]
Which node are you using to check if the clip is playing? You can ignore the progress value, because that's not used to determine when the clip is playing or not, the playback state is handled internally by a set of flags and an offset.

Try using the node with UpdatingRelay, because the playback system doesn't actually generate a change when it finishes, so it's possible your node isn't just triggering an update to re-evaluate the state.

**Comment by LewisSnow** [comment]
Im using the "IsPlaying" Node to check if the clip is being played. I'll try the updating relay.. plug the bool into it or the clip.

**Comment by Frooxius** [comment]
Yeah you need to use the UpdatingRelay with that, it won't trigger update on itself. Alternatively there's the Play & Wait or Wait nodes for playback, which will do the wait for you when you send them an impulse.

**Comment by LewisSnow** [comment]
Wilco
