### ISSUE TITLE
Setting a font's GlyphEmSize to a large number causes extreme memory usage that leads to crashing.

### ISSUE THREAD

**Issue by RileyGuy** [Frooxius/NeosPublic#439]
Steps to reproduce:
1: Find a font you wish to edit and inspect it
2: Open the font and set the GlyphEmSize to something like 2000
3: Everyone who is in the world will eventually memory leak and crash.

I would suggest not allowing anything over 512. This can't be the only way to crash people using avenues through the inspector like this. I would also suggest not updating values until the value is finished being edited so this doesn't happen through typos. Maybe have the enter button on the keyboard confirm the edit.

**Comment by Frooxius** [comment]
This is expected behavior, making each glyph really huge will make the system use lots of big textures. Those are not memory leaks, just a high usage as if you imported lots of high resolution textures. Using those values should be only be done with certain fonts or font sets.

I can put some arbitrary limit, but at the same time I don't want to prevent experimenting and certain usage. I can put a fixed one there for now and later make it a configurable option of the session.

I'd have to see about making it not updating until you finish editing. I have a mechanism for that (URL fields do this), but not a way to make only specific fields use this behavior.

**Comment by Frooxius** [comment]
Added clamping in 2020.4.8.1428, thanks!
