### ISSUE TITLE
World Building General Enhancement Thread:

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#467]
Throw any suggestions or optimizations that you'd like to add!

**Comment by shiftyscales** [comment]
I'm closing this issue as anything that could be suggested here would be better handled as discrete issues. Where possible, it's best to keep feature requests and bug reports small and discrete so that the underlying problem can be addressed, and the issue closed.

When issues/requests are bundled together, it makes it more difficult to track them.

Threads should be reserved for feedback on a very specific thing rather than something broad/general.

**Comment by TehTurk** [comment]
Ah that's fine :) sorry for any misunderstanding.
