### ISSUE TITLE
Smooth POV Camera Sometimes enters my head.

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#470]
This one is an odd one. Sometimes when using smooth pov on the ingame camera it will render the inside of my head when im flying. This doesn't always happen but when it does  it can be quite jarring for the video.

I have an unlisted video showcasing the problem here: https://www.youtube.com/watch?v=T9PIWrE-J_g

I understand that it might just be my avatar configuration but I wanted to report it. Please let me know what I can do to help.

**Comment by shiftyscales** [comment]
This was [previously reported](https://streamable.com/egwh9b) by Hayden on Discord.

I believe it's related to the update order of physics being changed sometime around build [2020.4.6.1189](https://discordapp.com/channels/402159838827905024/469131434628612116/696811887765225522).
`- Restructured update cycle, so physics engine updates after all changes and any colliders that were moved as a result are updated immediatelly after in broadphase`

**Comment by ProbablePrime** [comment]
Ahh awesome, here's a GH for it then :) thanks for making the linkages!. Also I take it back Hayden's face is much worse with this issue D: teeth and eyeballs.

**Comment by Frooxius** [comment]
Yeah this is a known issue, it has to do with an update order. Sometimes the camera updates first, before the character position updates, resulting in an old position.

It's a little bit tricky to get around, as it requires some architectural changes, otherwise there will always be something that sort of "lags behind".

**Comment by shiftyscales** [comment]
Since this issue was initially reported, I've noticed this behavior more, and more elsewhere, e.g. when spawning into a world, the avatar will be at the origin, and fly into position to meet up with where the user is in their playspace, and while they are moving around (particularly backwards) it is very clear that your avatar lags behind the tracking.

The old behavior felt much nicer for avatars at least, as the avatar would always stay nearly 1:1 with the user's tracking space locally.

If possible, prioritizing updates on the local user's avatar to keep them in sync with their tracking would feel a lot nicer.

**Comment by Frooxius** [comment]
Should be fixed in 2020.5.9.1126, thanks for the report!

**Comment by shiftyscales** [comment]
Reopening this issue as this issue has still been occurring. Notably, it has happened during a few recent Twitch streams when new users are checking out Neos.

**Comment by shiftyscales** [comment]
I've made an interesting discovery. If the stream camera remains open while entering a new world, this issue occurs again, causing the wrong update order for the camera, rendering it delayed behind the position of the head.

This is also why this issue has been so prevalent on the Friday live streams when Nexulan world-hops.

**Comment by LeonClement** [comment]
It also happens passively after world hops as well it seems. My viewers have told me several times within a single session that I've encountered the bug. Maybe it's a domino effect of the world hop issue passively causing it? If you need more logs I can provide them the next time I stream as it happens every stream without fail. : )

**Comment by Hayden-da-Serg** [comment]
I've also noticed that this happens when using a Camera Anchor then setting it back to SmoothPOV, the camera just remains in that state after that.

**Comment by Frooxius** [comment]
Should be fixed for good nowin 2020.10.5.476! Sorry it took so long to get to this issue!
