### ISSUE TITLE
Local-only lasers

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#485]
Suggested by Nexulan, GearBell, DeliriousJax, and others, it's been requested that worldspace lasers be visible only locally at all times.

Functionally, the purpose of the laser is to give context for the user that is using them what they are aiming at/how it will interact- as such, other users don't benefit from seeing them in the same way as the user using them.

Being visible in the world from all users has been identified as visually distracting, and immersion-breaking.

**Comment by Frooxius** [comment]
The lasers are intentionally visible for other users so you can see what they're interacting with, to help give you more context, rather than things happening without visual reference (e.g. someone moving object around). The system has been intentionally redesigned to allow this, by not having the lasers activate, so that is an intended function.

From what we discussed the lasers would be invisible when they're gray/white for others users, but would still be visible when pressing buttons and grabbing things, which cause visual changes regardless and are not something you're doing constantly in social setting for it to be annoying. I believe that's the best solution.

**Comment by shiftyscales** [comment]
Having the lasers be invisible (particularly while grabbing) has been a crucial aspect of some experiences that creators like GearBell have made. She uses her ability to manipulate things at a distance as a means of puppeteering her creations, e.g. on "A Miner Problem".

There is also a certain coolness factor to being able to appear to reach out and pull things towards you- kind of like 'the force'.

A proposed solution I'd also heard is to keep lasers active only for when a tooltip is equipped.

But either way, hiding the gray/white lasers would be a good thing.

**Comment by Frooxius** [comment]
I could add things that would let you override this behavior. I think in most cases you want the lasers to be visible for ease of use and to make it clear what's going on to users.

Originally the lasers being hidden was a quick ad hoc solution for the lasers being everywhere, but it has caught a lot of baggage constraining the design and leading to behaviors that were never intended. Having them active with a tooltip was one of the ad hoc solutions.

We have opportunity to redesign the system for better, so I want to avoid constraining the redesign just to preserve old behaviors exactly as they were.

It's possible to find new good solutions for the problems and breakages, but it's important to understand what they are.

A few ideas might be either some overrides on the object itself, ability to toggle the lasers to be fully hidden on the user or having a special tooltip for remote grabbing manipulation. Each one has some implications and potential problems.

**Comment by Frooxius** [comment]
The laser now only render when interacting with things for other users. Closing this now. For mechanisms for hiding lasers in general and other behaviors I recommend opening new issue. Thanks!
