### ISSUE TITLE
[Feature Request] Addition to TouchableData and TouchToggle

### ISSUE THREAD

**Issue by LewisSnow** [Frooxius/NeosPublic#499]
Now with the new laser system, being able to allow these components to be interacted through colliders would be amazing, especially for hud based UI interactions.
say like
"Ignore occlusions" Bool

**Comment by Frooxius** [comment]
That's not possible unfortunately, sorry. The reason they don't get found is because some other collider is hit. If they're never found the property to ignore occlusions can never be checked. 

You need to structure your colliders in a way that they get hit appropriately. I'm working on adding a little bit extra fudging with the new laser, so it can slightly penetrate colliders, which could help in some cases, but this particular function cannot be added.
