### ISSUE TITLE
Document how to find tools

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#5]
I had this question, and so have others. Most VR experiences have these available within your controller menus. Neos replies on you to find them in-world and take them with you. This should be documented for new users.

**Comment by Frooxius** [comment]
Hmm, this isn't fully clear how to solve, because there's not one "official" version of the tools, as variants (or new tools) can be dynamically constructed or modified within Neos.

I will delegate this to another feature - the persistent user inventory. We could preload it with some commonly used tools, like a "starter pack", so users can bring those in. If they won't like those variants, they can throw them out and fill their own inventory.

**Comment by sirkitree** [comment]
I added this to the FAQ, but that could be updated since @Frooxius also added the main tool tips to the content hub as well
