### ISSUE TITLE
Grip pose TipReference moves grip pose visual.

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#509]
Grip pose visuals are incorrectly rotated/positioned when a TipReference is assigned to the grip pose reference. A tip is automatically generated on each grip pose reference that is rotated -90 degrees on Z, resulting in the grip pose reference visual appearing sideways.

The position of the grip pose reference is also affected by the TipReference.
![2020-05-06 17 08 44](https://user-images.githubusercontent.com/54213390/81249626-f173f000-8fd3-11ea-8e74-661658ba2f1f.png)
Issue reported by DeliriousJax.

**Comment by Frooxius** [comment]
This is expected. The TipReference is currently a hack to mimic the behavior of the old system based on the popular demand. The old system is not hand based, but controller based, which is why the hand reference ends up in a funny position.

Once there's a proper system for defining references it will handle this.
