### ISSUE TITLE
After spawning with no permissions to locomotion modules, receiving permissions for modules doesn't initialise them/make them available

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#530]
[In a recent video](https://youtu.be/sn1iF8zs5P4) I showed off the "Require Tag" feature of the locomotion permission system. 

During this video, I create a world where users spawn with a physical locomotion module enabled and permission-ed so that they can use it. They however cannot use the fly mode locomotion as this requires a tag.

After recording this video I decided to investigate disallowing ALL locomotion until the accept button(featured in the original video) is pressed so I copied the permission settings to the PhysicalLocomotion variant of the Whitelist. 

Now when re-spawning a user will be unable to move until they hit accept. However when a user spawns with no available, authorised permission modules and then later gains the permission to use some, it appears that the context menu OR locomotion systems do not update or engage.

The result here is that even though the user had no locomotion modules available, once they gain access to some they can't use them.

To me this seems like it MIGHT be a bug, i'm not sure. I've recorded an unlisted video explaining this issue visually which also shows a reproduction. I'd be happy to give the world orb to you for this in game too. I'll prepare that tonight. I forgot to save it in this setup. Here's the video: https://youtu.be/DIwEMwMawps

Additionally, as pictured in the original video, Locomotion modules I do not have the permissions for appear in the new context menu. This is somewhat confusing and doesn't match my expectations. If i don't have permissions for a locomotion module I would expect it to be missing from the selection.

I hope this makes sense, its a bit of a complex issue so please watch both videos above as they may help.

Thanks!

**Comment by shiftyscales** [comment]
I imagine that this could be potentially specific to the locomotion modes being in the context menu, and could be made irrelevant once locomotion is moved to a facet- but for the event it isn't, I've made some additional observations in case they apply more generally to the context menu:

It appears that the context menu is not properly updating the visuals but is properly updating the actual locomotion modules.

As demonstrated in Prime's video, and confirmed by myself- if a user has access to no locomotion options at spawn, their locomotion menu will not exist, and won't generate when they do gain access to locomotion. However- the locomotions and permissions are being properly updated.

To test- I had the locomotion modules require no tag, respawned, then applied the tag requirement. Modules that were not whitelisted could not be selected, and modules that were whitelisted for which I had the tag could also be selected (as expected.)

However- this exposed a few additional visual issues with the context menu:
- If a user is in a non-whitelisted locomotion module, all of their locomotion modules are grayed out/can't be directly clicked
- Despite being grayed out, they can still be clicked by dragging the center button towards them.
- If a user is in a locomotion mode they have access to, other locomotions aren't properly grayed out/the buttons can be clicked (although don't switch the locomotion mode (expected behavior).)

https://youtu.be/bn0VorP3EUE

**Comment by Frooxius** [comment]
I've made some changes in 2020.5.12.521 that should now always show the option if there are any locomotion modules available. Can you check if that improves things? 

If you can send me the world I can do some testing as well.

**Comment by shiftyscales** [comment]
The context menu now shows when access to a locomotion module is granted.

I don't have access to Prime's world, but I recreated it in a more basic form. To replciate the testing conditions, you just need to add the tag `test` to each of the locomotion modules under your user root you wish to gain access to.

neosrec:///U-Shifty/R-f39cf409-6071-4b74-8949-d69b3e55cfc9

**Comment by ProbablePrime** [comment]
Thanks for the updates, I got tired last night and was unable to prepare the world but it looks like Shifty's is a good replacement. I'll try out some things tonight.

**Comment by ProbablePrime** [comment]
Looks good, I am closing this issue :)
