### ISSUE TITLE
Can't save world orbs in another world

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#57]
Perhaps I'm doing something wrong, but I'm unable to take world orbs from the content hub and save them to my Local or Cloud Home.

Steps to reproduce:
1. Open the Content Hub from the main menu.
1. Teleport to the New section and duplicate a world orb.
1. Take this world orb with you back to your Cloud Home or Local.
1. Place the orb and hit Save on the main menu.
1. Close NeosVR using the Exit button on the main menu.
1. Re-launch NeosVR and note that the orbs are not present within your Cloud Home or Local.

If this works for you, consider that I've copied my Local to my Cloud Hub.

**Comment by sirkitree** [comment]
I had the idea that this might just be the particular orbs in the New section of the Content Hub having some property that made them unstable, and it seems I was right.

If you go to the actual world, use the main menu to get the world orb, take that to your Cloud Home or Local and save it, it will be there if you close and reopen NeosVR. 

So I'm not sure that this is a bug, so much as a usability issue. I can definitely see others collecting orbs form the New section of the Content Hub and being confused when they disappear.

**Comment by Frooxius** [comment]
Oh. This is because the world orbs are marked as "NonPersistent" by the script that spawns them dynamically based on the latest list of submissions anytime you enter the hub (or when it refreshes periodically).

If you open them with inspector, you should be able to see "Persistent" checkbox that's unchecked. This will exclude the whole hierarchy from being saved. User avatars/hierarchies use this as well, otherwise they'd get saved with the world too.

However I can fix it in this case, mark only the root as non-persistent. Meaning if you take them out of that hierarchy, they'll get saved.

**Comment by Frooxius** [comment]
Fixed now, pushed to nightly channel.
