### ISSUE TITLE
VR180 Projection Mesh

### ISSUE THREAD

**Issue by CuriousNicholi** [Frooxius/NeosPublic#580]
This isn't an issue, but more of a curious question.
Google open sourced VR180 about a year ago, complete with specs for generating calibrated stereo fisheye mesh projection. Could this potentially be integrated into the Neos stereo camera?

https://github.com/google/spatial-media/blob/master/docs/vr180.md#appendix-mesh-generation-demo
https://github.com/google/spatial-media/blob/master/docs/spherical-video-v2-rfc.md

**Comment by Frooxius** [comment]
Hmm I'm not quite sure if I entirely understand the request. I could add a procedural mesh that generates one based on those parameters that you could apply the video texture to for playback.

However there's no way to sensibly integrate that in the Neos stereo camera, since the camera itself is not rendering in spherical projection. Unless you want that to be added to the camera? That'd be a lot more difficult though, because rendering with spherical projection in realtime is not a trivial change.

**Comment by CuriousNicholi** [comment]
I certainly don't want to request difficult changes. I'm just a big fan of the format and dreaming about possible applications for mixed reality. Thanks for the response!
