### ISSUE TITLE
Headless disconnecting all users randomly

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#587]
Zane#0529 and I have encountered an issue with Headless, occasionally if there are too many users it'll randomly disconnect everyone from the session, according to Zane the console is still running and operating perfectly fine, but still shows that users are connected despite not being accessible from the Session Lists. Log files from Zane's headless are attached below if needed (Provided through Google Drive, the file is 36MB and has almost half a million lines).

**Comment by Hayden-da-Serg** [comment]
https://drive.google.com/open?id=1B8A251tNWND4xUn4OEC6uD87IpDjFO2O
(Accidently entered)

**Comment by Frooxius** [comment]
Do you have more logs? I don't see too many sudden disconnects in the one provided, but there seems to be a few around the same time that a asset download times out, which suggests this is a network issue.

**Comment by Hayden-da-Serg** [comment]
You'd have to ask Zane, he provided the files, as it was hosted on his headless. Cyro has reportedly encountered this issue as well so he may have some information.

**Comment by RileyGuy** [comment]
https://cdn.discordapp.com/attachments/619845139770376192/714547506398101544/cyro-anarchy-server_5_23_2020_11_22_56_PM.log
https://cdn.discordapp.com/attachments/619845139770376192/714547510122774639/cyro-anarchy-server_5_24_2020_4_57_16_PM.log

Here are the logs from my sessio that's doing the same thing.

**Comment by Frooxius** [comment]
@RileyGuy Looks like it's a networking error. Your system probably briefly lost connectivity. It's failing establishing network connections to the DNS server to complete the HTTP API requests and since the people seem to drop out at the same time it would suggest that the whole network has dropped for a bit.

**Comment by shiftyscales** [comment]
Cyro's closed the headless immediately after it dropped everyone's connection, and provided this log: https://cdn.discordapp.com/attachments/619845139770376192/717286133201109002/cyro-anarchy-server_6_1_2020_8_54_09_PM.log

What mostly stands out to me right at the end of the log is `2:55:51 AM.269    LNL_Listener NetworkError, endPoint: , socketErrorCode: 10035`
Apparently this error is thrown when the socket's send/receive buffer is filled, blocking the connection as a means of rate-limiting. Reportedly increasing the buffer size can help.

Although since it's also supposed to send the data when it next can- perhaps there is an underlying issue that is exposed here where it is overly sensitive to dropped/delayed data of some kind?

**Comment by shiftyscales** [comment]
From a log collected from a client that was in this server at the time, all that is shown:
`09:57:31.313 ( 47 FPS)	Disconnected: , reason: Timeout, socketErrorCode: 0`
So the peers are disconnected from the host possibly because of the 10035 socket error.

As for the exact cause for _why_ that 10035 socket error is thrown by the LNL_Listener, I'm not yet certain, @Frooxius.

**Comment by Frooxius** [comment]
10035 can happen for lots of different reasons, so it's hard to say. My guess would be that either Mono or the networking stack on particular Linux distro he's using has some differences in the UDP socket implementation that makes it fail with this code, since this has never happened on Windows. 

I could check if it's possible to skip this error without corrupting the state of the networking, but I might need more information.

**Comment by RileyGuy** [comment]
Just crashed again was fine until more people started joining: https://cdn.discordapp.com/attachments/619845139770376192/717946454198583366/cyro-anarchy-server_6_3_2020_6_30_54_AM.log

**Comment by Kal47** [comment]
Here is the log from the headless, I joined then another joined and about 30 seconds later I got disconnected https://discordapp.com/channels/@me/656434079008423949/717955958650830879

**Comment by shiftyscales** [comment]
Closing out this issue as it's been a few months since I've heard of an active case of it occurring. If it comes up again, this issue can be re-opened, ideally with replication steps.
