### ISSUE TITLE
Remote tool equip without grip

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#603]
Proposed by Runi#1730 on Discord, and matching my experience, it would be a nice QOL change to be able to equip tools/gadgets in world by opening the context menu while the laser is hovering over the tool, rather than while gripping it.

This would streamline the remote equipping process, and make the context menu function more in line with other behaviors. (Perhaps if the tool is clicked on, it opens a context menu similar to avatars, and world orbs to interact?)

**Comment by TehTurk** [comment]
Hmm I remember reading this but thought it was also one of those new things that people aren't used to controls yet. In terms of tools I figure typically you want to have people focus on grabbing it, because not everything will be like this (grabbable, sliders etc), it would have everyone focus on using only lasers vs the physicality of some things.

**Comment by shiftyscales** [comment]
My main concerns in this particular interaction lies in consistency, as well as ease of use. Context menus as a concept didn't exist prior, so where possible if it's not an interaction that will conflict, it can be good to make use of them for context-specific actions.

E.g. as noted, with avatars, you can click to equip them via context menu. So being able to click on a tool in the world to equip it seems a natural step for equipping tools lying in the world too.

I think it would also feel really nice as far as inputs go, especially on Index controllers where you need to physically squeeze your hand whilst still manipulating the context menu, etc. It's not as though adding this new method of equipping would necessitate the removal of the other means by which users can equip tools either.

It's an option- and one I think will feel really nice if it is implemented.

**Comment by TehTurk** [comment]
No I get where your coming from and I agree, but this is also more of a design/implementation question, do you want users grabbing more.or lasering more. So this is def a Froox Input kinda thing. Sometimes it's just easier to go up and grab something you wana use. It still in VR to some degree :0, usability vs feel. Because there are some behaviors we can't exactly disable.

**Comment by Frooxius** [comment]
Added in 2020.5.28.1239 thanks!
