### ISSUE TITLE
[Feature Request] [Logging and Reporting] Add a link between the user's IP and the user's name in the logs.

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#608]
There doesn't seem to be a way to link a user to an IP address in the logs, and disconnect messages are only shown as IP address. These two things together make it very difficult to tell from the logs if a user has actually disconnected or not from a logs-only review.

If possible can a section be added to the "Verifying Join Request." message saying the IP? I get that it seems the "Peer Connected" message and the join request happen at about the same time, but I've got a log here where two connected's happen at once, and the join requests happen a moment later and it's not really possible to tell which matches to which.

**Comment by Earthmark** [comment]
#610 would also resolve this, as it would provide explicit leave messages so pairing the IP address to the user wouldn't be needed.

**Comment by Frooxius** [comment]
Sorry, the logging is an internal function and it can change at any time, I don't plan on spending significant development time for those functions (it's not possible to just include the username easily, because it's not known anymore at the time of the disconnect). 

Linking it together is trivial though, just use a search function in a text editor like VS Code, Sublime and so on.
