### ISSUE TITLE
Laser gripped objects flip 180 degrees when rotated by wrist

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#638]
Steps to replicate:
- Grip an object with the laser
- Rotate the object approximately 105 degrees in a single turn

**Comment by Frooxius** [comment]
This is expected behavior, the wrist turning is implemented so it directly translates to object turning angle, but the angle is halved so it's not too sensitive. This means there's a half-way point where it will snap 180 degrees to the other extreme. 

The wrist turning is for fine adjustments, if you're twisting your wrist that much it's better to use the joystick.
