### ISSUE TITLE
Lasers/Context menus not transferring properly on avatar switch

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#639]
This is a fairly random bug but it seems to happen more in headless servers from what I remember during my tests. Lost a few notes due to a computer hitch. I have a few logs where the bug happens, will send them in.

It seems the lasers are not being removed properly from the old avatar and generating in the new one, causing the lasers and context menu to appear from the unequipped avatar's hand when activated. Sometimes it happens with one hand, or both hands. When this bug happens when an avatar is switched to directly, it causes an exception and makes the user respawn.

**Comment by H3BO3** [comment]
I am unsure if this is a related bug, but I see some laser offset exceptions in the logs - Sometimes laser tip offsets break for tools like the tipref is not being respected. If this is not related I can open a different issue and do some more testing tomorrow.

**Comment by Frooxius** [comment]
That's really strange. Is there a way to make this happen? Are you doing anything special with the laser or tooltip anchors on the avatar?

The log you provided only has aftermath, after it already breaks, but it's technically correct behavior - the system detects you're corrupted, making you respawn.

I'd need to know what leads to this behavior in the first place. Is it still happening on the latest build too though? There was a bug with headless where CommonTool would get corrupted (but only on headless sessions) which was fixed since, so that might be a potential cause.

**Comment by H3BO3** [comment]
It seemed fairly random to initiate, but the first cases were noted with it happening on switching into head-and-hands avatars from a regular avatar on a headless session. With further experimentation it randomly happened across a wide variety of avatars with no strange modifications, I have not been able to experiment with it on the new build but I will try when I can.

Were the exceptions prior to the one that caused the respawn no good? They should have occurred during just switching avatars in-world and having the lasers stick behind, doing that didn't cause a respawn.

**Comment by shiftyscales** [comment]
As far as I'm aware this issue is resolved. Feel free to reopen it if it comes up again.
