### ISSUE TITLE
Private UI Items are hard to click

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#641]
With the recent build, It has become increasingly difficult to click private UI items. Examples include the dash, inventory and other window Icon buttons(Close pin etc) and the volume selector.

I'm not entirely sure what's up or how to provide additional information. Several users at the educational meeting today agreed it was harder though. I'll capture some footage when i get the chance thank you.

**Comment by shiftyscales** [comment]
This is because of this fix #628.

Are you/other users soft-pulling your triggers/keeping your lasers active while running your laser over the private UI? Lasers auto-activate on private UI, so you could either click fully to activate the lasers (if you need the visual), then hover over the private UI, or just hover over the private UI.

**Comment by ProbablePrime** [comment]
Lasers were fully activated with a fully trigger pull and i was trying to do move my hands in all sorts of ways to activate the buttons with much difficulty.

**Comment by shiftyscales** [comment]
What platform/controllers are you/others having this issue using?

**Comment by ProbablePrime** [comment]
Index, Vive Pro Eye with Index Controllers

**Comment by shiftyscales** [comment]
Hmm... That's really odd, then. Maybe it's muscle memory messing things up? I had noticed the same thing last night until I made the connection it was because I was activating the worldspace lasers via soft-pull. After that, once I was aware of how that worked, I didn't have any subsequent issues.

I know exactly what you're talking about, but I wonder if there's an underlying factor at play, e.g. trigger drifting, or something? Are/were your lasers active/white while you were trying to interact with the private UI?

**Comment by Frooxius** [comment]
Hmm. Was the laser activated with trigger press in world-space before you moved it over private-UI space?

I think that might be the protection against the tool being currently in use like @shiftyscales mentioned. Right now it just checks if the trigger is released when you start hovering over private UI.

I could make it so it only checks that if you're actually using a tool, but that's a bit tricky on itself, as the behavior would still be there if you equip a tool (although then again, you have the laser constantly on, so you shouldn't be holding trigger to keep it activated).

**Comment by ProbablePrime** [comment]
Let's wait till i get some footage here, I want to be sure we're all talking about the same thing. I'll get some recorded today.

**Comment by Frooxius** [comment]
Oh right of course! We'll wait for the footage, thanks!

**Comment by shiftyscales** [comment]
Not sure if it's related to Prime's issues, but another issue that was highlighted to me by Madmaxkz was that scrolling events on private UI can be interrupted by objects passing through, and interrupting the laser. This doesn't occur during the soft-pull. While soft-pulling the laser will pass through the object without issue.

https://cdn.discordapp.com/attachments/598212542938218506/717875493394710619/2020-06-03_15-55-20.mp4

**Comment by shiftyscales** [comment]
Having gathered feedback from other users- I think one of the main underlying issues is in the fact that many users don't tend to fully release their triggers between clicks.

As an example- if you click on a field in an inspector panel, the keyboard pops up, but while the keyboard is open, you can't click on it until the trigger is fully released. This change seems to be tripping up a lot of users- likely because of muscle memory built-up for only releasing their triggers as much as they needed to before rather than releasing it all the way.

**Comment by SHFRH** [comment]
I think that might explain why I was struggling also (don't fully release the trigger) - Will try that. Thanks ^H^

**Comment by ProbablePrime** [comment]
Fully releasing the trigger will ensure a successful use of private ui for me. This does feel a little odd though. Doing quick operations in private UI is more difficult etc. 

Keyboards, folder management etc.

**Comment by shiftyscales** [comment]
I wonder, then, if it could be preferable behavior that the new behavior only be applied during the full trigger click?

That would take care of the initial issue with brushes, and the Logix tip getting interrupted, as well as scrolling on private UIs, but will also account for public to private transitions. E.g. inspector to keyboard without the need for fully releasing the trigger.

It would mean that something could interrupt your laser prior to clicking, but I think that would be an acceptable tradeoff since you aren't in the middle of the actual click event yet.

**Comment by Earthmark** [comment]
I recorded a video about my experiences with this UI behavior, I noticed a new player was also having an issue with this so some way to show that a full release is needed may be useful.

Here's the video, it's very stream of consciousness https://www.youtube.com/watch?v=UU6jFot206s  I honestly learned a lot about the behavior while making the video, and that shows. This is possibly how someone who notices the behavior will experience and try to learn it (and become confused at times by it).

There are also two possible bugs near the end, I have tags in the video for when the behaviors occur.

**Comment by Frooxius** [comment]
I'm tweaking the behavior a bit, but this is a tricky situation. This is unfortunately mutually incompatible with the userspace interrupting some of the tools. Either it interrupts the tool interaction and is easier to interact or it doesn't and you have to fully let go first.

I can set the threshold much higher (or to a full click), but this won't work with brushes in particular, because there the trigger press determines the width of the stroke, so if you were making a thin line it would get interrupted anyway.

Another option would be to have an override per-tool and have the threshold much lower for brushes specifically. This could help, but it's going to be more work specifying the right threshold for tools, although I think only mostly the brushes really need it.

**Comment by shiftyscales** [comment]
The brushes, and the Logix tip were the main places I've seen this come up. The Logix tip would be full-click as it was dragging out wires from nodes that was being interrupted.

For brushes- as you noted, the trigger strength is variable, so they would need a wider range ideally.

Otherwise, full-click covers most other scenarios previously mentioned.

**Comment by Earthmark** [comment]
I've noticed that some tools (at least when using @H3BO3 's tooltip so the normal tools may work just fine) don't go onto the tool shelf very well if at all, maybe it could be considered a behavior of some tools that they just won't respect private UI some times? Like with a logix tooltip, when it's dragging a wire it won't try to connect with UI at all.
With a brush, it just won't connect to UI ever unless you let go first?
I don't know if these are good ideas or not, but at least in my experience so far being able to classify a tool as "Just drop it first manually" is annoying, but it's far less confusing than my lasers seeming to not work randomly and I didn't understand why.
The first case made it clear that a behavior was different by there not being a laser connecting to my tool shelf, and I had a direct workaround of dropping the tool first and placing it there manually.
The laser thing I often don't have a workaround, and I didn't understand why it was happening.

Honestly I thought it was a collision box issue until I saw this issue, I kept moving private UI items lower than the hand I was selecting them with because I thought private UI items would only respond well to downward facing lasers, and even then it was iffy. Now I realize though it was lots of confirmation bias and my hand probably relaxing fully when reaching up.

**Comment by Frooxius** [comment]
I rewrote the mechanism a bit in 2020.6.5.201! Tools now actually provide their own state, whether they're in use or not. By default that's being the trigger fully pressed for all tools, except for brushes, which use the brush-specific logic on whether a stroke is currently being generated.

This should make the private UI easy to use again, while not interrupting brush strokes with private UI. Thanks for feedback!
