### ISSUE TITLE
Default session privacy to Nobody/Invite only for "Busy" status

### ISSUE THREAD

**Issue by peterthethinker** [Frooxius/NeosPublic#652]
I am at the end of my rope here

 If i am in  paid work mode I dont ever want to see a status message from people.
sorry  the pop ups are distracting 
and every map I  start needs to default to  
Do  not show in lists and  
do not allow any one to join. 
its a   fail safe.  
as far as  ever one else is concerned I am NOT on neos .  
If for some reason I want to have people come in Ill  per session  open up the world as need be . 
Iam duty bound to keep  some of my paid commercial work  under NDA .

**Comment by ProbablePrime** [comment]
Setting yourself to Invisible should do this no?

**Comment by peterthethinker** [comment]
It does not.  

cause  Invis Still lets  the pop ups    blast my work space

i dont care who is joining   every 20 Sec . If I want to know Il check my friends list.

**Comment by BlazeVR** [comment]
Busy status is hiding popups, although invisible shows up popups.

From Froox's older update post
> -- When Busy you won't receive any notifications
-- When Invisible you will show as Offline to everyone and all your sessions are Private by default

**Comment by peterthethinker** [comment]
blaze ... I am the one who asked for the 4 balls in the 1st place.  I am fully aware!

the problem is busy  still  defalts to  open sessions and  lists

**Comment by peterthethinker** [comment]
Right now the only fix is to de-friend every one  and  then use Inviz mode. 

not practical at all

**Comment by shiftyscales** [comment]
If you save a copy of the world with "don't show in session lists" enabled, it will always be private by default if that helps, @peterthethinker. "Don't show in session lists" is a property that saves into the world itself so each time you start that world, "Don't show in session lists" will be enabled until explicitly turned off by you.

If you start a custom session from the world orb, it will also allow you to specify the private session state, so you can always ensure the session is set to Nobody/Invited users, even when you are set to 'busy'.

As noted above, being 'busy' will mean that the popups don't appear.

With the UI update, it'll be possible to customize your UIs, and other such properties, so you could have a 'work mode' loadout for your UI.

**Comment by peterthethinker** [comment]
so Our busy mode is  half baked .  

got it

My fix will have to be a mass unfriend.  sorry but this is  kinda  silly . when  clearly  we can tie a  status to trigger in the software a  session lockdown. 

If we can tie  Inviz  to do this . is there a  good technical reason  why this cant also  stop  pop ups .

**Comment by shiftyscales** [comment]
I think the fix best fix would be to set the default session privacy for opened worlds to invite only/don't show in session lists for 'busy' which makes sense given that if you're busy, you likely won't want users joining your session by default unless you open it up anyway.

Once the UI update is out, it'll eventually be possible to have a work loadout that hides the popups, etc. And possibly set you to busy by default.

**Comment by ChrisWarner103** [comment]
I completely understand what Peter means by this. When I'm working on my D&D stuff. It's one of those things where I can't let anyone see it and sometimes when I open a world it'll set it to public and someone will join and I have to as much as I hate doing it, tell them to leave.
 I have to check every time I make a world now just in case it makes it public. I set myself to busy so that I don't get disturbed by countless people coming online.

Having a way where when you go into Busy mode and puts the world you are in private/invite only state would be amazing and certainly make a lot of peoples lives easier when they're working on something others can't see and don't realize their world just opened in public.

Also, I get that invisible mode is a thing, but sometimes when I am working I get people messaging me and when I have the time to rest/take a break I will reply to them

**Comment by Frooxius** [comment]
I'm sorry to hear that this had such a strong effect on you. Originally those two options are separate modes, the busy one to hide notifications, but still participate in worlds and invisible just to hide that you're online at all, but still see what's going on.

I plan on expanding the notification options with the UI redesign, which will have more fine-grained options. For now there are two options that we can tweak:

- Make Busy also start worlds as private by default
- Make Invisible hide notifications

I'd definitely go for the Busy option, as Invisible is sometimes used when  you want to join worlds and socialize, but don't want people messaging you or following you.

**Comment by shiftyscales** [comment]
Yeah- based on those use-cases you outlined, it sounds like both of those tweaks could be really nice to make, @Frooxius.

**Comment by peterthethinker** [comment]
Hola.   Yes Froox . If busy also made all sessions a user spawns as  Pvt  that would be awesome!!

**Comment by Frooxius** [comment]
Both? I was proposing only one of those. I think hiding notifications on Invisible would not be a good idea, because it's often  used when you do want to socialize and be reached out by other people, but you don't want them to actively follow you.

**Comment by shiftyscales** [comment]
I'd agree that busy would be the better status to tweak. I had just noted that you had mentioned: "don't want people messaging you" in referenceto invisible- and if that's the case, presumably you might not want to see the pop-ups either?

Either way, changing busy makes a lot of sense, because if you are working, presumably, you won't want an open and joinable session, and if you only wish to modify one, that is the best one to modify, @Frooxius.

**Comment by Frooxius** [comment]
Ok changed in 2020.6.8.518, busy will now start all sessions as private, just like invisible does.
