### ISSUE TITLE
[BUG] "Glossy" effect mismatched between eyes, or just outright glitchy

### ISSUE THREAD

**Issue by TiagoTiago** [Frooxius/NeosPublic#657]
![Screenshot](https://user-images.githubusercontent.com/194285/83957373-ebd22a00-a85f-11ea-94e1-e07f3f9311be.png)

In various objects like the floating cubes around the home environment, the information panels in the tutorial hall (sorry, forgot what it's called), and on GUI panels, this glossy effect mismatches between each eye, and often looks like it's just repeating what's on screen but with some offset and occasionally somewhat scrambled.

Running on Linux Mint, with a GTX 1070, SteamVR version 1.12.5

Lemme know what other details you need, or if you need me to perform any specific tests.

**Comment by TiagoTiago** [comment]
Pinging @Earthmark as requested in-world

**Comment by shiftyscales** [comment]
If you are familiar with the MaterialTip, and DevToolTip, it would be beneficial to have a list of the materials/shaders for which you observe these issues, although having a list of places they can be observed works too.

There are some shaders that don't compile, or render correctly under the Linux build, e.g. Flat Lit Toon. Some of these shader issues can also be observed on the Quest/Android builds too.

**Comment by Frooxius** [comment]
This is normal. The fake refraction shader isn't designed to be physically accurate, it only warps the existing rendered data of things behind it based on normals and relative position, which is why it will differ between eyes, or produce the pattern that repeats what's on screen (it's because the refraction reaches the end of the edge of what's currently rendered or has a normal that causes a stretch from particular viewpoint.

**Comment by TiagoTiago** [comment]
The thing is it's not doing it to things behind the objects but in front; notice on the screenshot, that mug is in front of the GUI panel (I've had even my avatar's arm showing on one eye at a time, with a lucky angle there were even two copies of the arm on the panel, just visible on a single eye; I don't have a screenshot with the arm because I couldn't work out how to work the keyboard to call for a screenshot while having my hands busy and the headset on).

**Comment by Frooxius** [comment]
That's still normal. The refraction shader cannot really tell what's in front of it or behind. The way it works is that all opaque objects are rendered first. That image is captured and stored as texture. 

Then the transparent objects (including this glossy effect) are rendered. The refraction shader uses the texture from opaque render to do this kind of "fake refraction" effect, but due to its nature it will "refract" things that are in front of it as well.
