### ISSUE TITLE
Add one more length in the arm bone chain so shoulders can move.

### ISSUE THREAD

**Issue by RileyGuy** [Frooxius/NeosPublic#664]
I've noticed that the shoulders in neos seem to be locked in place. This leads to some unnatural behavior in arm movement where on some models the arms only reach the correct length at the sides and not in the front. When you move your arm out in front of you in real life, you shoulder commonly moves forward so you can reach, in neos the shoulder is locked in place and doesn't reach with rest of the arm resulting in the arm not reaching the correct amount even with height compensation.

**Comment by H3BO3** [comment]
Stiff shoulders have been a problem with neos' IK for a while now. It'd be really nice to see them fixed! Perhaps the forearm roll bug could be fixed at the same time

**Comment by Frooxius** [comment]
I'm sorry, but adding more to the arm bone chain is not possible, that would require the chunk of the IK to be redesigned and rewritten and it wouldn't match how most rigs are anyway (they don't have extra bone in the chain in the first place, so there would be nothing to map it to, further complicating the IK), so that won't be implemented.

The shoulder is simulated, but specifics will depend on your rig and settings. I recommend playing with the shoulder settings on the VRIK component.
