### ISSUE TITLE
Playback -> Set Speed doesn't work

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#665]
1. Spawn a video or audio clip
1. Wire up the "set speed" node to either
1. change the inputted speed value to uh basically anything
1. Fire the pulse
1. Observe nothing changes

I've tried this with both an audio clip and a video clip. 
I've tried various speed values. 

On video clips it seems to create short repeating loops of segments of the video clip that slowly progress through the video repeating each short segment a few times before advancing.

**Comment by mralext20** [comment]
my best guess is that the setspeed node is ment to accept an `Animation`, but accepts any `IPlayable` instead

**Comment by H3BO3** [comment]
SetSpeed isn't meant for audio, just animations, I believe. There's no way to change audio playback speed yet, I wish there was though

**Comment by ProbablePrime** [comment]
The same for video clips too? Hmm, interesting. Id suggest adjusting its typing information then so that users are not confused.

**Comment by Frooxius** [comment]
Currently changing speed for audio and video isn't implemented yet. Implementing it for audio is relatively easy (it will still take some time to implement though), if you need that I could implement it (although note that it means the pitch will change).

For video it's a bit trickier, as it depends on the video playback engine and video playback doesn't deal as well with changing speed (especially faster than normal). That's why you're seeing the weird behavior, because the playback engine is just jumping around the timeline at different speeds. 

It should work correctly for animations though, which have support for variable playback speed implemented.

**Comment by H3BO3** [comment]
Changing playback rate (and thus pitch and speed) is exactly what I've been waiting for for a while now - However, my applications for this necessitate being able to drive the speed property for smoothly pitching audio on, say, a vehicle engine or similar. I am unsure if Prime's application is different but if it is exposed as a field in the player that would be very useful and would work on a write basis as well

**Comment by Frooxius** [comment]
The system is designed so you can drive the speed and all other parameters, so you'll be able to do that regardless. Any playback in Neos is built around "Playback" structure, which is a special kind of field for abstractly controlling playback.

However things that use this structure need to implement different behaviors, e.g. sampling audio at different speed based on what the Playback structure determines.

**Comment by Frooxius** [comment]
Changing audio clip playback speed is now supported thanks to the new audio system in 2020.10.25.915!
