### ISSUE TITLE
New Equip System Faults

### ISSUE THREAD

**Issue by Shalefoot** [Frooxius/NeosPublic#673]
_Please know that everything stated is meant in good faith on behalf of the Neos community and platform._ 

**What is the issue I am presenting today?**
The equipping system within NeosVR has been a crucial part of most props on the platform whether they are...

-_weapons_ (guns, knives, etc.)
-_silly props_ (such as the frying pan or the puppets)
-and _general tools_ (grappling hooks, jet-packs, etc.) 

The more recent update that revamped this system has made for some undesirable changes to this system. While over-all it should be more effective at auto-equipping more frequently-used and passed about items, as well as adjusting to the scale of a user's hand, a lot of items has suffered as a result. It has made some worlds — such as the "Huge Mountain" world by Coffee — much more difficult to navigate (as there is not a permission level high enough to enter [Edit Mode] or make manual adjustments through the inspector). 

**To my personal understanding and testing, this means that any world in which a user does not have permissions for [Edit Mode] or the inspector cannot adjust the positioning of an equippable item/object in their hands.**

I have brought in a few friends to Neos over the past week, and I have had to state several times that unless I offer them higher privileges in a world (in which, I am not always comfortable in doing depending on the circumstances), they cannot fix the awkward positioning of the items/objects they try to equip and play around with.

Due to the fact that it is nearly impossible for all creators to be proactive or cognizant of the fact that their equippables, whether old or new, are broken — I'd like to implore and encourage that an ability for the user to grip the equippable in hand be returned or reformed to some degree to allow users to adjust their own interactions/use/experience in the game without this handicap.

![2020-06-12 01 21 57](https://user-images.githubusercontent.com/66750708/84467957-a17bef00-ac4b-11ea-870e-dd7049175561.jpg)
![2020-06-12 01 21 50](https://user-images.githubusercontent.com/66750708/84467955-a17bef00-ac4b-11ea-9faa-f14a72996b25.jpg)
![2020-06-12 01 22 13](https://user-images.githubusercontent.com/66750708/84467953-a04ac200-ac4b-11ea-8d7b-85bf95d59268.jpg)

**Please consider making this change. Thank you for reading, and please have a wonderful day. :)**

**Comment by TehTurk** [comment]
I know being able to adjust in hand was something that was missed when we upgraded to the new system. The edit mode adjustment was something of kinda an inbetween the old behavior and the new behavior. But the question is if this should be something that should be warranted as it's somewhat also up to the map creators/content makers to update their stuff. Anything newer doesn't have this issue because typically the grabbing system is already considered in mind while the older content didn't, but it's also more of a growing pain for Neos as a whole too.

**Comment by Shalefoot** [comment]
> I know being able to adjust in hand was something that was missed when we upgraded to the new system. The edit mode adjustment was something of kinda an inbetween the old behavior and the new behavior. But the question is if this should be something that should be warranted as it's somewhat also up to the map creators/content makers to update their stuff. Anything newer doesn't have this issue because typically the grabbing system is already considered in mind while the older content didn't, but it's also more of a growing pain for Neos as a whole too.

I figured this issue would not be exhibited in newer content — but the point still stands that not a lot of old creators know their old content is broken, and some do not care to fix it (same goes for some map creators out there). While new users have the opportunity to garner some experience in how Neos functions by attempting to fix it themselves — the point still stands that in certain worlds they just don't have the permission to do so (and some worlds won't permit them to save the item/object to bring out of world and adjust it elsewhere).

For me, personally, being able to grip and move the item/object with my other hand takes _seconds_ while this new method is more time consuming. Again, while it does implore me to learn some new techniques and be able to aid other individuals who encounter this issue — it is not convenient for new users or those primarily focusing on socializing and goofing around. I'm sure the issue will dwindle away over time, and I do intend to find out what ways I can help out on the platform — but I still for-see this to bring up complaints in the near future.

**Comment by shiftyscales** [comment]
Being able to move tools around without builder perms is something I would also see implemented with the new UI, @Shalefoot. This has been previously noted in another issue- #633.

I proposed that a "Lock/Unlock Tool Positioning" facet toggle could be beneficial. It would allow users to reposition any tool just like they could on the old system (and by keeping it permanently unlocked, would act just like the old system), especially if the user is also able to grip to resize the tool, which is also been another highly requested functionality.

Hopefully this is something @Frooxius will consider. In having a facet to unlock tool positioning, and scaling, it will become much quicker, and easier to reposition tools, toys, and gadgets, just like on the previous equip system.

**Comment by TehTurk** [comment]
I mean I know I often see facets as the end all be be all, it's tied to the Grabbable or Tooltip components :o, but if your able to adjust those or at least the behavior of them within it it'd be interesting, but wouldn't more editors and collection oriented requirements be needed first?

**Comment by Frooxius** [comment]
Sorry this took so long to address, I needed to build more parts of the new UI system to have the pieces ready for this.

In build 2020.7.11.1366, the editing of the pose is now tied to the UI Edit Mode instead. I've also reworked it a bit so it can be toggled on and off on the fly without needing to equip/dequip items and fixed some other glitchiness.

Overall this should make it much easier to adjust the positioning of the old items.

Unfortunately many of the old items still won't position themselves correctly, simply because they were never setup properly in the first place and the old system wasn't designed to handle this properly, so there's not enough information to auto-upgrade them. The new one is designed to avoid this kind of scenario.

Thanks for the feedback though!
