### ISSUE TITLE
Mechanism to propagate nameplate changes to active sessions

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#681]
A mechanism to propagate nameplate changes to active sessions helps in a few cases, most notably for new users logging in for the first time, and for new Patrons who pledge while Neos is running.

**Comment by Frooxius** [comment]
Sorry, this won't be implemented. For users who logged in, this is not possible for security reasons, because they're not authenticated in that world.

Whenever user joins and they're logged in, Neos performs a secure handshake first during the connection itself to authenticate the user that's joining, so all subsequent communication can be sure that the user is who they say they are.

This would require some mechanism to somehow perform this handshake after they joined, which would add huge complexity and potential security holes. User logging in while they're mid-world isn't something that's common enough to warrant that.

For Patreons that's technically possible while in worlds, but it's still not something I'd add, as it would require some mechanism to get notified in realtime about it. This would mean more complexity and potentially a lot more load on the cloud server, for something that's rare occurrence and can be solved by simply respawning.
