### ISSUE TITLE
Trigger on Vive controllers makes flying faster but walking slower.

### ISSUE THREAD

**Issue by SHFRH** [Frooxius/NeosPublic#691]
Trigger on Vive controllers makes flying faster but walking slower. 
This seems very odd to me and I wonder if it would be easy to allow users to choose by entering a negative speed exponent value or something? Thanks, ^H^

**Comment by Frooxius** [comment]
This is intentional. It's unfortunately a sort of "ad hoc" solution due to the limited nature of the Vive controllers.

Typically Flying is used to get around the scene quickly when building and so on. You typically reach much higher speeds with flying when trying to cover large distance, which is why it speeds up. If it was reversed,  you'd be zooping around at crazy speeds unless you held the trigger.

The walking is a bit different. Normally you want to walk at your normal speed, but slow down for precision if you are aware of this behavior. Especially for users who don't know about this mechanism, it makes both of those modules still usable - they don't walk too slow and they don't fly too fast.

It's kinda tricky making setting for this. It could maybe be made, but it's already kinda "hacky" so it's unclear what exactly would the setting do?

**Comment by SHFRH** [comment]
Hmm, I guess I was thinking that it would be great if one could set a fly speed and a walk speed and have a trigger 'speed exponent value' for each where pulling the trigger with a positive setting would go faster and with a negative setting would go slower. 

With that it would be possible to keep the behavior you  are describing above but also to set it so that the trigger makes both go faster (or both go slower, etc.) but I understand if that seem too hacky ;) Thanks, ^H^

**Comment by Frooxius** [comment]
That's a bit complicated. Typically Fly locomotion doesn't have a speed limit, so you can fly as fast as you can, so there it's fine, it can either slow down or speed up.

However for locomotion, you can only go as fast as it specifies, so if you wanted it to speed up instead, it would have to be adequately slowed down, so when you speed up you don't exceed the max velocity.

Negative exponent wouldn't really work unfortunately, as that would technically make you move backwards instead. There could be some settings, but I'd need to engineer them a bit so it doesn't break the rest of the system.

**Comment by SHFRH** [comment]
I see, I guess it must be ages since I did much walking - mostly for videos.
(previously I think pushing further forward on the Vive track pad walked faster)

Will try to get used to trigger being faster fly and slower walk. 
I guess this is closable then - thanks a lot for your answers ;) ^H^
