### ISSUE TITLE
Replace OVRLipSync Library

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#702]
The existing OVRLipSync library has had numerous performance issues anytime it is upgraded to the latest version, and even on the best known working version, has shown signs of exhibiting performance issues.

It would require profiling, but I suspect it is also likely responsible for the CPU scaling issues that are present when multiple users are in a world based on prior experience in seeing high CPU time in process explorer associated with ntdll.dll and OVRLipSync.

This particular library is also incompatible with our Linux build as per #149.

Some stack traces that can be seen in high (~15) user sessions.
```
0x0000000000000000
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0x31372
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0x2ead0
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0x2aab0
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0xe2af
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0x50a79
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0x19931c
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0x160e89
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0xe7498
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0xe6de4
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0xe7116
OVRLipSync.dll!Ordinal0+0x20858
OVRLipSync.dll!Ordinal0+0x20793
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0x7502c
OVRLipSync.dll!Ordinal0+0x1c0fd
OVRLipSync.dll!Ordinal0+0x1ba61
MSVCP140.dll!Concurrency::details::_Schedule_chore+0xd8
ntdll.dll!TpReleaseWait+0x54d
ntdll.dll!RtlInitializeResource+0xce4
KERNEL32.DLL!BaseThreadInitThunk+0x14
ntdll.dll!RtlUserThreadStart+0x21
```
```
0x0000000000000000
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0x8f39d
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0x50a6e
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0x19931c
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0x160e89
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0xe7498
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0xe6de4
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0xe7116
OVRLipSync.dll!Ordinal0+0x20858
OVRLipSync.dll!Ordinal0+0x20793
OVRLipSync.dll!ovrLipSyncDll_ProcessFrameAsync+0x7502c
OVRLipSync.dll!Ordinal0+0x1c0fd
OVRLipSync.dll!Ordinal0+0x1ba61
MSVCP140.dll!Concurrency::details::_Schedule_chore+0xd8
ntdll.dll!TpReleaseWait+0x54d
ntdll.dll!RtlInitializeResource+0xce4
KERNEL32.DLL!BaseThreadInitThunk+0x14
ntdll.dll!RtlUserThreadStart+0x21
```

**Comment by Frooxius** [comment]
Replace it with what exactly though? There aren't any viable alternatives that I know of. It has its issues, but it's also the only library that actually does what we need it to do right now. Unless you have some good alternatives, I'd close this, since it's not really something we can do.

**Comment by shiftyscales** [comment]
I feel like it should be a long-term goal. This issue isn't really meant to be something to be addressed now. Mostly just logging it for the eventuality that a solution of some form comes up in the future- whether that's the library itself improving/becoming multi-platform, or an alternative being discovered somewhere.

If you feel that this issue isn't worth keeping open, that's fine. It isn't something I'm looking to have you fix now, or even soon, @Frooxius.

**Comment by TehTurk** [comment]
Question, does the lipsync run only locally? I would think the stream data from each client is synced and not processing the daya for the audio on each component right?

**Comment by H3BO3** [comment]
Pretty sure it has to run for everyone to keep in sync for the audio being received. This may also be a contributor to multiple full-IK users in a world causing performance degradation - Think about it, most head and hands avatars don't have visemes and thus no lipsync.

**Comment by Frooxius** [comment]
I see. Thanks for logging it, but I'm going to close this one. It's not something that's actionable, unless someone releases a better library as some point in the future. OVRLipSync is the currently best available solution and I don't have plans to replace it right now. 

I think it's better to make an issue once a specific alternative appears, so we can evaluate it and perform the switch, but having issue open for something that might or might not happen, or might not even be an issue in the future will just add clutter for now.

The performance issues with it are mainly pathological behavior with newer versions, the older one runs fine. All the analysis is queued up asynchronously on background threads, currently run locally. I do consider making it networked over voice to save some local compute, it needs the analysis to be synced with the audio stream though.

Keep in mind the Process Explorer stack traces are very rough and it might not be indicative of how much time it's actually consuming, because the thread you're checking happens to fall asleep at the particular trace and might not be even doing anything when you check it. I've added some profiling info to the build, once I'm doing some more profiling the VisemeAnalysis should show up.
