### ISSUE TITLE
Assimp64.dll crashes on import

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#711]
Reported by Rukio, upon importing a particular file, Assimp will cause Neos to crash during the import process.

Attached is a zip containing the model, and some crash logs pertaining to it.

[AssimpCrashes.zip](https://github.com/Frooxius/NeosPublic/files/4811340/AssimpCrashes.zip)

**Comment by Frooxius** [comment]
This is a bug in Assimp, not in Neos, so I'll have to forward this. However we're currently behind on the main commits, due to other bugs in latest versions Assimp, so I don't know when we'll be able to try the latest commit. 

For now I recommend converting this model to a different format and importing that.

**Comment by Frooxius** [comment]
Updated to latest Assimp in 2021.1.26.1308, this has fixed the crash!
