### ISSUE TITLE
Interface Request: Have SYNCHING bar on Session Tab too when saving session

### ISSUE THREAD

**Issue by GearBell** [Frooxius/NeosPublic#739]
When we save a world we have to jump over to the home tab to see if its synching, can we have a synching indicator under the Save options in the sessions tab so we can see it synch on the same tab we press save? there seems to be lots of room for it.

**Comment by TehTurk** [comment]
I reported this during the testing phase and was skipped why idk but, the Sync should be on the top as a default, even with inventory saving/syncing.

**Comment by GearBell** [comment]
Agreed! Synch bar on top makes sense!

**Comment by shiftyscales** [comment]
Sirkitree has already added this feedback/request on #727.

**Comment by TehTurk** [comment]
Ah but he didn't mention it for the top bar in #727 l, should we close this and add that there then?

**Comment by shiftyscales** [comment]
Not necessarily- it's still easier to have separate threads than mega-issues for tracking (unless it's added as a check box like the other notes on that issue.)

**Comment by Frooxius** [comment]
Once the editing is possible, you'll be able to do this yourself, but I feel like the whole approach here is wrong. If you're checking the syncing to check if it saved, I feel like that's the actual problem and something that should be addressed, namely by adding some sort of confirmation message when you save.

That solution is a lot more general, as it doesn't rely on it being saved to the cloud too.

**Comment by TehTurk** [comment]
True, but I do feel like for the default behavior a new user should know they saved/synched something, maybe have a color/text indicator overlaying till synched like a loading bar in some form. But Im sure this needs to be thought on.

**Comment by sirkitree** [comment]
Possible duplicate: https://github.com/Frooxius/NeosPublic/issues/760

The conversations seems to be either having this on the top bar or on the session screen where you can save. Either I think addresses the underlying issue in that we look at the sync state when saving. Though as @Frooxius stated, a confirmation dialog could be added. 

Though with that, I'm not sure. You see, I wait until syncing is complete when I save so that if I immediately want to quit Neos after saving, I know it's safe to do so without losing any work, because the syncing is complete. I know that Neos will not quit until syncing is complete, but I've been burnt on that before sometimes with a system crash (rare). It may just be all in my head that I'd lose that work, but I feel like it's happened enough in the past that I'm simply safer waiting until it's synced to leave.

**Comment by TehTurk** [comment]
I originally thought it was a dupe, but this is more confirmation behavior related vs new user behavior/issue why I decided to add another issue to split the conversation from it.

**Comment by TehTurk** [comment]
Should we close this or rename the issue?

**Comment by shiftyscales** [comment]
Closing this issue as the sync has been added to the top bar by default, thus making it visible while the session menu is open. Additionally, in subsequent updates once the session menu is converted to facets, it'll be possible to add it directly onto that menu too.
