### ISSUE TITLE
Request: Organize Block Components & Add More BlockComponents

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#740]
The Block components are really handy, it'd be nice if they had their own category under Interaction -> Block. 

Thusly I would like to request the addition of some more Block Components akin to GrabBlock, DupeBlock, SearchBlock. Some suggestions/ideas are

SaveBlock - Would prevent any type of Saving or Syncing, handy for locking down worlds, or items without having proper permissions. 
PackBlock - Would prevent the parenting behavior of logix packing and unpacking. This is handy in certain modular logix situations. 
ParentBlock - Would prevent any slots underneath from being added or removed, or itself from being parented after being spawned. But I can understand if this one isn't added or considered due to technical/design reasons. 

If any others have suggestions or ideas feel free.

**Comment by shiftyscales** [comment]
Making their own category is something that could be done- but perhaps it'd be better to move the other blocking components into the existing 'tagging' group?

SaveBlock- this can already be accomplished on a per-world basis with the "AllowSavingItem" and "AllowTransferingObjectsOut" permissions. Doing it per-item would be handled under the scope of the licensing system- to determine who has the rights to own/spawn out an object. It also poses some fundamental issues- e.g. if the saving of that object is blocked- how does one save it to their inventory in the first place if they wish to use it after it was created?

PackBlock- What "certain modular logix situations" are you talking about? It sounds like there is an underlying issue that could be resolved there, possibly by a different method. There's also not really a means by which you could exclude one speciifc piece of Logix from packing in a slot but not another.

ParentBlock - This is something that could be handled via the hard permissions system, e.g. locking certain parts of a hierarchy/data model from being modified, e.g. filtering out parenting events.

**Comment by TehTurk** [comment]
I don't think it would be a Tagging Catergory, the entire components list does really need a proper reorg. Because finding stuff is a little unruley sometimes .

I also realize in hindsight yes alot of this would be handled by permissions ^^; so was considering closing the thread, but I do think there should be more blocks in consider if a game design scenario. 

PackBlock and ParentBlock are similar, but it's more so referring to the discord when @H3BO3 asked for an explanation. Repeating it here, in context of DriveNodes I need them to be duplicatable for UI situations Because when you duplicate other driving components it keeps the same reference instead of the new one. Because I need a drive node duplicating vs the ui panel itself.

**Comment by ProbablePrime** [comment]
Here's my Hat in the ring.

Transform-> Tagging is the right place for all the block components.

They are small components who's presence tags a slot with new behavior.

**Comment by Frooxius** [comment]
I've moved the components under Transform/Tagging for the next build.

However those proposed components aren't feasible to add. These components only serve as hints to particular subsystems, but the ones you're asking for require more complex/general functionality that's handled by different systems.

SaveBlock wouldn't be secure at all, all need to do is simply remove it. It could serve as a hint to not save particular objects, but I'm afraid people would misuse it for security, which it could not provide. That's going to be responsibility of the Object ID system: https://github.com/Frooxius/NeosPublic/issues/21

PackBlock doesn't really mesh with how LogiX packing works. If you need to split systems into modular ones, that needs to be done at LogiX level, rather than at the level of individual slots. It's not clear how it would behave in various ambiguous situations. 

The ParentBlock would be job for the permission system as well, otherwise there's no way to actually enforce this. Objects can get parented by variety of different ways and variety of different systems. E.g. consider the GrabbableReparentBlock, which specifically interacts with the grabbing system.

**Comment by Frooxius** [comment]
I've reorganized the components in 2020.7.5.788! Let me know if I missed any. 

Since the proposed components can't really be implemented, I'm going to close the issue for now. It might be better to make more general topics for different functionality itself (or based on the issue you're dealing with), rather than specific implementation form.
