### ISSUE TITLE
Unable to spawan facets from public folders

### ISSUE THREAD

**Issue by Coffee-Maker** [Frooxius/NeosPublic#756]
Facets that are in public folders are unable to be spawned into userspace as the button to do so does not exist. Saving the facet to a non-public folder then shows the button to spawn into userspace

**Comment by shiftyscales** [comment]
As noted in the patch notes:
> - Added ability to bring custom Facets into userspace through the inventory
-- First, save a Facet into your inventory and then click on it once and use the new magenta colored button to spawn it out in the userspace
-- IMPORTANT!!! Only spawn out Facets you trust, they have access to your private UI and data. The mechanism will be more robust in the future, this is meant for early experimentation.

I think this could potentially be an important security consideration/intentional design that the facets currently must be saved to a personal inventory.

I don't think the public folder/sharing mentality should be encouraged this explicitly with facets yet. It's important that anyone that wishes to use facets trust the source/understand what they're installing.

**Comment by Frooxius** [comment]
This is intentional, it's a security restriction as noted in the update notes.
