### ISSUE TITLE
Dash disables when it's closed, causing facets to stop functioning

### ISSUE THREAD

**Issue by Coffee-Maker** [Frooxius/NeosPublic#757]
Some facets rely on being active (I made a facet that has an audio playback), the dash disables the facets causing the audio to stop playing.

**Comment by Frooxius** [comment]
This is intentional, it's necessary to have it disabled when it's not in use for performance. I can add a mechanism for setting up part of Facet hierarchy to be parented under object that stays permanently active even when closed.

**Comment by shiftyscales** [comment]
I would like to see that in general as a mechanism for facets. The capacity to 'pin' them to stay always-active regardless of the container's state. E.g. in the top bar of the dash one could pin the time, FPS, and voice mode switcher (as some potential examples).

Having an 'isPinned' property for individual facets would be a useful way to keep certain facets always-active without the user needing to create an entirely separate container for them. It would benefit not just the dash, but containers/workspaces/facets in general.

As noted before too- since containers can be a facet, it would also allow user-made containers to stay open even when the rest of their UI is closed.

**Comment by Frooxius** [comment]
@shiftyscales That's not possible. If the container is closed and hidden, so has the facet. The only option is to have the container be visible and active.

That's planned as you'll be able to have permanently-on containers in your playspace and on your avatar, but separate from this issue.

**Comment by Frooxius** [comment]
2020.7.27.3 now has AlwaysOnFacetModule, which lets you separate part of the Facet when it's placed on the dash into a hierarchy that always stays active. It also has ProjectedRectSlotDriver which lets you project arbitrary 3D objects on top of the dash.
