### ISSUE TITLE
Bug/Glitch: Grabbing nodes positions them at hands for people observing

### ISSUE THREAD

**Issue by DeliriousJax** [Frooxius/NeosPublic#764]
An odd glitch causing nodes grabbed snap to the grabbing person's hand. To them it looks normal; to others, it snaps to their palm/wrist. It seems to be different per user, as seen here when two users wearing the same avatar are grabbing the same node with differing results.

Example video:
https://www.youtube.com/watch?v=T9k2GDS4waI&feature=youtu.be

**Comment by shiftyscales** [comment]
This issue actually isn't exclusive to just nodes. It's also been occurring on pictures too. I've not yet quite isolated the cause.

Visually it's quite similar to #637, but it doesn't seem to be exclusive to just headless sessions, and it also doesn't seem to happen entirely consistently.

**Comment by inzanesonikku** [comment]
i have seen it on anything thats grabbable

**Comment by inzanesonikku** [comment]
restarting does not fix it

**Comment by mralext20** [comment]
i can confirm, i have seen this a lot on gearbell and vigil, its especially noticable when either of them grab inspectors. 

i wonder if its based on tracking method / runtime? that would not make very much sence however.

**Comment by Frooxius** [comment]
Hmm this is odd. It looks like some of the data used for grab positioning is not handled correctly. 

- Does this happen for everyone in the session of specific user?
- Does it go away if the user that holds the items respawns?
- Is there anything that seems to trigger this behavior?
- When this happens again, could you check the CommonTool component and what is the value of _currentGrabType field on it?

**Comment by GearBell** [comment]
it seems to stick with specific users. respawning or restarting world does not fix it. It consistantly follows users in any world. it only happens specifically when grabbing things with the laser. Releasing the item sets the item down in whatever new spot you've chosen as if nothing wierd happened. (ex: pick an item up, others see it dissapear to the hand, you move the item to the other side of the room and release it, it drops wherever you meant to put it). Ill check the grabtype field next.

**Comment by Frooxius** [comment]
The item dropping wherever it was meant to be dropped is expected behavior, as the new position gets written out directly.

It's likely something with the laser positioning not working correctly, but it's quite bizarre that respawning or even restarting world doesn't clear it up, as everything relating to positioning should be completely gone.

- Definitely check the _currentGrabType field on any of the affected users, that could help indicate or eliminate one major potential cause.
- Does it persist if the user restarts Neos and rejoins the same world?
- Does the user hosting a world make any difference? 
- Can you get me logs from any user who was affected by this (ideally logs from other people in the session too)?

**Comment by H3BO3** [comment]
I was trying to check this last night, but I cannot find the _currentGrabType field. Could you point me to where it is?

Also, it seems to consistently happen to @GearBell , often she's hosting a world but I'll try and keep an eye out for it in other sessions too and make those connections. Perhaps she can provide a log from a session of hers.

**Comment by shiftyscales** [comment]
This issue reportedly hasn't come up in a long time, and is believed to be resolved. If it isn't, this issue can be re-opened, and/or a new issue made.
