### ISSUE TITLE
User lasers visually distracting

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#767]
Requested by GearBell, lasers could be visible only while actively grabbing an object (not passively hovering over it) similarly, for buttons, etc. she also wishes those would not appear publicly from other users.

One of the primary reasons for the lasers change was to provide visual feedback to other users, in particular, when something is actively being grabbed.

She believes that it is visually distracting to see the lasers of every user in the session frequently- especially for situations in which the lasers aren't actively providing visual feedback (e.g. passively hovering over interactible objects, or grabbable objects.)

**Comment by Frooxius** [comment]
I can tweak that for the grabbing, but not sure about the interactions. Usually there's much fewer of them and generally you want to see those before you even click it, since the clicks are brief. Would that work well?

**Comment by shiftyscales** [comment]
I think it makes sense that passive hovers for grabbing definitely be changed.

Would there be any way to briefly make the laser visible for a moment after an interaction instead maybe? That way they still don't appear publicly while passively hovering.

Then you would get the feedback of seeing who clicked on something public without keeping the lasers visible unnecessarily, @Frooxius.

**Comment by GearBell** [comment]
i vote on hiding them unless picking up things or clicking on interactive thing. its awful with lots of people in a room and lots of lasers everywhere.

**Comment by Ruikio** [comment]
Seeing lasers, especially from desktop ends up becoming disorienting. Especially coming from other platforms where things normally accompany it (Like a malicious user). I also have friends who are in the service and get PTSD from things like this. Having them not just floating around unless something is being interacted with would help minimize that. Also yeah.. visually disturbing. I vote to fixing it.

**Comment by NateTheHunter** [comment]
Coming from a person who began Neos as desktop, its very distracting seeing laser fly past your screen and such.

**Comment by Frooxius** [comment]
I can change it for the grabbing, but like I said the interactions are trickier, especially since they're meant to be visible so you can better show what you're interacting with and teach other users as well. 

Why exactly are they becoming so distracting though? The new laser system only makes them appear when the user wants to actively interact with something and they should be hidden otherwise. Are many people activating the lasers at once?

We can't just blindly change things without bringing the old problems back and understanding the situation better will help.

**Comment by GearBell** [comment]
when you are in a room with lots of interactive things or grabbable items peoples lasers are popping up all the time even though they dont intend to use them. if we want to point to soemthing we do have laser pointers we can easily pull out, but them automatically being visable is super distracting. to clarify - we dont want to see other peoples lasers, if they we kept locally itd be a lot less visual cluster

**Comment by Ruikio** [comment]
Unless users are interaction with something. I see no reason why lasers should be on constantly. If I want that I'll equip tooltip that maybe specifically functions like that, or a laser pointer. Seeing desktop lasers around the map is a little odd. Given me a few scares.

**Comment by Frooxius** [comment]
This is really odd, because that's not the way the system is designed. The lasers should be off, unless they are activated by the user. They will also auto-fade afterwards. Unless the laser is pointing at an interactable item, it should also be invisible to others.

The system already is designed so the lasers aren't on constantly, but only when interacting with things. I can fine tune this, but I'm a bit confused by your description of the problem, because it sounds more like something that's already there is broken, or there's some odd use (e.g. do people have Edit mode on?)

**Comment by TehTurk** [comment]
Desktop mode is a debug mode and I don't think the behaviors will change for that. As for having peoples lasers not show up, I don't know if you could reliably tweak this behavior. If you want I can sit down with you guys and see whatsup, maybe your upset by like lasers being infinite distance so they will randomly appear.

**Comment by mralext20** [comment]
an example of lazers ruining a photo: 
![2020-07-13 15 03 33](https://user-images.githubusercontent.com/4016295/87362133-4115f100-c51a-11ea-8194-9d76f647d003.jpg)

**Comment by NateTheHunter** [comment]
https://clips.twitch.tv/EsteemedInspiringMageOpieOP

**Comment by GearBell** [comment]
in that photo the laser showed up when i hovered over something

**Comment by TehTurk** [comment]
Pretty sure there's a hide lasers in the camera options

**Comment by Ruikio** [comment]
No. I just don't like laser's being placed straight across my screen.  It's not a matter of being upset. It's not just visually appealing. A simple QoL. Make main lasers off by default. Have an option to have it on by default. 
![image](https://user-images.githubusercontent.com/42963569/87362182-f1482180-c53b-11ea-8ea5-4c67538d7eaa.png)

**Comment by mralext20** [comment]
if there is a hide lazers option its not enabled in the finger photo menu

**Comment by H3BO3** [comment]
there could be a toggle to make other people's lasers completely invisible I imagine, but it wouldn't be default

**Comment by TehTurk** [comment]
So couple different things. 
1. The across the room lasers could be solved by distance cutoff, but the main issue is your world a build world or a.social world? The lasers are there so others are aware of what your doing.
2. Ok then that seems like a bug as Finger and Camera settings should be shared.

**Comment by Ruikio** [comment]
Why wouldn't it be default? Why not default off?

**Comment by H3BO3** [comment]
because it's good to know when people are grabbing or clicking things? You're basically the only problem who seems to have a problem with this, so if it was a neos setting, you could just turn it off.

**Comment by Ruikio** [comment]
You're right! Thats why the purpose of this was to have it where laser would be invisible to say me, unless someone is grabbing something.

**Comment by GearBell** [comment]
if the laser is going to be visible on click or grabbable anyways it seems redundant to have them visible anyother time. the old way of what they were made more sense: lasers are visible only when grabbing

**Comment by H3BO3** [comment]
Wait what? The way you were saying it sounded like you wanted other's lasers to be invisible all the time

**Comment by H3BO3** [comment]
I agree with gearbell, I have been for a while now

**Comment by TehTurk** [comment]
If this is going to be very conversational I recommend going to the #bugsandfeedback to hash it out. Too many people are trying to comment on an issue on a git when it's not something that's constantly messaged on.

**Comment by Frooxius** [comment]
I see. For them being specifically with photos that could be fixed, I think I forgot to add the new ones into an exclusion list.

Distance cutoff sounds like a potentially good idea to explore, to make it more clever and cull them when they shouldn't be seen, but show them in scenarios where they could.

Having them default off isn't really good solution, because it just moves problem rather than solving it and brings back the old problems again. E.g. people turn them on and forget (or don't care) and we'll be back to where we started. It's better to balance the system so it behaves in desired way without the need for user intervention.

I understand that they can be distracting at times, but we can't fix that long term by making a knee-jerk change.

**Comment by Ruikio** [comment]
Nope! Just invisible unless the user  is interacting. I've been having many people spawning in and having a laser cutting across my screen for a bit too long. It makes me panic, especially when I try to limit people from having access to the inspectors and dev tools.

**Comment by Frooxius** [comment]
The system is already designed so they're invisible unless the user is interacting. Except when they're in edit mode or using a development tool.

**Comment by GearBell** [comment]
no not just for photos! anywhere! live! we dont want to see people lasers at all if we can help it

**Comment by Frooxius** [comment]
Please read my whole post. It's just one of the things I mention.

**Comment by GearBell** [comment]
we are not in edit mode, we can see them

**Comment by H3BO3** [comment]
they're not invisible everywhere, they show up when someone is hovering over a grabbable object or click button

**Comment by GearBell** [comment]
can we not have globally visable lasers when hovering?

**Comment by shiftyscales** [comment]
Filtering out passive lasers in general would be beneficial. E.g. 'on hover'.

As a practical example- while watching a movie last night with Coffee, etc. he needed to set desktop users to spectator otherwise their lasers would be constantly on.

They can/should be visible during active interactions, e.g. moving sliders, grabbing objects, and perhaps for a very brief period after clicking buttons, etc.

The main issue users are having is with relation to lasers being active and visible to other users while they are just passively hovering over objects, @Frooxius.

It's not that the lasers are active for themselves- but rather that they are seeing other user's lasers while they are passively hovering over grabbables/interactibles. That's what I'm gathering from the above responses.

**Comment by Frooxius** [comment]
I've already confirmed that I can tweak a few times above. But I asked a bunch of additional questions to better understand the problem and fine tune the solution so it both does what you want, but also doesn't break other things and introduce old problems, but I can't do that if you're just repeatedly restating the same problem, rather than participating in the discussion.

**Comment by Ruikio** [comment]
Shifty formatted the question perfectly.  Check out his response.

**Comment by GearBell** [comment]
we dont want to see other peoples lasers when they hover over stuff, its okay to see our own though.

**Comment by TehTurk** [comment]
Please understand the Git isn't a chatroom, the responses will not always update immediately.

**Comment by Ruikio** [comment]
We understand. Thank you.

**Comment by Frooxius** [comment]
@shiftyscales Yeah I understand the underlying issue, but we need to find the optimal solution for this, so I need some more details for this.

For the grabbing, that seems like a good change without any side effects. Only visible when the item is held, so it doesn't quite show up.

What is a bit strange though is the situation with Coffee. Why are people's lasers coming on in that case? The way the system is designed is that they shouldn't be visible, unless people are turning them on, so that shouldn't even be happening with the current system at all. Can you provide more details about this please?

Similarly what @Ruikio is mentioning with them being constantly on is odd, because that shouldn't be happening either, so it sounds more like a bug or some misunderstanding.

Like I mentioned in my initial post, the click interactions a bit trickier, because clicks are brief and you can't see what the person tries to interact with otherwise, which can be a problem for UI's, inspectors and so on and you might need to see the laser before. This is the main thing that I'm trying to get some ideas/feedback on.

An interesting solution can be made there as well though, like the filtering from angles and/or distance that @TehTurk mentioned. This could allow them to be seen in some cases, but also filtered out from randomly flickering in others. Potentially also having a "grace period" for them coming on for others could eliminate more of the artifacts.

For the case of PTSD that @Ruikio has mentioned I think that's a more special case that should warrant its own solution. E.g. having a toggle to disable seeing everyone's lasers completely. That could be a good option in general for users who just don't want to see them at all and are willing to have some of the negative side effects on interaction side.

**Comment by shiftyscales** [comment]
Users interact with the video player, e.g. to change their volume level, their lasers don't deactivate while inactive because they continue to hover over the video player, thus 'interacting' with it. I believe that is what the issue was with Coffee's video player.

Similarly for Rukio, I believe 'constantly on' is because the delay for them to turn off automatically is reset every time a user in their session hovers over a new interactible/grabbable regardless of whether they intended to interact or not.

I think that is something that could eventually be resolved when laser settings could be adjusted in more depth post-UI overhaul for the settings menu. E.g. the laser timeout period.

I think seeing 'on hover' passive events for interactbles will likely be okay- especially if paired with the aforementioned distance filtering- or if there is a mechanism through which laser visibility can be turned off as a toggle (that isn't enabled by default) (this would also fit in with the desire of other users to have an 'immerion mode').

**Comment by Frooxius** [comment]
I've made changes in 2020.7.24.446 to reduce this problem. Lasers won't show for grabbables unless you're holding them. For other interactables there's a short grace period before they show for other users, which should fix them randomly flickering.

I could not replicate the problem with the photo, they seem to be culled correctly in those. Can you provide more replication steps?

@shiftyscales Hmm, that's a bit strange, do they just keep their own lasers on for themselves? I feel like that's more of a social issue when the users don't deactivate their lasers. That's a bit more tricky, as it's hard to distinguish when the user is interacting intentionally and when not.

**Comment by shiftyscales** [comment]
I think the issue in the photo was actually a user-made tool. @Frooxius It has an always-on red laser, I've since seen other users using it. I think things are in a pretty good place right now/this issue could potentially be closed. I've asked @GearBell and @Ruikio for their thoughts too.

**Comment by shiftyscales** [comment]
Ah- I got further clarification on this. Apparently lasers are not turned off for finger-photos, @Frooxius.

**Comment by TehTurk** [comment]
This is typically okay, there is a hide lasers option in the camera,. typically it would relate to that I would think.

**Comment by Frooxius** [comment]
@shiftyscales Ah that makes sense, I haven't checked the Finger Camera before. I've added a code that will exclude the lasers in the next build for photos taken with it.

**Comment by Frooxius** [comment]
2020.7.29.725 now has fix for the finger camera.

**Comment by shiftyscales** [comment]
I'm considering this issue as resolved, and the original parties including Rukio and GearBell have agreed as well. Thanks for all of your additions, and tweaks, @Frooxius. <3
