### ISSUE TITLE
Request: Please Let Facets be Spawnable from the public folder. Also Reduce Shrinking

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#780]
I don't know if the mechanism will get reworked, but right now having to save facets then set them is a bit annoying and stressful on users Cloud Storage because typically it'll count for that. Be able to spawn Facets from publics is alot more realistic. While I understand for security, a confirmation dialog could be added for warning users to be careful when using public facets.  

Alternatively, can they also not Shrink when I grab them? Or at least not have the default be like .5 local scale.

**Comment by shiftyscales** [comment]
If a facet is on someone's dash it'd still count towards a user's storage anyway as data is data, and it still needs to be synced to their cloud in order to save the arrangement.

There will be different mechanisms in place in the future for dealing with facets (e.g. once the market is out), but as noted, disallowing them from public folders is a security issue. Even with a warning, a user should verify the code first. It'd still require the user spawn it out in the world to inspect it prior to using it- and even then- it's doubtful a user is actually going to take the time to check that if they're looking to install it quickly- and hence want it to be spawnable from public folders in the first place.

All that adding a confirmation dialog would do is to serve as yet another button to click past prior to spawning out their facet. Since the facet that's displayed on their dash is also going to be synced to their cloud anyway, it makes sense they have a personal copy in their inventory, both to spawn it out, and keep it backed up.

Can you clarify on your use-case/desire for 'reduce shrinking'? What's the underlying issue you are wanting to solve by doing so?

**Comment by Frooxius** [comment]
Sorry, but I'm going to deny this request.

As mentioned in the release notes, this is intentional. There's not a proper security system for spawning out facets, so you can potentially spawn out really dangerous ones that steal some of your private information. As such, you should only ever spawn facets you really trust and saving the facet into your inventory is ensuring that you consciously know what you're doing and to prevent users that are unaware from just spawning something out easily.

It's not perfect, but until the security system and proper way to introduce the facets, it will be this way to reduce security risk. This is not debatable, sorry.

**Comment by TehTurk** [comment]
This is fine, I just wanted to know if an opt in for the security would be possible, besides right now customizing your dash isn't as fluid in terms of introducing new pieces/parts.

**Comment by shiftyscales** [comment]
Security isn't something that would ever be compromised like that- as Frooxius had noted, it's not negotiable.

And yes, it's not where it could be- but the functionality is also not finished. As noted even at the time of its release- the current system is a temporary one aiming to allow users to start playing around with customization/custom facets now in advance of the proper systems being developed.

**Comment by TehTurk** [comment]
No I'm aware and understand that, but if I don't have the capability to asses someone who makes logix and what they might do, then yeah, that'd be on me but I understand if that's not for the general user. I'm not upset, I'm just like "hmm let me see if possible, if not I can wait."

**Comment by Earthmark** [comment]
I was having a conversation with Alex, my guess is once authenticated assets becomes a thing this may be revisited? I could see from an API updating perspective it may be good to be able to spawn facets from authenticated folders once the folders and things inside can be authenticated, validated, and approved.

**Comment by mralext20** [comment]
i have noticed; you can currently load a keyboard from someone's public folder. not sure if that mechanisum will also be reworked aswell, or not

**Comment by Frooxius** [comment]
It's not about authentication, but rather validation. We need a system to scan what kinds of things the facet wants to access and have mechanisms for isolation, so if it doesn't have right permissions, it cannot access any other hierarchy than its own or use any components it doesn't have the permissions to.

It's not about being possible either. It's easily possible to enable this, but my main concern is what kind of pattern this enables. I don't want people to start sharing Facets too freely. Let's say you're a new user and you spawn out Facet from someone's public inventory without thinking, which has some malicious code.

Or you get Facet that looks good from someone's public inventory (let's say you verify its logix). Later on you want to spawn another copy, but the person has silently replaced it with a malicious variant and you haven't noticed. 

The current system is far from perfect and fully safe, but it should mitigate the issues from spreading too much.

It's also good point on the keyboard, I'll make sure that one can only be spawned from your inventory right now. Later on it would use the same system for validation.

**Comment by TehTurk** [comment]
The issue is this kinda persists with being able to favorite anything of that nature outside of the public folder space. In terms of sensitive info, identifying it what would be protected first would be the first step imho. Like NCR amounts, maybe Machine ID? Or even disabling get/post but that would also prevent some facets from working. If we are protecting from Malicious intent, understanding targets would help.

**Comment by Frooxius** [comment]
Machine ID is a public information, it's safe to share and available to the world. NCR isn't and it's only available to private facets.

What do you mean by the issue persisting by favoriting anything of that nature?

**Comment by TehTurk** [comment]
Ah, keyboards, cameras, avatars, tbf if anything is in the local space and can be Favorited yeah it's going to be subjected to the same issues/rules, even avatars but then that can break the benefits of the public folders. I think having at least things we need to know of sensitive nature to avoid, by identifying that and then you can have the validation in some form.

**Comment by Frooxius** [comment]
Cameras and avatars are fine, because these are never spawned in your Userspace, they're always part of the world, which doesn't have access to the private information (e.g. the components to access NCR counts don't work there).

Keyboards I'll fix though.
