### ISSUE TITLE
Tip reference set to X rotation -90 causes grabbables to rapidly flip around

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#800]
Reported initially by Alex from Alaska.

I discovered on investigating that this issue is specific to using a tip reference with rotation of -90 on the X-axis (-90,180,180 in the inspector).

@Frooxius believes it's likely that specific rotation causing a singularity/should be an easy fix.

**Comment by TehTurk** [comment]
Would @Frooxius Be able to expand on what a Singularity is? We did try different tip Rotations and it didn't seem to affect anything.

**Comment by Frooxius** [comment]
In mathematics it's a point where something is undefined: https://en.wikipedia.org/wiki/Singularity_(mathematics)

In this case it's trying to determine forward direction on a plane, but the vector is pointing completely up (perpendicular with the plane), so there's no valid solution, as any vector on the plane is a valid solution (in other words, the solutions are infinite).

**Comment by Frooxius** [comment]
Also can you send me the problematic tooltip in-game for testing?

**Comment by mralext20** [comment]
ill send it to you, one moment.

**Comment by mralext20** [comment]
sent!

**Comment by Frooxius** [comment]
Thanks! I've looked into this, but turns out it's not a bug, the tooltip is just setup incorrectly. It uses the upwards (Y - green) axis as its forward, with the actual forward direction being to the side and the tip direction being perpendicular to that.

For tooltips to work correctly the axis coordinates are important. You need to use the forward axis (Z - blue) as the actual forward and upwards as the actual upwards axis.

![2020-07-27 01 21 13](https://user-images.githubusercontent.com/8838625/88491995-9f75b180-cfa7-11ea-846a-01685b5b8377.jpg)

**Comment by mralext20** [comment]
good to know, thanks!
