### ISSUE TITLE
Controller node floats show 2.795787E-09 instead of 0 for other players

### ISSUE THREAD

**Issue by InsaneGrox** [Frooxius/NeosPublic#809]
I discovered this because of something on my avatar behaving incorrectly for other players, as it turns out, for the user plugged into the controller node, a value of 0 is a value of 0, for all other players however, the value reads 2.795787E-09, this may be problematic for some logix systems involving controller nodes to people unaware of this issue, and infact it caused some issues with me just now, with anything my avatar grabs showing up on my feet instead of on my hands due to a system I use for foot grabbing using a == node for checking the pressure of the trigger and a ?: node for changing the position of my grab sphere between my hand and foot.

I debugged this a bit further with alex_from_alaska and found it affects every float output from a controller node.

**Comment by mralext20** [comment]
![2020-07-25 00 45 24](https://user-images.githubusercontent.com/4016295/88453173-2b090a00-ce11-11ea-9e93-feb5b12df513.jpg)
![2020-07-25 00 44 59](https://user-images.githubusercontent.com/4016295/88453174-2c3a3700-ce11-11ea-8940-2f9ca35a8999.jpg)

**Comment by Frooxius** [comment]
This is technically not a bug, but a consequence of floating point numbers and their imprecision. I can look into making sure that the 0 and 1 values will encode exactly as 0 and 1, but in general you shouldn't be using sharp comparisons for floats, as this is a general problem you'll run into with lots of other things (it's not specific to Neos either, but pretty all common programming languages).

Usually it's good to have some small tolerance value for comparisons. For controllers you might also not get exactly 0 in general, as some end up sending some nonzero value due to drift or other small errors.

**Comment by Frooxius** [comment]
I've changed the quantization defaults, so 1D inputs on controllers should be quantized in the 0...1 range, rather than -1...1. This will make them decode as 0 exactly in 2020.7.29.725. 

Still I do recommend to be wary of using exact comparisons as floats, as there will be other cases where this will cause problems.
