### ISSUE TITLE
Dynamically Loaded URLs Only Play On the Second Attempt When Using One-Shot Audio

### ISSUE THREAD

**Issue by Enverex** [Frooxius/NeosPublic#811]
I've sent Froox an example case of this, he just needs to spawn it out and unpack it. You can then change the variable to test it each time.

The issue is that when setting the URL for a Static Audio Clip Provider, it doesn't seem to work the first time if it's an external audio file. Trying to then play the same clip again (via One Shot logix) will work as expected. Changing the URL will cause the next attempt to fail, trying it again will work as expected.

My initial concern was that maybe it needs a few seconds after being switched to download/buffer it, but even adding a 5 second delay between the URL switch and playback doesn't resolve the problem. The audio still only works on the second and further attempts.

**Comment by H3BO3** [comment]
I will try and do some testing on this today, including seeing if it works with the standard Play node as well.

**Comment by Frooxius** [comment]
This is expected behavior, the audio doesn't get downloaded and loaded until you have an instance of it. The first play one shot is actually the first time it's spawned into the world, so it has to download and load that clip. Just having the URL somewhere isn't enough, because it doesn't know what kind of URL it is or that you even want to be loaded.

I can add things to help preload assets in such cases. A kinda hacky workaround would be to do Play One Shot with volume set to 0 first to force it to preload without playing audibly and then after a short time playing it for real.

**Comment by Enverex** [comment]
Is there any sort of asset loader component that it can be put into that would force a load, without having to actually play it through another audio element?

**Comment by H3BO3** [comment]
@Enverex There is, it's called the AssetLoader, coincidentally enough. Could try using it for this

**Comment by Enverex** [comment]
Using an AssetLoader component with a FrooxEngine.AudioClip datatype seems to work (subject to the existing Neos audio bug of cutting off the start of the audio) so I'll class this as "working as expected" then really.
