### ISSUE TITLE
Controller nodes on Local User don't seem to work

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#819]
Controller input logix nodes seem to bind to a random user instead of local user when hooked up to a local user node. This is a bit problematic when trying to make controller proxies for the tutorial world. Lucas came up with a workaround of user override reference drivers hooking into the data streams, but I figure this is probably a bug!

**Comment by H3BO3** [comment]
This has been addressed before in discord discussions. Froox plans to change the node behavior at some point so this setup works as expected. Leaving this open as a reminder.

**Comment by Frooxius** [comment]
Yes, this is expected behavior. The node is designed so it shares the same outputs for everyone, so the user needs to be consistent. Otherwise if you plug "LocalUser", everybody sees that they should be the ones controlling the node and you end up with a mess.

I'll see about redesigning those nodes though so this pattern can be used.

**Comment by Earthmark** [comment]
Are there many other nodes that have this "everyone gets the same output" behavior?

Considering local user is kinda 'the node' to use for client dependent behaviors I'm not sure what I'm supposed to expect in this case.
With a controller node under an avatar driven by an active user I can understand that being identical for all, but in this case it feels like the controller node does not have the behaviors the framework has taught me to rely on.

**Comment by Frooxius** [comment]
Yes, there's a bunch. FireOnTrue or FireOnChange also perform deduplication to make sure the right person detected the change. 

In general Neos' patterns are built around shared state and that's the philosophy of how most things are built. I always advise against doing otherwise and finding approach that follows this philosophy, otherwise you will clash with how the system is largely designed. It sometimes requires to approach problems differently, but it's worth it.

You can think of the "Local User" node as saying "Me". When you plug it into a node who uses it to determine who should be simulating or controlling or firing impulses, everybody's client will see "Me" and they'll think they're the ones supposed to handle stuff.

It goes to everything, even stuff like Update node. If you plug "Local User" there, everyone will fire the impulse on their end, because when the node checks the input for "Which user should be firing impulse?" they'll see "Me".

**Comment by Frooxius** [comment]
Hmm. Also looking more into this, I'm not sure if this will even be feasible to do. Problem is, the user who is supposed to be controlling the node does all the setup. Finds the appropriate instance of the controller on their end, checks if it's right type, fetches and optionally setups streams for transmitting the information and sets them up for everyone so they can read the info.

This work is not possible to do on other people's ends, because they don't have the information necessary to set it up. It can potentially be setup by assuming the streams were already setup, but it's very tricky.

I'll have to shelf this for later, sorry. I'd recommend using the right pattern and having a controller readout for particular user. Assign a user to the instance on setup and handle that. If you build things around that principle you're going to have easier time in general.

**Comment by Earthmark** [comment]
The current hack is a user reference override for the value streams with auto add for new users enabled. Every users client seems to attempt to bind the controller, which adds entries to the override making all the outputs client only (at least I believe that's the theory, it seems to at least work that way). I'll think about how to rebuild that for the tutorial world controller models, but for now it seems stable enough.

In terms of the context of shared state, while I agree I think the systems (specifically around local user) are used very consistently to do private ui, objects that follow every user around, or other systems like that where each client is intentionally seeing something different by using drives where the backing logic involves local user. If that goes against the core neos model I think there is a mismatch with the community then. Even the private ui done in the fps game mode uses systems that change object locations per user in the case of ui (at least for how I believe it works).

If those patterns are not supposed to be supported I'm very confused, because they seem to be quite common in the community. Perhaps more community discussion is needed around this or things may evolve in a way that causes ruffled feathers

**Comment by Frooxius** [comment]
There definitely are mismatches, but that's unavoidable. I generally keep advising against using these approaches, because at some point it will more likely clash with how things are designed, compared to alternate approach.

However Neos is very general, so it's possible to find lots of different ways and approaches to do things (kinda like a multi-paradigm programming language, where you can mix both imperative and functional styles for example) and people will.

It's not about not fully supporting patterns, but it's about what will be easier and better long term as you keep expanding your project. You can still use this pattern, it's just that you have to be aware that eventually you'll run into a situation where it might be difficult to solve a problem with it - e.g. if in the language where functional style is first class, you might run into issues if you try to force everything to be imperative. 

If one thing was changed to accommodate different approach, it will now clash with other things that depend on it, if those are changed those will clash with others. For Neos itself the goal is to keep the major style. If people's approaches and/or hacks cause problems, that at least isolates the problems, rather than causing major architectural issues in Neos long term.

**Comment by Earthmark** [comment]
I still think this is a bug, but I don't think it'll get fixed for a while. For now I'll stick to user override hacks, that's the basis for a lot of the tutorial world panels. 
But, the issue ain't doing anything so whatevs!
