### ISSUE TITLE
Option to record a Voice Message

### ISSUE THREAD

**Issue by MR-Alex42** [Frooxius/NeosPublic#82]
Neos allows you to quickly write a message with the paint tool. How about having the option to record a voice message that could be placed next to an object and would play if the user hits a button or just by getting into the proximity of the object.

**Comment by Frooxius** [comment]
Heh, I was just talking about this with sirkitree! :D I have it half-way implemented already, should be coming soon.

**Comment by MR-Alex42** [comment]
@wel97459 I like your idea. A metaverse would need some message system with an inbox.

**Comment by sirkitree** [comment]
Is this still something that is halfway done @Frooxius ? Generally, any access to voice data and recording would go a long way with the new character animator for us to create animated, walking, talking, NPCs

**Comment by sirkitree** [comment]
pasted form ohzee in discord: 
https://discordapp.com/channels/402159838827905024/731903736028332083/765570273419853844
![image](https://user-images.githubusercontent.com/28543/95868739-6c79c900-0d1f-11eb-8d63-ecfcbc85beec.png)

**Comment by Frooxius** [comment]
We have everything necessary to implement this with the support for full encoding with the Ogg Vorbis library. I just need to design how will the recording itself work. I'm not fully sure though if I want to rework and generalize the audio clip asset system a bit, so it will nicely work with recording and manipulating audio data, rather than hardcoding the functionality directly.

**Comment by H3BO3** [comment]
All viable functionality seems to be in place, including the microphone tip and voice messages as of build 2020.10.27.1173
