### ISSUE TITLE
Viewpoint further back on Oculus Quest for PCVR

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#828]
When joining the tutorial world by Earthmark I was defaulted into the NeosBot avatar only to realize my entire view is taken up by the eye textures, I know this was a thing for a while but I didn't quite know that this would cause issues.
I found that the viewpoint of the Oculus Quest is further back than other VR headset, in my testing this is the case in all cases of a Quest on PCVR, whether it be using Link, Virtual Desktop or ALVR.

**Comment by shiftyscales** [comment]
This is a known issue as you mentioned, but unfortunately seems to be an issue either with SteamVR, or Unity. Neos doesn't do anything specific to handle the camera positioning, but rather it is passing on the data from Unity/SteamVR. Stranger still- it seems to actually be an offset rather than just being a different position, because nearclip values, etc. are treated exactly the same as far as what is culled.

E.g. I set the near-clip such that the very tip of my avatar's muzzle was visible, and switched between the runtimes- the same amount of the muzzle was visible in both cases.

**Comment by alexderpyfox** [comment]
Maybe GitHub issue 592 could be used to solve this problem

**Comment by Hayden-da-Serg** [comment]
I just tested on Quest Standalone, this doesn't appear to be an issue there, though it is also quite outdated (2020.6.8.483) so it's either how SteamVR or Unity on PC builds is handling it.

**Comment by Earthmark** [comment]
The thing I was most worried about with it was related to the bot honestly. Can the neos bot get a preconfigured near clip so new users on those platforms that use the MTC don't get locked into a white interior view of their own eyes?
I can would imagine the attrition rate of those platforms in neos would be quite high if they use the avatar creation center as a new user.

**Comment by shiftyscales** [comment]
This issue appears to have been fixed in [SteamVR Hotfix 1.15.16](https://store.steampowered.com/newshub/app/250820/view/2931245981685839445).
> Fixed issue with head position on Quest and Quest 2 that appeared in 1.15.15.

**Comment by Earthmark** [comment]
Possibly not? The original hotfix was from Dec 17th, this issue was made in July. Either way it was mitigated!
