### ISSUE TITLE
In many Neos UI elements Spaces are hard to recognise

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#829]
On the default keyboard when entering text I find it very difficult to recognise if I have included a space or not. This also comes in in inspector text fields such as the slot name etc.

More recently it seems this might have affected a users actual username: https://discordapp.com/channels/402159838827905024/402159839251398666/738866745267454052

From memory i've spoken to a few other users and they've agreed. So i wanted to log this.

**Comment by Frooxius** [comment]
Do you have any screenshots or references? I'm not quite sure how much can be done about this, because spaces are defined by the used Font and the metrics and shaping rules it provides.

We could potentially switch to alternate font or maybe use MonoSpace font in some places, but that's tricky too, because there aren't that many permissively licensed fonts with large language coverage that we could bundle with Neos.

**Comment by Enverex** [comment]
On standard input in Neos, the space seems *incredibly* small. I find myself having to delete a few times and retype things just to make sure. It's almost non-existent.

Without space:
![image](https://user-images.githubusercontent.com/958670/89102122-0b1faa80-d3fe-11ea-96a0-8b5159cba0f1.png)

With space:
![image](https://user-images.githubusercontent.com/958670/89102124-12df4f00-d3fe-11ea-8449-fff5181c69cf.png)

It may as well not exist, it looks almost like it's only a single pixel wide. The space only becomes apparent after you type something else after it:
![image](https://user-images.githubusercontent.com/958670/89102135-31454a80-d3fe-11ea-91d8-c28ac2ca0f26.png)

**Comment by shiftyscales** [comment]
The major issue is that spaces and tabs have nearly zero width until there is a non-space/tab character entered, @Frooxius. The easiest way to see this is to enter a character on the keyboard, then press space/tab a few times, then enter another character.

Once the other character is added, the spaces/tabs will extend to their full width. This is mostly relevant during text entry.

It has caused various issues with user registrations too. Users adding multiple spaces, or adding a tab to their username without realizing because they tried to switch the input field.

**Comment by Frooxius** [comment]
I see. That's more specific issue, I thought it was just spaces in general in the middle of a word from the initial description. If it's at the end of the words, then that can be fixed for the cursor.

**Comment by ProbablePrime** [comment]
Ahh thank you so much for the screenshots and further help Shifty and Enverex that makes sense!

**Comment by Frooxius** [comment]
I'm looking into this and I've discovered one of the major problems... I've never implemented support for the tab '\t' characters! They're just ignored!

I've implemented support for them, they're coming in the next build. I'm still looking into the spaces not being quite visible in some cases, not sure what's causing that yet.

![image](https://user-images.githubusercontent.com/8838625/89351435-4944f480-d6b2-11ea-8f72-a96f418289d4.png)

**Comment by Frooxius** [comment]
Ok fixed all cases of it in 2020.8.5.1178 hopefully! The system used the width of the glyph to position the cursor at the end of the text. Since spaces have no width, the last space would be invisible. I expanded the system so it now tracks the "pen" position for each glyph and uses that for the last symbol when positioning the caret and selection, it should behave a lot better now.

Tabs are now also fully implemented as well, so they should show up correctly and align the text to the width of 8 spaces (I'll probably make this configurable per text renderer later).

Thanks for the info!
