### ISSUE TITLE
Make Voice Volume automatically added when creating an avatar

### ISSUE THREAD

**Issue by GearBell** [Frooxius/NeosPublic#831]
there are more growing situations where vfx on our avatars are driven by voice volume meter component - however because we are not in the habit of remembering to hit that "yes" checkbox on adding that component when creating an avatar - ESPECISLLY if its a new user who didnt know theyll need it later. Its a pain to add it later as it requires tracking down the deeply buried tutorials of it. Can Voice Volume Meter just automatically be added from now on when creating an avatar so we dont regret forgetting down the line?

**Comment by TehTurk** [comment]
There is a checkbox for this atm, I figure avatar creator will also be touched or adjusted in part of "UI" update.

**Comment by GearBell** [comment]
the point is no one thinks to add it at the time. if its added automatically we wont have to regret having forgotted to add it later

**Comment by TehTurk** [comment]
I add it all the time, everyone's mileage varies. Adding it is like VolMeter + Ref Copy or VolMeter and AvaVoiSourceAssigner. I understand what your saying tho, thank you for noting this so Froox can refer to this later.

**Comment by GearBell** [comment]
YOU might add it all the time, but new users dont, and then they come to me asking me to help them with an effect that requires a voice volume meter, and they didnt add one. and finding the tutorial is a pain and anyone who knows how to add it manual says its a major pain in the butt and most times ghost out before they can help. Again - if the voice volume meter is added *automatically* when you make an avatar we would not have these issues and could just jump right in on things that use it.

**Comment by Frooxius** [comment]
This is a bit tricky. The reason it's not added by default is because it adds a bit of extra performance impact, so I'd rather not have it put on all avatars unless it's really needed. Typically this component would be used by creators for setting up special effects and the expectation for creators is that you know you need it so you add it in advance or you add it later, whereas new user just setting up their avatar doesn't need to worry about it.

I could perhaps add a quicker way of setting it up afterwards or setting it up additionally with redesigned Avatar Creator (I want the redesigned one to be able to re-run and adjust a lot of the setup on existing avatars), but I'm not really sure about having it on.

**Comment by GearBell** [comment]
i see your point. i am not against manually setting it up, but currently less than a handful of users know how cause all they keep saying is its long and painful to set it up. is there a more compact way? from what i heard it requires tracking down several scattered components. (not asking for how to do it, but asking if it could be made to be more compact and easier) Is it possible to apply it with logix? if so perhaps some of us can band together to make an applier tool for easy use?

**Comment by Hayden-da-Serg** [comment]
@GearBell, after a but of digging I found it is possible to make a tool, so I made one in my public folder under Hayden Public > Tools > Volume Meter Installer
If you don't have my public folder it can be found in The Directory or just ask me next time you see me in Neos

**Comment by GearBell** [comment]
alright, i suppose this thing can close now. itd be beneficial to have that tool added to the general community avatars tools in Essentials so everyone and newcomers have quick access to it.
