### ISSUE TITLE
Camera Control panel is overzealus with reguard to finding a twitch chat

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#839]
I have created a facet that implements twitch chat on the dash, as so: 
![image](https://user-images.githubusercontent.com/4016295/89178122-6acea080-d539-11ea-986a-3ca1da303dbb.png)

when opening the streamer Camera, the streamer camera searches local space for a twitch chat component, and uses it for the settings boxes on the right side of the camera display: 
![image](https://user-images.githubusercontent.com/4016295/89178175-86d24200-d539-11ea-8cc9-7af9d262e38e.png)

this has the unfortunate side effect of disabling the twitch chat on dash when changing to a different settings panel on the camera (like the OBS intigreation) 
![image](https://user-images.githubusercontent.com/4016295/89178222-a4071080-d539-11ea-95bc-43b7a7c7dbb3.png)

idea for a fix: search not as deep for a Twitch Chat Diolog, instead of searching the entire local (dash) space. 

this may also probably be fixed when the camera control gets reworked to a facet, so 🤷

**Comment by Frooxius** [comment]
Unfortunately this is currently by design. Making the Twitch Chat Dialog into a Facet isn't a supported feature/workflow, so you'll have to wait until the systems are reworked properly into Facets and more modular pieces. 

If you want to experiment with the old UI and adapting it yourself into Facets you can, but we won't offer any support for it.
