### ISSUE TITLE
Tooltip disable/enable system for productivity

### ISSUE THREAD

**Issue by wel97459** [Frooxius/NeosPublic#84]
I was think this could be as simple a double tap of the controller pinwheel menu button.

With also a item add to the pinwheel to do the same thing.

My reasoning for this is that I find myself taking tooltips off for safety, and then needing to use it again a few seconds later.

This would also allow you to use the controller to move around in the world with tools equipped while there disabled.

**Comment by Frooxius** [comment]
Hmm, I'm not too sure about this one. I think disabling them would be pretty confusing/weird to most people.

I have a different feature I want to add - quick tool swap/rest, by pointing at the item shelf on the controller and just pressing trigger. If you point at another tool, it'll swap the current one for it, if you point at empty space, it'll just place the current one on the shelf.

This should be much faster than equipping-dequpping. What do you think?

**Comment by sirkitree** [comment]
> I have a different feature I want to add - quick tool swap/rest, by pointing at the item shelf on the controller and just pressing trigger. If you point at another tool, it'll swap the current one for it, if you point at empty space, it'll just place the current one on the shelf.

I like this. Most other VR apps with various tools do something similar and it feels like a known design pattern. Not sure what the last part, with pointing at empty space. Might be better to just put it back on the shelf if you want nothing equipped, or have a context menu item for 'unequip' maybe?

**Comment by wel97459** [comment]
context menu item for unequip would be be nice. along with all of this:

> I have a different feature I want to add - quick tool swap/rest, by pointing at the item shelf on the controller and just pressing trigger. If you point at another tool, it'll swap the current one for it, if you point at empty space, it'll just place the current one on the shelf.

**Comment by Frooxius** [comment]
Yeah, it should make things simpler to just point at the tool and press to equip. But the swapping has to be tied to the item shelf, otherwise there's no way to distinguish between using the tool (for example applying material to the tooltip or using it with developer tooltip) and swapping it.

I have a few problems with the contextual menu too. It adds yet another, completely different way of getting rid of the tool, uses up precious space in the circular menu and is pretty slow, compared to just quickly pointing at item shelf and pressing trigger to place the tool there.

Right now the workflow to quickly get rid of a tooltip and stash it to item shelf is:
Double press grip -> Press and hold grip again to hold it -> Move above item shelf -> Release

This is quite slow and fiddly, especially if you want to do it often.

What I propose for doing the same is:
Point at empty space on the item shelf -> Press trigger.

Or if you want to tool-swap (the one you have gets placed on the shelf and the one you pointed at gets equipped):
Point at another tool on the item shelf -> Press trigger

It keeps swapping and unequipping & stashing pretty similar.

**Comment by shiftyscales** [comment]
Closing this issue as Frooxius has already implemented this proposed tool-swap mechanism. Tooltips can now be stored on the tool shelves by aiming at, and clicking on them, as well as swapping between them.

Additionally, physical mode exists to disable remote clicks on everything in the world except for the UI, and will hide the tool shelves/tools, as well as the tips themselves aside from when in use on the UI.
