### ISSUE TITLE
Request: Remove Basic Shadow Ramp having a default

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#840]
While this is a nice touch, I'm noticing with alot of avatars it's just easier to not have it as depending on color tones or the material type(metal/specular) or look of the object it tends not to mesh well unless manually added.

**Comment by Frooxius** [comment]
Sorry, this won't get changed. Originally there was no shadow ramp, which made the material confusing to users, because it wouldn't really shade well, so default ramp was added. The material is meant to be used with a shadow ramp anyways, so it actually reacts to lighting.

You can simply clear it if you don't want it or change it for a different one, there's never going to be a perfect default. I changed it to a softer one in the latest build, which should look better.

**Comment by TehTurk** [comment]
Ah that's a shame, I'll have to check the current and find a good default then and see. Typically the issues I'd run into is the model doesn't play well with the orientation, or people will come in with mis rotated ramps making them look like some sort of horror monster. I'm more so posting this in consideration for the default user who has no clue what they are doing.
