### ISSUE TITLE
Scan Depth Integer for Dynamic Impulse Triggers

### ISSUE THREAD

**Issue by H3BO3** [Frooxius/NeosPublic#843]
Add an input int for both styles of dynamic impulse trigger that determines how deep into the target slot it searches for receivers when pulsed. No input would result in infinite scan depth or whatever the default currently is.

**Comment by shiftyscales** [comment]
Those nodes are intended to be directed at a specific target hierarchy that definitely contains the dynamic impulse receiver that will accept the trigger.

Do you have any specific use-cases, or underlying considerations for why you're making this request, @H3BO3?

**Comment by H3BO3** [comment]
Optimization - Controlling how many slots are looked through if you know the receiver will be at a certain level.
Flexibility - Allowing for weirder setups where sometimes you may want to only pulse higher receivers, and sometimes lower ones/all of them.

I have five reactions of support on my discord idea post from Zyzyl, Bitman, Turk, Alex, and Monsoon. I presume they have applications in mind as well.

Another aspect is that a -1 int or whatever that standard is should force default scan depth as well.

**Comment by mralext20** [comment]
ah, my reaction was meant as a 'yes, do go make a issue for that', rather than a 'i would like this feature'  

sorry for miss representing my opinion.

**Comment by shiftyscales** [comment]
Negative one is also already reserved for 'infinity' for scan depth for reference. If you know the receiver will be at a certain level though, you could just place the target hierarchy at that slot? And if you weren't entirely sure, I imagine you could use the get child nodes in conjunction with the highest known hierarchy on the trigger to get the same effect?

**Comment by AMonsoonofBabies** [comment]
For more context, this issue stems from an observation I made, which was that a lengthy setup I had created seemed to run at different speeds based on whether the LogiX nodes were packed or not. General thoughts on this were that the additional visual slots placed on all the nodes increased search time for all the dynamic impulse triggers, as there were many more potential slots to go through and check for tags. If this is true, and dynamic impulses could benefit from limiting the search depth, then users could have more control over vastly more complicated setups in the future that depend more on how long it takes for operations to complete.

It is true though that more clever thinking can be used to be more specific about the targeted dynamic receivers. I will admit that I personally can't think of an immediate practical use of it right now beyond being able to ignore LogiX visuals for consistent run times between packed and unpacked script, or other contexts where performance is low because of other factors.

**Comment by H3BO3** [comment]
Alright, so -1 sounds good for that.

The scenario you list doesn't seem to satisfy the optimization potential and doesn't allow for the flexibility gained by limiting search depth. Finding the slot by name would be a potentially recursive slot scan in itself. What you are suggesting is the inverse of what a search depth limit would achieve, perhaps optimizing from the bottom but not from the top. It would still scan unnecessary slots beneath the receiver, like visuals during testing, as Monsoon experienced. Control and flexibility are the keywords here, otherwise you don't plug it in and the node behaves as it always has.

**Comment by Frooxius** [comment]
-1 would definitely be used for infinite search, since that's existing convention for others.

This could potentially be added, but I'm not too sure about it. One consideration is that later on the queries will be optimized for more efficient triggering/receiving, so it would need to work with this as well. 

However main thing is that it's fair bit hacky approach to some things. I'm not sure if controlling execution by determining the depth would be a good pattern to introduce, as it ties the actual hierarchy into execution flow a bit too much - even something like some processing that adds an extra slot in between could break LogiX programs, making some operations unsafe to do (e.g. compacting all LogiX nodes into a single object) and that adds a lot of complexity to other things, by ensuring that the exact hierarchy depth is always preserved as to not break LogiX programs.

There are much more elegant patterns if you want to control which logic you run and which one you do not.

**Comment by H3BO3** [comment]
Ah, I see. I do remember you wanted to optimize dynamic impulse execution in the future now. I did figure this would be for very explicitly designed things, so yeah, it might be deprecated in the future. Perhaps instead we could look more into the "Source" functionality as per https://github.com/Frooxius/NeosPublic/issues/737 ? I want to use it for validation purposes.

**Comment by Earthmark** [comment]
The use case I have for this is avatars that subscribe to world data, right now the best way to do that as I see is send a pulse to root (currently unbounded) that sends a slot to send the subscription to, the subscription controller recieves the pulse and sends a pulse into the slot provided by the first with a data source.

So, in my case this would be a great improvement!

**Comment by Earthmark** [comment]
One mitigation to my problem is to search for a named node within a depth though, so there is a strong mitigation.

**Comment by AMonsoonofBabies** [comment]
I think this request ultimately comes down to being more efficient with how dynamic impulses work, which would be done with Frooxius's aforementioned plans of optimization anyway. Adding search depth sounds good on paper, but it might just end up adding additional complexity and confusion that wouldn't be outweighed by whatever niche function it would provide. At least, efficiency was my reason why I liked this idea.

**Comment by Frooxius** [comment]
Yeah. The added complexity is pretty high, especially with things coming in the future and lots of other algorithms. The thing I'm really worried about is that simply removing a single parent or inserting one in the hierarchy will now have potential to break LogiX programs, which will be really hard to diagnose, debug and mitigate. I don't think using hierarchy depth for control flow is a really good idea.

I do want to optimize the dynamic impulses, so it actually builds an acceleration structure for more efficiently querying the targets later on, so that will help solve the performance issues. 

You can also do a node search first - search a particular child under the root and then send the dynamic impulse to that.
