### ISSUE TITLE
Materials: Stacking/Order

### ISSUE THREAD

**Issue by GearBell** [Frooxius/NeosPublic#844]
When you want to Add a new material slot to an object/avatar it will add it to the specific submesh that the last material on the list is at. For instance, if the eyeballs material is at the bottom of the list then when you click Add to the materials slot it adds only to the eyeball mesh. I have tried to rearrange the materials in blender so that the intended submesh that i want to have multiple shader effects on will stack only on that submesh, but neos keeps rearranging the materials list, making the intended submesh material on the top - meaning if i add a new material slot itll apply it to the wrong part of the avatar. Im asking for either 2 solutions please:
1) have neos maintain the materials list order that it is in blender/maya/3dmax/whatever program people use.
2) create a new component, a "Shader Combiner" where it has material slots, you put whatever materials in the list you want, then take the component, which now renders as a single slot material and put *that* into the selected model material slot on the mesh. (example: you have 4 materials, but you want 3 shader effects on just the eye material, so you use the "Shader Combiner" component, stack your materails for the eyes in that, take the new component singular material reference and put that into the models eye material slot. Now your eyes can have multiple effects cause its using a singular reference)
The first will allow a quick fix, but the second option will allow us to do more controlled visual effects on just about anything!

**Comment by TehTurk** [comment]
This would be interesting but I feel like this might be a little tricky handling the data underneath. I am aware Froox does want to make build able Shaders.

**Comment by GearBell** [comment]
buildable shaders might be a waaay down the line, for now this would help alot in the meantime. currently the only way to achieve this is to unfortunatly split meshes which becomes inefficiant.

**Comment by Frooxius** [comment]
The only proper way to do this is to split your mesh into pieces that you want to render with multiple materials and then duplicate the mesh renderer, each time with a different material and use either the RenderQueue on the material or SortingOrder on the mesh renderer to control in which order they render. 

Unfortunately neither of the 2 solutions is technically feasible
1. Blender/Maya/3DsMax and so on are not game engines and their graphical pipeline is very different. Unfortunately this means that materials do not translate 1:1 to the concepts and mechanisms in a realtime graphics engine, which is a lot more closer to the HW than those. You have to setup the RenderQueues if you want to enforce a particular order

2. This doesn't fit into realtime graphical engine either. Each mesh renderer (particularly submesh) and material represent a single "rendering unit". Rendering unit can only have a single mesh and single material.

If you want to use multiple materials, you need multiple rendering units. They can use the same mesh, but different material, but you need more of them - more of MeshRenderers. I could potentially make a UI tool, which will setup a combination of mesh renderers and materials with appropriate render orders, but that will take a while to build on itself, the fastest thing is to just do it manually right now.


Once we have custom shader support you'll be able to build a shader that does all the effects you need, instead of having to render multiple on each other, but that's further down the line. Your only option right now are multiple MeshRenderers and RenderQueues, sorry!

**Comment by GearBell** [comment]
alright. i suppose i can close this then. :(

**Comment by Frooxius** [comment]
I'm sorry :( I wish there was a nice solution to this, but realtime graphical engines are designed to work very closely how the GPU works for high performance, so you have to build stuff around that.

The most  that can be done there is the UI to simplify the setup, but it would still do the same thing under the hood.
