### ISSUE TITLE
Camera anchors attach to tool shelves long range

### ISSUE THREAD

**Issue by Ruikio** [Frooxius/NeosPublic#848]
Seems like it's working just like the bug a few months ago where cameras and the full body calibrator was attaching to people's tool shelves from medium / long ranges.

To replicate:
- Spawn a camera anchor
- Move it around near your tool shelf.

**Comment by Frooxius** [comment]
What's the maximum distance that it attaches at? Is it unlimited or is there a certain range at which it stops attaching? 

How are you spawning the camera anchor? Is it through the interactive camera dialog? Or spawning a copy of it from the inventory?

**Comment by Ruikio** [comment]
No idea the maximum is. It seemed long though. When I tried to replicate, it only seemed to attach at a medium range. Meanwhile when it happened randomly, the camera attachment was maybe 8 meters?

The camera anchor is being spawned via the interactive camera screen thing?

**Comment by shiftyscales** [comment]
I've not been able to replicate this so far either using the camera control panel to spawn the anchor. The camera had to be released fairly close to the toolshelves to attach to them in testing.

**Comment by Ruikio** [comment]
https://clips.twitch.tv/BlightedYummyPlumberCclamChamp
https://clips.twitch.tv/CrunchyAntediluvianIguanaWutFace
https://clips.twitch.tv/ShakingArtsyHyenaChefFrank

https://clips.twitch.tv/SmokyPiercingMangetoutGivePLZ

New findings. The anchor doesn't attach long range. You need a camera inside the anchor.

**Comment by CuriousNicholi** [comment]
Is this the issue you're referring to @Ruikio ? My left had is out of frame, but any active Camera Anchor attaches to my hand from about 30cm away.
https://youtu.be/yUXD3Zbsupg

**Comment by Enkiko** [comment]
Many times now I've gotten the camera stuck in my tool shelf, and even at 10m+ the camera won't detach from the toolshelf. (Well, when I'm holding the camera it parents under my hand, but immediately parents to my toolshelf again when I let go)
The camera is attached to an anchor according to Alex, and indeed if I save my avatar whilst it's attached, it'll load the avatar next time with just an anchor attached to it.
So, I need the camera for streaming purposes, so this is the streaming camera that pops out when you open the camera facet. I've had the camera altered so that it's image can be accessed by a screen, in order to stream footage, and I've duplicated one of my shelves, to make attached items saveable.
But it's not just me. My camera got stuck in Brayton and Alex's toolshelves too.
A Monsoon of Babies says he can't grab the stream camera in manual mode because he knows it'll get stuck to his toolshelf.

**Comment by shiftyscales** [comment]
Okay, I've finally got some solid replication steps down. They're kind of strange, though.

- Create a camera anchor
- Place the camera in the anchor
- Grab the camera and attach it to your toolshelf
- Detach and reattach the camera to your toolshelf a few additional times
- After being detached and reattached a few times, the toolshelf will grab the camera from seemingly any distance on the hand opposite of the one you released it- e.g. if you release with the right hand, it attaches to the left, and vice versa

Observations:
- The camera range to reattach to the toolshelf seems to increase each time the camera is attached and detached
-- If the camera has only been attached to the shelf once while in the anchor, it is often easy to move it out of range of the toolshelf so it doesn't reattach (sometimes this issue seems to happen on the first time it attaches though- haven't fully figured out the behavior)
- This effect lasts until the anchor is deleted

**Comment by Frooxius** [comment]
Fixed in 2020.11.8.605, sorry it took so long!
