### ISSUE TITLE
Add Options for Mirrors/Cameras to Only Render Player Avatars

### ISSUE THREAD

**Issue by StarfishHidari** [Frooxius/NeosPublic#857]
As a performance option for Mirrors and Cameras, add an option to only render player avatars. This is a very standard feature across other vr platforms and is a very helpful performance option to have available.

The camera currently has selective rendering but requires parenting all users to a slot in order to only render them, this option is not available on the camera portal. Adding an option to render only player avatars for both the camera and camera portal components will be helpful for creating performance options in worlds when users cannot handle rendering the background world in mirrors.

As an example, here is a mirror rendering both player avatars and the world;
![fi68bunh](https://user-images.githubusercontent.com/11951324/89481025-d3e62c00-d764-11ea-8bf0-c0a91741ad21.png)

And here is a mirror that is only rendering the player avatar and skybox behind, the world is not being rendered;
![y5nppzvp](https://user-images.githubusercontent.com/11951324/89481094-fd06bc80-d764-11ea-9bf2-e1a908ee5be3.png)

**Comment by shiftyscales** [comment]
This would be better handled by using layers, rather than selective renderers/exlcusion lists.

Using the exlclusion lists enables some problematic behaviors, and could potentially block additional optimizations down the line.

If performance is a consideration, I would suggest you utilize a camera instead with a selective render list under which users are parented to based on a collision volume near the mirror as discussed in the Discord.

Selective rendering would be very inefficient because it would need to iterate through the entire hierarchy of the world every single frame to mark each slot as active/inactive, and would actually hurt performance significantly by utilizing a lot of CPU time.

Once layer support is integrated at some point in the future, this will not be an issue as this could be made in an efficient way.
