### ISSUE TITLE
[meta] Voting/ Putting money towards issues

### ISSUE THREAD

**Issue by sirkitree** [Frooxius/NeosPublic#861]
I wanted to open this as a discussion to see how the community and project owners feel.

What do you think about being able to donate money towards particular issues?

I think this might be a way to indicate to @Frooxius which issues are more important to the community and help him determine priorities possibly. This would be a sort of "bounty program" where anyone could donate money to an issue, sort of voting to say just how important it is for you to have.

There are websites out there that can help in this regards, such as bountysource.com

Alternatively, we could setup some sort of voting system. Perhaps just some instructions along the top of GitHub to vote for an issue with a 👍 on the OP.

**Comment by Frooxius** [comment]
A vote system would be good, that could help sort priorities on issues. The upvote one could be used, GitHub supports sorting by it using `sort:reactions-+1-desc` as search criteria. However it's not too formalized and not too easy to see.

I really like something like https://www.uservoice.com but we'd probably have to migrate a lot of issues towards that. 

I wouldn't do the donations however. We're not at the stage where we could focus at multiple issues at once, I can generally focus only on one major thing with a bunch of smaller issues on the side, so donating towards particular issues wouldn't really speed things up much.

Priority for the issues is a fair bit complex too, since a lot of things have pre-requisites and I tend to adjust them based on what will be most efficient way to handle them. With small team like ours, development efficiency is crucial. But it depends a bit on how big of issues are we talking.

Even with the voting it can be a bit misleading. Currently the most upvoted issue here on GitHub is Linux support, but that's something that affects relatively small portion of playerbase. Priorities change too over time.

I think it could definitely help prioritize some of the smaller things. We're considering putting some of the bigger ones on Patreon, since they change the major focus for a while.

**Comment by sirkitree** [comment]
Thanks for the reply :) It's imperative to know your thoughts on this matter.

We could add [issue templates](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) to this repo which would allow us to add some guidance on this when folks create new issues.

We could also update the README which would give some guidance on this process. I'll propose a change through pull request. 

Or we could open a new issue that has simple instructions in the body and pin that.

I wish you could put a header on all of the issues that would say something to this effect but I don't see a way to do that currently.

**Comment by sirkitree** [comment]
ref #871

**Comment by sirkitree** [comment]
Closing as this doesn't seem to be a viable idea
