### ISSUE TITLE
Provide inventory retention graph for the user

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#874]
I've seen a few people now have issues with freeing assets, towards that end I'd like to help users understand why they're having high retention rates.

The best way I can think to do that is for the user to have access to the retention graph (probably a graphML file or something) anotated with asset size and what nodes are strongly referenced in the inventory / worlds (along with the paths of those nodes). From that it should be pretty easy to visualize and color, giving a user a view of exactly what is keeping their storage full.

Please let me know if it's viable to provide this graph, I get it would touch a database table possibly a lot, but I think it'd end up being petty cheap as no actual assets need to load.

**Comment by Earthmark** [comment]
I should clarify, give access to the graph and it'll be possible to make the tool, I'm not asking for the tool itself!

**Comment by Frooxius** [comment]
Having UI for analyzing the storage usage is planned, but will have to come later, since it's a fair bit of work to implement. The best thing right now that you can do is to send the `/requestRecordUsageReport` command to the Neos account in your friends list, which will email you some usage statistics and then start deleting things you don't need that take up the most space. 

For the full UI what I'd do is list the biggest assets on your account and then for each show which records (worlds/items) are using that one, so you can decide if to delete them or not.

I don't really know about providing the graph though, I'm not sure how exactly do you want it to be mapped to Neos' concepts. Storage is calculated based on records you have stored (those are technically flat, though they can have associated path, but that's just user convenience for browsing). Each record has an asset manifest. As long as there's at least 1 record on your account that has given asset in its manifest, it will be "pinned" on your account and use storage.

**Comment by Earthmark** [comment]
With this comment, "then start deleting things you don't need that take up the most space.", Does it not delete things by default as you remove assets?

What I'm proposing is I can make the "full ui" kind of thing using a web browser cause that's a really common class of problem if it's in the graphing a graph space, see tools like http://sigmajs.org/ . In this case I hope to color code the nodes by type, and the size of the node represents the asset size. Users can see "this inventory reference has like a hundred massive nodes connected to it... And nothing else connects to those nodes" and now they know about their problem asset! The good thing is it also shows that even if it's a cluster of records that have the heavy references.

In this case consider every record a node, this record-node is decorated with a user recognizable name and probably an ID valid internal to the file for defining edges (I don't know if the actual neos ID is sensitive).
Also consider every asset also a node, where it is decorated with the asset size, same kind of ID, and possibly a name if one exists so people can understand what is taking so much size. I'll recognize assets versus records by if they have a size field (alternatively they could be tagged with something).

Note that records do not have a size, the point of this is to understand size better than the total retained size metric currently in the inventory.

Append both lists together, and map the asset manifest of every record to be a list of edges defined as a pair of IDs (preferably directed with source being the record ID the destination being the asset ID). This edge list will be possibly massive, that's fine.

Provide access to that kind of file, i can provide a temp visualizer until ya get the fancy graphics in, because users seem confused as to what is retaining what.

Here's an example file in this format
```json
{
  "nodes": [
    {
      "n": "potato cannon",
      "i": 0
    },
    {
      "n": "yodel tube",
      "s": 1024,
      "i": 1
    },
    {
      "n": "Roman Column",
      "i": 2
  ],
  "edges": [
    {
      "s": 0,
      "d": 1
    },
    {
      "s": 2,
      "d": 1
    }
  ]
}
```
I can add more for clarification but typing json on my phone was a mistake I will not repeat again.
If you would prefer putting the edge list on the record node this one as well

**Comment by Earthmark** [comment]
I fat fingered the close button.

**Comment by Frooxius** [comment]
Hmm what I could do is simply export a list of all records as a JSON, along with their asset manifests. Would that be sufficient? It could be a similar command, which would send you the generated JSON rather than a text report. The asset manifest contains the asset signatures and their sizes in bytes. You'd have to build a graph out of these yourself, but that shouldn't be too difficult.

Each record essentially looks something like this:

```JSON

{
    "id": "R-Home",
    "assetUri": "neosdb:///abcd.7zbson",
    "name": "Home",
    "recordType": "world",
    "ownerName": "SoliTest",
    "path": null,
    "thumbnailUri": "neosdb:///abcd.webp",
    "isPublic": false,
    "isListed": false,
    "creationTime": "2018-11-12T19:56:45.1274545Z",
    "firstPublishTime": null,
    "lastModificationTime": "2019-04-29T11:30:46.6929995Z",
    "neosDBmanifest": [
        {
            "hash": "aaaaaa",
            "bytes": 3846
        },
        {
            "hash": "bbbbbbb",
            "bytes": 10202
        },
        {
            "hash": "ccccccc",
            "bytes": 10379
        },
        {
            "hash": "ddddddddd",
            "bytes": 41690
        }
    ],
    "ownerId": "U-SoliTest"
}
```

**Comment by Earthmark** [comment]
That'd be perfect! I'm happy to parse on my end, and the hashes will act as perfect IDs.

**Comment by Earthmark** [comment]
I have a very rough visualizer here, I made some assumptions about the output payload and it's got no error detection, but it's an attempt on making it easier to figure out where the problem assets are. (The larger the node, the larger the payload size)
https://github.com/Earthmark/NeosStatbox/blob/master/index.html

**Comment by Frooxius** [comment]
I've added `/requestRecordUsageJSON` command, which will send you the JSON now, you can use it for testing. It will email you a JSON file with the report.

However I'm considering actually replacing the asset hashes with just generic asset IDs, because sharing this file will let anyone spawn anything from your account, since it includes all the private stuff as well and I'm not sure if people will be savvy/responsible enough to be careful how they share the generated report.

**Comment by Earthmark** [comment]
As long as it's reliable to cross key things inside the report, sounds good to me!

**Comment by Earthmark** [comment]
Also, thank you for the quick turnaround time there, I'll get to testing.

**Comment by Frooxius** [comment]
No problem, I just extended the code that generates the usage report!

It would be enough for that. But you wouldn't be able to tell which asset is which, so if something is using a lot of space, you can't tell what it is.

I think I might leave it for that reason. It already contains listing of everything in your inventory anyways, so sharing that alone would be dangerous. I'll add a warning when it's being generated.

**Comment by Earthmark** [comment]
Sounds good to me, I can make sure the tool has a disclaimer as well about "Do not share pictures of the values in this page", it's intentionally not doing any webby things besides downloading the rendering libraries.

**Comment by Frooxius** [comment]
I've added a big warning to the email with the file. Hopefully that'll be enough, combined with the command being more obscure, so people who use it know what they're doing.

**Comment by Earthmark** [comment]
Thank you Froox, I'll mark this as resolved as now the info is accessible.
