### ISSUE TITLE
Problem when using logix node "Open World"  with local headless server with customSessionId.

### ISSUE THREAD

**Issue by SUPTEC-Gourry** [Frooxius/NeosPublic#885]
When "Open World" is used on a customSessionId on a local headless server (same network) it get stuck on loading state (if i use the local ip address and port, like lnl:///192.168.254.158:59894 as url it works fine).
Logix: 
![2020-08-07 22 00 27](https://user-images.githubusercontent.com/69479081/89816358-d35ee400-db1c-11ea-91a2-a69cc84a8740.jpg)

Result:
![2020-08-07 21 26 03](https://user-images.githubusercontent.com/69479081/89816374-deb20f80-db1c-11ea-8fa4-89e3f5239599.jpg)

**Comment by Frooxius** [comment]
If you use the lnl-nat:// URL, Neos will attempt to connect through your public IP to the session. If your network is correctly configured with IP loopback and you have multiple LAN adapters on the hosting machine, this won't work, as you can't connect to your own session.

I recommend switching to neos-session:///<sessionID> URL instead, which will automatically look up appropriate session URLs. This will work better long term as well, because we'll eventually switch to different transport protocols (even right now, people might prefer the Steam Networking Sockets instead). 

In the next build I'll tweak the system so it uses local data for the lookup with this URL as well, which should automatically discover the local IP.

**Comment by Frooxius** [comment]
The change is now done in 2020.8.10.1195. You still have to switch to neos-session:/// URL instead though, lnl-nat won't work unless you have your network configured for it.
