### ISSUE TITLE
Use user facing direction when spawning objects

### ISSUE THREAD

**Issue by ProbablePrime** [Frooxius/NeosPublic#893]
1. Spawn any image. 
1. It spawns the wrong way around

I swear this was reported before but couldn't find the bug report. I know its been mentioned a few times in the discord.

It became quite annoying today when arranging a large amount of images in a world.

**Comment by shiftyscales** [comment]
The photos spawning backwards is actually because of a mechanism (or lack thereof?) in which items spawned from the inventory are oriented based on the user's global/playspace orientation. So in this case, you were physically facing backwards in your playspace.

Personally I would much prefer if objects were to spawn using the user's head/facing direction. This would also fix numerous other objects from spawning in the wrong orientation too, e.g. mirrors, etc.

A clip demonstrating physical/playspace rotation, vs rotating with the joystick: https://cdn.discordapp.com/attachments/439422161657135106/743034254618787910/2020-08-12_02-08-36.mp4

**Comment by Frooxius** [comment]
Fixed in 2020.8.13.259, thanks!
