### ISSUE TITLE
Floating point percision breaks the Value Equality drive

### ISSUE THREAD

**Issue by RueShejn** [Frooxius/NeosPublic#896]
the value equality driver will not function at all due to very small decimal place inequalites, like if its atleast .00000000000000000001 off it wont work.

steps to replicate

add value equality driver(FloatQ)

target any slot and set that as the reference in the equality driver

it will never be true

**Comment by Earthmark** [comment]
Just to snowball issues, the == node does not use an epsilon comparison either and it's similarly impossible to use in practice, can those nodes be made useful as well?

The == operator uses an epsilon comparison for quats, but not for floats or float vectors, making it really annoying to use in practice, making them 'just work' in a sane way for most use cases would be great!

**Comment by Frooxius** [comment]
This is not really a bug, this is just how floats work. You should pretty much never, ever use direct equality for floats, unless they're specific values like 0 or 1.

The == node won't change, because it would ultimately change what it represents. However I can add another node for approximate comparison, with configurable (optional) epsilon.

Similarly I could add optional epsilon to the ValueEqualityDriver which could help in this case as well.

**Comment by Earthmark** [comment]
Since there == node is what users go to for comparing two entities, could that node similarly get the extra parameter treatment? That way it helps teach that float comparison should be different than the rest?

**Comment by Frooxius** [comment]
No. == represents actual native equality comparison operation, that's the exact same one as you get in C#, C++ and many other languages. I do not want to deviate from those established conventions and change its meaning, so it has to be done through introducing a new node for datatypes that support approximate comparisons.

**Comment by shiftyscales** [comment]
As of 2020.8.14.437, the approximate comparison node `≈` was introduced which should suit the needs of this issue.
