### ISSUE TITLE
Recently added debug nodes should go in the utility folder

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#907]
Seems like a simple change.

I know myself and atleast one other have messed up muscle memory for where certain folders of nodes are ( slots and flow moved to the other side of the panel for example)

**Comment by Frooxius** [comment]
I'm sorry, but I don't plan on relocating them. Debugging functionality is going to be quite common so it should be top-level category of it's own.

The categorization isn't fixed and it's subject to changes and additions, preserving whatever the current set of categories is long term isn't a design constraint I want to put there, because it will make categorization messy.
