### ISSUE TITLE
Component request: User Profile Avatar/Icon provider

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#916]
the requested  component should provide the given user's profile photo (as seen in the friends menu), like a static texture2d.

**Comment by H3BO3** [comment]
Wouldn't this be better as a component? It could provide the texture directly, acting as a provider depending on the user given to it

**Comment by mralext20** [comment]
why not both ;)

**Comment by H3BO3** [comment]
Because it's redundant I think, components make more sense for this kind of thing. Do you have an application where you'd need the url instead of the image directly?

**Comment by mralext20** [comment]
no, not really. i guess a component would be just as good.

**Comment by TehTurk** [comment]
Wouldn't this get introduced when the Friends Tab is Facetized?

**Comment by Frooxius** [comment]
Yeah this would be added as a Component that provides user's profile information in general, the same way other "Facetized" parts of UI were done. That way it's general enough. Doing a node just for this isn't likely going to be a thing, because that'd be redundant and there's hundreds of different properties that you might want to access overall, so it doesn't scale too well.

**Comment by mralext20** [comment]
Added in 2021.1.11.642
