### ISSUE TITLE
Unpack and Pack numeric primitives (float, double, char, int, long...) into bytes

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#927]
A lot of people have hand made parsers right now, however most of them need to do some form of bit masking to get form characters into some other primitive right now.
This is kinda hackey to get around collections, but one space that's been particularly problematic is floats and doubles, where there isn't a good way to do bit masking on the objects and convert the floating point number into bytes for binary serialization.

Can we get pack/unpack nodes that go between bytes and those compound value types? I get endianness is a problem, but if the pins on the inputs and outputs are labeled most to least significant bit, people can deal with endianness in their own way. C# should be able to magically convert the format into the correct endianness as well, so this should be a pretty small node to add hopefully?

**Comment by Frooxius** [comment]
Hmm, there are multiple ways to approach this. One would be is to reinterpret the float as uint (and double to ulong) and vice versa. This would let you use all the normal functions for bitmasking of getting individual bits. Another would be to simple give you 4 byte values for floats and 8 for doubles and you could work with those.

I'm not sure which approach would be best here. Endianess can be checked and auto-converted, but question is whose responsibility that is, because it will need to maintain consistency with that. E.g. ExtractBits node doesn't handle endianess right now, although that could be added to them, since it wouldn't change behavior with existing code.

**Comment by Earthmark** [comment]
Preferably the mode where it gives you the raw bytes so it's a lossless operation to unpack-repack the float, the goal is deserializing and serializing floats with less hackery than goes on right now!

**Comment by Earthmark** [comment]
Ah, I see what you mean now, I think if a reinterpert is done then the end user may need to care about endianness, as I think floats specify endianness where as ints it becomes platform dependent?

**Comment by Earthmark** [comment]
Resolved as of 2020.10.26.1103
