### ISSUE TITLE
Request: Add Options to trigger flags within Debug Menu and NeosLauncher to Clear Cache, Repair Database, and Clear Queue 

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#929]
While this doesn't prevent the finding and fixing of what causes the issues in the first place, it allows end Users to at least fix the issues in a more streamlined way adding some QOL. 

First two would be more flags set on restart, while the Clear Queue is more of a in-game thing as there are times where the Queue will just get clogged, and while I know it's been said to "let it sync" either let users restart their queue, or at least clear it, and rejoin the world so that things might be properly obtained.

**Comment by Frooxius** [comment]
I'm sorry, but these won't get added.

- Clear Cache is something that needs to run while Neos isn't running right now, once it starts it's already too late. You should delete it manually or use a disk cleaning utility, those will typically delete the temporary folders. Proper implementation will allow to actually remove the cached data on the fly and manage the maximum size of the cache
- Repair Database is invoked automatically when there's a corruption or problem detected, you shouldn't ever have to trigger it manually. If you're having problems that make you want to run the repair, please report those
- The queue doesn't support clearing, it's not really a concept that fits in how the system is designed. If assets can no longer be transferred (e.g. leaving session) they are cleared automatically. Otherwise the lifetime is managed by the asset requests in the system and forcefully cleaning it would cause more harm then good. If things get stuck and such we need to address those and investigate why, having a replicable scenario would help.

**Comment by TehTurk** [comment]
I understand, but there are other utilities that can do this and are ease of use and built into the programs themselves, I ask that you consider this at least in some shape or form for the end user because oft not people aren't willing or accepting to do extra work to fix something small like that and little things like this added up in their perception of the platform, and I only post things like these because oft not people won't speak about these problems, or be blunt about the issue, they'll just give up or stop using the platform. We are lucky that people are willing atm. At least consider some of these if not all. 

They could be implemented in the Launcher, restart flag or even in some other form of your choosing. This isn't even a "right" now kinda thing, just wanted to get some acknowledgement or feedback on it vs it being closed right away.

Cache: I don't see why it couldn't prime something to be run at Neos Close, Neos currently autosaves as a way to prevent file or sync loss so I don't understand why if it can save it can't clear as write access is ubiquitous.

Database: It does do this yes, but it can't account for "Everything" user input will be needed everyone now and then and most Users will not be willing to fix things like this, ease of use is important Froox.

Queue: Yes you've told me of this before, but the Queues still get clogged regardless, for those on weaker connections you'll run into queue clogs alot more, so because of these they get way past in terms of the session, when stuff that gets sync'd or deleted might be gone and not even relevant to the queue anymore, and I figured it will only affect queue items sequentially not individually, or even having priority of certain request flip or change depending on urgency/time/date. Is there no way to have a dropped request in term of how network packets work?

**Comment by Frooxius** [comment]
I understand the problems, I'm just saying that these aren't the right solutions for them. If you're encountering those issues, please make issues about those and then we can discuss the solutions and what's needed, but since you requested those specific buttons that was closed since those won't be implemented.

There are many other issues and things that make people stop using the platform, but I'm handling most of the development alone, so there's only so much I can focus on. There will always be issues and bugs, so I'd rather take approach that's more efficient and manageable long term, rather than littering the system with quick hacks.

Cache: Because that's a lot of engineering for a "quick" solution to make sure it behaves and runs correctly, without causing more problems than it solves. The goal for proper solution is to have the cache be auto-managed, with the system clearing up assets it knows that aren't in use or weren't used frequently.

I generally tend to avoid doing these quick fixes, because they almost always just end up with tons of complications and problems and all the time spent solving those could've just been put into implementing the proper solution in the first place.

Database: I know that ease of use is important, that's why the system is designed to handle things automatically and avoid requiring the user to take action in the first place. I repeat, if there are cases when things aren't working correctly, REPORT them. Just having the user mash Repair Button on each problem won't ever get those issues fixed and will cause people to run into weird behaviors. Most people won't go looking around for help to have someone tell them to run the database repair, they will just go a way.

Queue: I don't really understand the question sorry. The queue has some priority system, but as long as download is running it will try to continue. There can be things done to ensure it doesn't get clogged, but I need more details. Regardless clearing the queue is just not technically possible how things work, it would break a lot of stuff.

**Comment by TehTurk** [comment]
sigh I get it :\ I'll try to be more vigilant and try to do what I can with what I have. 

Queue: Ah, there's times where if it's just one asset? Typically it'll just be stuck on that until it's resolved, so some sort of skip or at least a way to force it to the end of the queue since it's getting stuck. I was wondering if there'd be some sort of pause this download, focus this download, or a way for maybe putting priority on certain assets like audio/textures/etc. Is there a way to profile it at all?
