### ISSUE TITLE
Node to provide index of the first matching input

### ISSUE THREAD

**Issue by mralext20** [Frooxius/NeosPublic#936]
i.e. if the 0th input is valid, then the extra output would be 0. if the 1th input is valid, it would be 1. 

i would imagine if no outputs are valid then -1 is returned.

**Comment by Frooxius** [comment]
I'm sorry, but this won't be part of the operator, since it doesn't really fit the definition of the operator - it only has a single output. It's pretty much 1:1 this: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator

I could add a different node that will give you the index of the first non-null input or more generally index of the first matching input, that would be more generic.

**Comment by mralext20** [comment]
The original use case I was imagining for this can already be achived with impulse multiplexers and regular multiplexer/demultiplexers.

 Without objection, I would like to close this.

**Comment by mralext20** [comment]
The original use case I was imagining for this can already be achived with impulse multiplexers and regular multiplexer/demultiplexers.

 Without objection, I would like to close this.

**Comment by H3BO3** [comment]
I think a generic operator for this would be nice, kind of like a Switch statement. I think this should stay open
