### ISSUE TITLE
"Audio bug" replication case

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#937]
Discovered while investigating another issue for Enverex, if you leave, and join an asset-heavy world like his currently unpublished 'deep space' world numerous times (in my testing, the issue occurs reliably on the fourth join), the audio quality will rapidly degrade, and stutter. Neos will stutter briefly anytime a sound clip plays.

For additional details including the world URL, refer to this Discord message: https://discordapp.com/channels/597712650729947149/598212542938218506/747955732015480847

This may also be related to #511.

**Comment by Enverex** [comment]
For anyone that's not familiar with how it sounds - https://cdn.discordapp.com/attachments/439422161657135106/750126197777891370/2020-08-31_23-51-22.mp4
(taken moments before Neos crashed with another Unity Media Player error)

**Comment by Frooxius** [comment]
I've done some testing with the world and confirmed two things:

- The crash is due to the UMP video playback. After several loads and unloads I would crash. After knocking out the UMP video player so it doesn't load at all, I could load and unload the world many more times without a crash, but glitchy audio would still occur. It would persist even after world is closed and other audio sources would stutter heavily even in empty world.
- The glitchy audio bug is due to the Steam Audio Spatializer. After removing it, I could load and unload the world many times and the audio would still remain normal (although non-spatialized), same with single audio source in empty world after the runs that would previously stutter heavily.

I'll need to investigate more and see if there's a way to replicate this in isolation, trying to break the system artificially so far hasn't resulted in much.

I'll see if pooling the spatialized audio sources would help work around the issue.
