### ISSUE TITLE
Particle System Initialization Freeze

### ISSUE THREAD

**Issue by RueShejn** [Frooxius/NeosPublic#944]
Neos will freeze very hard on the initialization of a particle system.
this will only happens upon the first instance of the particle system Initialization in a play session

you can test this by making a particle system and activating it(enabling/disabling the emitter)
you will notice Neos freeze for the duration of the particle effect

if you play the same effect again it will not freeze, even loading a new world and closing the old one, the effect will not cause you to freeze

if you then close Neos and restart
the first activation of the system will now freeze you again

note that ANY particle system played after the initialization Freeze will also not freeze you, it is only the first activation of ANY particle system in a play session

**Comment by Frooxius** [comment]
Hmm I'm trying to replicate this, but I'm having trouble reproducing this in a simple scenario. Do you have any simple object that would cause this to happen reliably? The metamovie monster has lots of animations and other things and it pollutes the profiler.

**Comment by H3BO3** [comment]
Does this have anything to do with particle physics? I thought only those locked up on first emission

**Comment by RueShejn** [comment]
i will try to get a simpler repeatable case as soon as i can
it might also be influenced by the amount of people in the world base on a small bit of testing shifty did earlyer

**Comment by TehTurk** [comment]
Updating some info here, but as per request of Shifty I did send my Death Anim to Froox for something to look at and compare. Me and Rue were initially talking about how the initial call to activate the emitters will freeze, but anything after will legitimately be fine as it possibly be due to how it's introduced into memory, then it's fine, this could also be similar in the effect of how duplicating certain objects can basically stall, the more you add, the more your data model locks up. For me it's basically elevated because instead of just reducing the amount of particles, I have 10 emitters to obtain a certain effect (I can atlas, but it was more so a quick and dirty to get the effect and didn't plan to use it forever, it's intensified when the collisions are occurring on said particles too.

**Comment by shiftyscales** [comment]
2021.1.24.1266
`- Fixed list particle system collision job data accumulating endlessly when there are particle systems with collisions, but no active particles, causing a significant hitch when the particles are spawned next time, with duration of the hitch proportional to how long ago they were last spawned (reported by @ Lewis Snow | Lead Audio Engineer, @ Rue Shejn | Artist 3D, @ H3BO3, @ Turk and others, with replication case found by @ Shifty | Quality Control Lead)`
