### ISSUE TITLE
When you have more than one Texture Thumbnail Source component in slot hierarchy, it ignores all of them.

### ISSUE THREAD

**Issue by guillefix** [Frooxius/NeosPublic#949]
If you have more than one Texture Thumbnail Source component in a slot hierarchy you are saving, it just ignores all of them. Perhaps a better behaviour would be to take the first one.

This seems to be determined in ItemHelper.SaveItemInternal

**Comment by Frooxius** [comment]
This is not a bug, it's intentional. This is done because you can actually grab a "bunch" of objects and save them as a group. If it did what you're proposing (it actually used to do this before) you'd get thumbnail of a random one, rather than the whole object group, which ends up producing confusing thumbnail.

E.g. if you grabbed 4 photos to save to your inventory, you'd get a thumbnail of a single photo, even though the item represents 4 of them.

There's no reason for you to have multiple thumbnail sources in objects you create, just make sure there's only one that you actually want used. There is "Ensure single thumbnail source" button in the inspector that you can use to remove all others.

**Comment by shiftyscales** [comment]
Ah, that makes sense, thanks!
