### ISSUE TITLE
DSP with LogiX system

### ISSUE THREAD

**Issue by FreakyWaves** [Frooxius/NeosPublic#953]
I am planning to do a **Virtual Modular Synth**, inside **NEOS** for the **MMC**,
I want to make it like [VCV Rack](https://vcvrack.com/), having to plug **virtual cables**, **going everywhere**
So I wanted to know if there was **a way, to build and audio buffer and send it to audio output**, either with **LogiX**, or by **thinkering** in the inspector.

And if there's **no way to send audio output directly from LogiX**, I might be asking too much, but basically all the math functions are there, I would **just need arrays and audio out**
**Array** is basically to build an **audio buffer**
Also I don't know if the **sampling rate** of **LogiX** would even be **able to make audible audio**

**Comment by Frooxius** [comment]
Hello. 

There's a system called "SynthX" on the long term roadmap that would allow for this - a system that will allow building synthesizers, effects and other audio processing setups with LogiX.

However this system is relatively a major project and isn't going to be prioritized in a while. Even if it was, it still would not be ready for the MMC, I'm sorry.

**Comment by FreakyWaves** [comment]
Would there be a way to import scripts / code from external assets I could make in whatever format ?

**Comment by Frooxius** [comment]
It's very unlikely to be in "whatever format", it will need to interact with Neos' API in some way. There are general plans to provide more scripting abilities, but nothing concrete yet. Currently I'm thinking about WebAssembly, because it would be very generic (and allow using runtimes for other languages as well) but it's not set in stone yet. It's very long term goal as well at the moment.

Currently you can make new plugins in C# and other CLR languages and load them at startup, but that makes the build incompatible with others and it's not fully supported, mostly just for experimentation.

**Comment by FreakyWaves** [comment]
I guess I will have to save my idea for later then,
Thanks for answering so fast.
