### ISSUE TITLE
Can't connect to server in game/ losing connection to server

### ISSUE THREAD

**Issue by JaWi179** [Frooxius/NeosPublic#954]
Okay so had the same problem the other day, it fixed itself somehow so i wasn't worried, but today the problem is back and it looks worse, so i could not log in to the game bcs somehow i wasn't connected to the servers, today i can log in but still after a minute or so i lose connection to the servers, and it's only Neos servers, i tested my internet connection and it's good and stable, i also open a twitch livestream in background for a minute to see if my connection goes away when i'm in game, nothing happend to the stream, please help

**Comment by Frooxius** [comment]
Hello.

How are you determining that you are losing the connection to the servers? Does the server status on the dash say "Down" or "No Internet"?

I checked the server status and everything is running fine on our end, so it's likely a connectivity issue. There seems to be a world-wide internet outage going on right now that's affecting several major services, including Azure which is what we're using: https://downdetector.com/status/windows-azure/ so that could be the likely culprit. 

When you don't have the connectivity to Neos servers, can you try accessing this website and see if it loads? https://portal.azure.com/

**Comment by JaWi179** [comment]
After a minute the connection in Neos goes to "No Internet", the Website is
loading fine

niedz., 30 sie 2020 o 15:18 Tomas Mariancik <notifications@github.com>
napisał(a):

**Comment by Frooxius** [comment]
Are you using any firewalls or security software that could be blocking Neos' connection? Does the issue still persist today? There was a major national internet outage yesterday, so that might've been the culprit.

**Comment by JaWi179** [comment]
I'm using only the windows defender but today the issue looks to be gone so
it might be the internet outage

pon., 31 sie 2020 o 12:39 Tomas Mariancik <notifications@github.com>
napisał(a):

**Comment by shiftyscales** [comment]
Glad to hear things are working for you right now. If you continue to have issues, please feel free to reach out here, or on our Discord, @JaWi179 (https://discord.gg/neosvr). I will close this issue, then.
