### ISSUE TITLE
Bug: Twitch Follow Events do not Respond

### ISSUE THREAD

**Issue by TehTurk** [Frooxius/NeosPublic#956]
I checked the node with Mooke and Vigilabo earlier today. It seems to not respond, or something internal to the API was changed.

**Comment by ProbablePrime** [comment]
Confirming I saw this too, I was also with Mooke but we were trying it on my Channel at the time whereas you were probably using other channels. So it affects multiple channels is what im saying :)

**Comment by Frooxius** [comment]
I've looked into this and unfortunately this is a problem caused by Twitch restricting their API. They have changed their endpoint that's used to get the channel ID from the channel name to require an authenticated user, so there no longer seems to be a way to do this anonymously. 

It seems to have broken a bunch of extensions and caused some uproar with the developers: https://discuss.dev.twitch.tv/t/requiring-oauth-for-helix-twitch-api-endpoints/23916/25

This complicates things significantly, because either it'll require you to login in some way (although I'm not sure how would OAuth even work in this context) or I'll have to do the requests from the Neos cloud API. I'll investigate the possibilities or if there's another way to fetch the channel ID based on its name.

**Comment by Frooxius** [comment]
Ah of course I find another endpoint to use instead a few minutes after I post this! :D Seems the older V5 API allows anonymous access. It seems to work, fix coming soon!

**Comment by Frooxius** [comment]
Ok pushed in 2020.9.3.56, thanks!
