### ISSUE TITLE
Please allow rebinding double escape, or providing a dialog guard for world close in desktop mode

### ISSUE THREAD

**Issue by Earthmark** [Frooxius/NeosPublic#974]
Games and software have taught me over time to hit escape to get out of menus or regain control if there doesn't seem to be a way to do so.

This has gotten to the point where if I can't provide an input into a system (or suddenly a whole mess of autocomplete windows if it's code) pop up when I'm not expecting I hit escape a few times to break out of it.

This doesn't do great neos wise, where that closes the world. At least three times now I've accidently clicked what turned out to be a text box, my brains gone "screw this crap give me back movement control" and I hit escape a few times... Closing the world.

I can't think of another context where mashing escape has a destructive consequence, pretty much every other time it bails out of menus until you get to root (possibly promoting you to close the app with a menu that does not accept escape), or it does nothing (which is also very annoying).

I get that this is a tick of mine, but maybe I'm not the only one, and it's always very frustrating when I accidently close my world this way.

Preferably a dialog that asks if you want to actually close the world would be good in my eyes, would prevent the accidental closures.

**Comment by Electronus** [comment]
I remember this happening to me when I used desktop consistently. Definitely second this  suggestion.

**Comment by Frooxius** [comment]
I'm sorry, but this won't happen for the current desktop mode. The desktop mode isn't officially supported right now and the current one is mostly just a hack for debugging purposes, so it's really hard to add new behaviors to it, let alone something as complex as rebinding system. For that you'll have to wait for the proper desktop mode:
https://github.com/Frooxius/NeosPublic/issues/151

I could change the action to be hardcoded to a different combination though. e.g. Shift+Esc or something like that. The new dash lets you manage and close worlds as well, so that helps too.

**Comment by Earthmark** [comment]
A shift in shortcut would resolve my issue as well, it's that the current shortcut is only using the escape button that causes the negative behavior for me.

**Comment by Frooxius** [comment]
Changed the shortcut in 2020.9.5.1190, hopefully it helps for now!
