### ISSUE TITLE
Scroll Rects and Masks break everything at a curtain point.

### ISSUE THREAD

**Issue by candypheonixIO** [Frooxius/NeosPublic#991]
Self-explanatory, and you can access the world [here](http://cloudx.azurewebsites.net/open/world/U-SmolCookie/R-f97da7f2-5cf1-4ab0-94dd-0ed835c8a4eb)

Simply changing the active state on the two "screens" causes the masks to become corrupt, this is sadly nothing new, it can be seen on my other video player, and my current _halted_ youtube player project. I'd like to have this looked at.

[Video Evidence](https://youtu.be/rUbCPcIzxg4)

**Comment by TehTurk** [comment]
Poking at this I think it might have to do with Recent RectTransform Changes.

**Comment by candypheonixIO** [comment]
another example of the same bug.
It's not hard, nor impossible to re-create, and I really need this fixed so I don't have to make hacky bloated logix just to work around it.
[Video Evidence #2](https://youtu.be/9nJwJYIMUqQ)

**Comment by candypheonixIO** [comment]
I will have to postpone this project, or work on different aspects of this project until this is fixed, or I build up the courage to build useless logix to delay a boolean just to properly disable/hide a ui element.

**Comment by Frooxius** [comment]
It will help prioritizing this higher if you could provide clearer description of what the bug is. I checked the world and video, but I wasn't entirely sure what I'm looking for, so I left it for sometime later.

Having replication case helps a lot, but it's not a substitute for proper description. Particularly what's important:

- How it breaks? What's the expected result and what's the one you get instead?
- What are the specific conditions that trigger this? Are the masks anywhere in hierarchy?
- Any errors in the log or any other pieces of information relevant to the problem?

If it takes significantly more time on my end to determine and answer those questions, the report gets a lower priority over other reports and will have to wait longer or increase in urgency over others.

**Comment by candypheonixIO** [comment]
Here is a video, showing the examples in the world provided, along with showing _again_, and talking about _again_, what is happening. 
[Video Link](https://youtu.be/5KFZrPl5DJo)

I've sent the logs to shifty and hope they are able to find any dependencies regarding the ui.

And if you don't feel like watching the video:

- It breaks when you disable the parent of a masked element, whether its for a scroll area or not. The intended result is to have everything hide, but when you disable the parent, everything that was under the mask remains visable, but not intractable.

- Specific conditions can vary depending on how you need to set up your UI, but as long as you have a masked element under a parent and you disable that parent, everything under the mask will remain visable but everything outside the mask will hide under the disabled parent.

- I don't know what to look for in the logs, but I have contacted shifty and provided the logs to them.

If this comment doesn't answer the three criteria, then watch the video, and if that still doesn't answer the criteria, then can we get UIX debug tools? because this isn't the only repeatable bug with UIX, but this is one of the worse bugs that has hindered my progress several times while working with UIX.

**Comment by candypheonixIO** [comment]
Here we are again, with another very similar setup that will cause the same bug shown/demonstrated in the video above.
[Video Link](https://youtu.be/YQJ9GWbfPto)

**Comment by shiftyscales** [comment]
I visited SmolCookie's world with him so he could explain the issue a bit more- the general gist of the issue:

If you set the parent to a slot that contains masked elements to inactive, the masked elements will remain visible unless the masks are explicitly disabled before the slot is.

**Comment by Frooxius** [comment]
Should be fixed in 2020.10.1.1403! Like I mentioned in my previous message, showing more examples wasn't the issue, lack of clear description and information was.

If you'd like the issues to be fixed faster, I'd recommend reading up on how to make better bug reports:
https://steamcommunity.com/games/neos/announcements/detail/2174620391980332120
https://medium.com/pitch-perfect/how-to-write-the-perfect-bug-report-6430f5a45cd
