### ISSUE TITLE
Auto-open menus when circle is filled for WMR/Vive

### ISSUE THREAD

**Issue by shiftyscales** [Frooxius/NeosPublic#992]
Upon the circular ring being filled from the context menu button being held, the corresponding menu could auto-open.

This could also be accompanied by a confirming visual, e.g. the circle flashing.

Users have provided feedback that they are confused by the circle not doing anything once filled, and hold it longer than necessary.

I've also heard of cases of the menu being open inadvertently, perhaps the time to fill the circle could be very slightly increased?

There is also a region of the circle around three quarters filled where if the button is released neither the context menu or the dash will open.

**Comment by Frooxius** [comment]
Hmm this is a bit problematic right now, because you might want to keep holding that circle to trigger certain other interactions - e.g. enabling the UI edit mode. You hold the circle and then press it on the other controller. I can add some flash indication that it's ready though. Alternatively I could change it so it checks if both of them are held at the same time, which would override the behavior.

The time can be increased, it's just a question of whether it'll be comfortable to the users, I don't want to make them wait too long for the dash to open/close.

It's a bit of a tricky thing due to the limited nature of the controllers.

**Comment by shiftyscales** [comment]
A confirming visual/flash in of itself would go far to help I think. A lot of the underlying issues that people have noted from the current system on Vive/WMR is accidentally opening the dash (I believe this is also in part due to the old gesture system again as well.)

While it would be good to keep them from waiting too long, I feel as a default, the time could be increased a little bit without adding significant delay and while adding a wider window for the context menu to open. (It's also still strange that there's a window where neither menu opens. Not sure why that would be.)

Once we eventually rework the settings, I feel that the hold time could be one of the many potential variables that we expose as a setting for those that want to tune it, e.g. if they want to make it snappier/more responsive like it is now.

**Comment by Frooxius** [comment]
The setting is already planned to be exposed. Right now it's just finding a good balance that works for most users.

**Comment by Frooxius** [comment]
Reworked the mechanism in 2020.9.9.214. Now it will auto open when it fills. To open the UI editing mode, you simply hold both at the same time. Hopefully this makes things easier!
